/** R tests are explicit offline fixtures. CPU canvas text/curves are not rasterized;
 * mesh/clock/resource checks and retained actor triangles are not native evidence. */
import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import{createHash}from'node:crypto';
import * as core from '../.test/core.mjs';
import {CombatTiming,COMBAT_TIMING,lungePush,stopLunge} from '../.test/combat-timing.mjs';
import {World} from '../.test/cpu-entry.mjs';import{World as PriorWorld}from'../.test/combat-timing-r-prior-world.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';
import {combatTimingRSpec,combatTimingRBaseline,combatTimingRIfDeclared} from './helpers/combat-timing-r-baseline.mjs';
const close=(a,b)=>assert(Math.abs(a-b)<1e-9,`${a} != ${b}`),sha=b=>createHash('sha256').update(b).digest('hex');
function rig(width=192,height=128,W=World){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;const c=cpuTestCanvas(width,height);c.canvas.ownerDocument=doc;const w=new W(c.canvas);return{w,c,media,close(){w.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};}
const draw=(k,s,dt=0,animate=false)=>{const e=s.effects.splice(0),before=structuredClone(s),eb=structuredClone(e);k.w.draw(s,dt,animate,e);assert.deepEqual(s,before);assert.deepEqual(e,eb);return e;};
const advance=(s,n)=>{for(let i=0;i<n;i++)core.step(s,core.IDLE,1/60);};
function ready(k,slot=0,lucca=false){const s=core.createState('forest');s.joined=true;if(lucca)s.kingdom.phase='rescue';assert(core.beginBattle(s));draw(k,s);for(let i=0;s.players[slot].atb<1&&i<300;i++)advance(s,1);assert(s.players[slot].atb>=1);draw(k,s);return s;}
function attack(k,slot=0,kind='attack',lucca=false){const s=ready(k,slot,lucca);assert(core.action(s,slot,kind));const effects=draw(k,s);assert(effects.some(e=>e.actor===slot&&e.origin&&e.style));return{s,start:s.ticks,source:effects.find(e=>e.actor===slot)};}
const snap=k=>({heroes:k.w.heroes.map(s=>s.mesh.position.asArray()),shadows:k.w.actorShadows.map(m=>m.position.asArray()),floats:k.w.floats.map(f=>({time:f.time,y:f.mesh.position.y})),strokes:k.w.slashes.map(v=>({time:v.time,scale:v.mesh.scaling.asArray(),alpha:v.mesh.material.alpha,enabled:v.mesh.isEnabled()}))});
const resources=k=>({meshes:k.w.scene.meshes.length,materials:k.w.scene.materials.length,textures:k.w.scene.textures.length});
const history=k=>k.w.inspect().combatTiming.history;
for(const [dt,animate]of[[0,false],[.001,true],[.0166666667,true],[.05,true],[2,true]])test(`R same tick ignores render delta ${dt}/${animate} for all owned combat transforms`,()=>{const k=rig();try{const{s}=attack(k);advance(s,12);draw(k,s);const before=snap(k),rows=history(k).length;for(let i=0;i<10;i++)draw(k,s,dt,animate);assert.deepEqual(snap(k),before);assert.equal(history(k).length,rows);}finally{k.close();}});
for(const [slot,kind,lucca]of[[0,'attack',false],[1,'attack',false],[0,'skill',false],[1,'skill',true]])test(`R original source direction and .55 distance for ${slot}/${kind}/${lucca}`,()=>{const k=rig();try{const{s,source}=attack(k,slot,kind,lucca);advance(s,13);draw(k,s);const d=Math.hypot(source.x-source.origin.x,source.z-source.origin.z)||1,p=s.players[slot],l=k.w.lunges[slot],push=Math.sin(13/60/.42*Math.PI),shadow=k.w.actorShadows[slot];close(l.time,13/60);close(l.dx,(source.x-source.origin.x)/d*.55);close(l.dz,(source.z-source.origin.z)/d*.55);close(shadow.position.x,p.x+l.dx*push);close(shadow.position.z,p.z+l.dz*push);assert.deepEqual(history(k).find(h=>h.kind==='lunge').source.effect,source);}finally{k.close();}});
test('R retains original lunge/stroke/number curve and strict expiry boundaries',()=>{const k=rig();try{const{s,start}=attack(k),number=k.w.floats[0].mesh,stroke=k.w.slashes[0].mesh;let last=0;for(const age of[12,13,25,26,36,37,75,76]){advance(s,age-last);last=age;draw(k,s);assert.equal(s.ticks,start+age);if(age<=75)close(number.position.y,2.2+age/60*.8);assert.equal(number.isDisposed(),age>75);assert.equal(stroke.isDisposed(),age>36);if(age<=36){close(stroke.scaling.x,1+age/60*.6);close(stroke.material.alpha,Math.max(0,1-age/60/.6));}if(age>=26)assert.equal(k.w.lunges[0].cue,undefined);}assert.deepEqual(history(k).filter(h=>h.phase==='expired').map(h=>[h.kind,h.ageTicks]),[['lunge',26],['stroke',37],['number',76]]);}finally{k.close();}});
test('R frozen simulation and resume do not accumulate background animation time',()=>{const k=rig();try{const{s}=attack(k);advance(s,8);draw(k,s);const before=snap(k);for(let i=0;i<60;i++)draw(k,s,30,false);assert.deepEqual(snap(k),before);advance(s,1);draw(k,s,30,true);close(k.w.floats[0].time,9/60);close(k.w.lunges[0].time,9/60);}finally{k.close();}});
test('R reduced preference is reversible at identical tick and keeps essential numbers stationary',()=>{const k=rig();try{const{s}=attack(k);advance(s,12);draw(k,s);const before=snap(k),r=resources(k);k.media.matches=true;draw(k,s);close(k.w.actorShadows[0].position.x,s.players[0].x);close(k.w.actorShadows[0].position.z,s.players[0].z);close(k.w.floats[0].mesh.position.y,2.2);assert.equal(k.w.slashes[0].mesh.isEnabled(),false);k.media.matches=false;draw(k,s);assert.deepEqual(snap(k),before);assert.deepEqual(resources(k),r);k.media.matches=true;advance(s,64);draw(k,s);assert.equal(k.w.floats.length,0);assert.equal(k.w.slashes.length,0);}finally{k.close();}});
for(const change of['hurt','dead','defeat','explore','identity','inactive'])test('R '+change+' interrupts only visual lunge without replay or rule writes',()=>{const k=rig();try{const slot=change==='inactive'?1:0,{s}=attack(k,slot);advance(s,7);draw(k,s);if(change==='hurt')k.w.posePlayers[slot].trigger('hurt',s.ticks);if(change==='dead')s.players[slot].hp=0;if(change==='defeat'||change==='explore')s.mode=change;if(change==='identity')s.players[slot]=structuredClone(s.players[slot]);if(change==='inactive'){s.opening.phase='canyon';s.kingdom.phase='none';}draw(k,s);assert.equal(k.w.lunges[slot].cue,undefined);close(k.w.lunges[slot].dx,0);const h=history(k).filter(h=>h.kind==='lunge').at(-1);assert.equal(h.phase,'interrupted');assert.deepEqual(h.actual.offset,{x:0,z:0});assert.equal(k.w.floats.length,1);}finally{k.close();}});
for(const change of['new-state','rewind','new-scene'])test('R '+change+' releases owned effect resources and timeline references',()=>{const k=rig();try{let{s}=attack(k);const meshes=[k.w.floats[0].mesh,k.w.slashes[0].mesh];if(change==='new-state')s=structuredClone(s);if(change==='rewind')s.ticks--;if(change==='new-scene')s.chapter='truce';draw(k,s);assert(meshes.every(m=>m.isDisposed()));assert.equal(k.w.floats.length,0);assert.equal(k.w.slashes.length,0);assert(history(k).length===0);assert(k.w.lunges.every(l=>!l.cue&&!l.owner));}finally{k.close();}});
test('R scene disposal releases recorded sources and live entry references',()=>{const k=rig();const{s}=attack(k),meshes=[k.w.floats[0].mesh,k.w.slashes[0].mesh];k.close();assert(meshes.every(m=>m.isDisposed()));assert.equal(k.w.combatTiming.inspect().disposed,true);assert.equal(k.w.combatTiming.inspect().history.length,0);assert.equal(k.w.floats.length,0);assert.equal(k.w.slashes.length,0);assert(k.w.lunges.every(l=>!l.owner&&!l.cue));});
test('R reset disposes temporary mesh/material/texture once, not actor resources',()=>{const k=rig();try{const{s}=attack(k);const hero=k.w.heroes[0],meshes=[k.w.floats[0].mesh,k.w.slashes[0].mesh],counts=[0,0];meshes.forEach((m,i)=>m.onDisposeObservable.add(()=>counts[i]++));k.w.resetTransientPresentation();k.w.resetTransientPresentation();assert.deepEqual(counts,[1,1]);assert.equal(hero.mesh.isDisposed(),false);assert.equal(hero.texture.isReady(),true);assert.equal(k.w.combatTiming.inspect().history.length,0);}finally{k.close();}});
test('R timing history is bounded, detached, monotone and from real delivered effects',()=>{const c=new CombatTiming();for(let tick=0;tick<30;tick++){c.begin(tick,false);const e={kind:'hit',x:1,z:2,text:'explicit offline fixture'},cue=c.cue(c.delivered(e));c.record('number',cue,0,{position:[1,2.2,2],enabled:true,disposed:false});e.x=9;}const h=c.inspect();assert.equal(h.history.length,24);assert.equal(h.historyDropped,6);assert(h.history.every(r=>r.source.effect.x===1));h.history[0].source.effect.x=50;assert.equal(c.inspect().history[0].source.effect.x,1);c.dispose();assert.throws(()=>c.delivered({}));assert.equal(c.inspect().history.length,0);});
for(const bad of[-1,1.5,NaN,Infinity])test('R rejects invalid presentation tick '+String(bad),()=>{const c=new CombatTiming();assert.throws(()=>c.begin(bad,false));});
test('R pure age and lunge helpers cannot accumulate or create a simulation clock',()=>{const c=new CombatTiming();c.begin(100,false);const cue=c.cue(c.delivered({kind:'hit',x:1,z:2,text:'offline'}));c.begin(112,true);close(c.seconds(cue),.2);close(lungePush(.21,false),1);assert.equal(lungePush(.21,true),0);assert.equal(lungePush(.42,false),0);const l={time:0,dx:.1,dz:.2,cue,owner:{}};stopLunge(l);assert.deepEqual(l,{time:1,dx:0,dz:0});assert(c.rewound(111));c.begin(111,false);assert.equal(c.inspect().history.length,0);});
for(const [width,height]of[[192,128],[256,160],[240,180]])test(`R actual actor CPU triangles move on elapsed ticks, unlike delta-zero Q ${width}x${height}`,()=>{const a=rig(width,height),b=rig(width,height,PriorWorld);try{const s=ready(a),p=structuredClone(s);draw(b,p);assert(core.action(s,0,'attack'));assert(core.action(p,0,'attack'));draw(a,s);draw(b,p);advance(s,13);advance(p,13);draw(a,s);draw(b,p);assert.deepEqual(s,p);assert.notDeepEqual(a.c.pixels(),b.c.pixels());let different=0;for(let i=0;i<a.c.pixels().length;i+=4)if(!a.c.pixels().subarray(i,i+4).every((x,j)=>x===b.c.pixels()[i+j]))different++;assert(different>0);const fixed=Buffer.from(a.c.pixels());draw(a,s,0,false);assert.deepEqual(Buffer.from(a.c.pixels()),fixed);advance(s,63);draw(a,s);close(a.w.actorShadows[0].position.x,s.players[0].x);close(a.w.actorShadows[0].position.z,s.players[0].z);assert.equal(a.w.floats.length,0);assert.equal(a.w.slashes.length,0);mkdirSync('test-results/combat-timing-offline',{recursive:true});writeFileSync(`test-results/combat-timing-offline/cpu-${width}x${height}.json`,JSON.stringify({scope:'offline actual CPU actor triangles; text/curves not rasterized; not native',width,height,differentPixels:different,fixedTickFrameIdentical:true,logicalStateUnchanged:true,expiredTransientCounts:a.w.inspect().transient}));}finally{b.close();a.close();}});
test('R export actual offline phases for independent Python checker, not native proof',()=>{const k=rig();try{const{s}=attack(k);let last=0;for(const age of[13,26,37,38,76]){advance(s,age-last);last=age;draw(k,s);}const observation={state:structuredClone(s),motion:k.w.inspect().combatTiming,transient:k.w.inspect().transient};mkdirSync('test-results/combat-timing-offline',{recursive:true});writeFileSync('test-results/combat-timing-offline/observation.json',JSON.stringify(observation,null,2));assert(history(k).filter(h=>h.phase==='expired').length>=3);}finally{k.close();}});
for(const name of Object.keys(combatTimingRSpec.files))test('R exact Q source inverse and missing/duplicate/unrelated rejection '+name,()=>{const raw=readFileSync(name,'utf8'),old=combatTimingRBaseline(name,raw),e=combatTimingRSpec.files[name][0];assert.equal(sha(old),combatTimingRSpec.originalSha256[name]);assert.equal(combatTimingRIfDeclared(name,old),old);for(const bad of[raw+e.after,raw.replace(e.after,''),raw+'\n// unrelated drift\n'])assert.throws(()=>combatTimingRBaseline(name,bad));});
test('R core/painters/MNOPQ/held-prologue/input/workflows remain exact Q bytes',()=>{for(const[name,h]of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03r-unchanged-inputs.json'))))assert.equal(sha(readFileSync(name)),h,name);});
