import test from 'node:test';
import assert from 'node:assert/strict';
import * as c from '../.test/core.mjs';
const ticks=(s,n=180,input=c.IDLE)=>{for(let i=0;i<n;i++)c.step(s,input,1/60);};
const ready=()=>{const s=c.createState();s.joined=true;c.beginBattle(s);ticks(s);return s;};
test('new game begins in exploration with two healthy actors',()=>{const s=c.createState();assert.equal(s.mode,'explore');assert.equal(s.players.length,2);assert.equal(s.players[0].hp,120);});
test('P1 movement does not steal P2 input ownership',()=>{const s=c.createState();s.joined=true;const p2={...s.players[1]};ticks(s,30,[{x:1,z:0},{x:0,z:0}]);assert.ok(s.players[0].x>-1);assert.equal(s.players[1].x,p2.x);});
test('P2 has independent movement',()=>{const s=c.createState();s.joined=true;ticks(s,30,[{x:0,z:0},{x:1,z:0}]);assert.equal(s.players[0].x,-1);assert.ok(s.players[1].x>1);});
test('diagonal movement is normalized',()=>{const a=c.createState(),b=c.createState();a.joined=b.joined=true;ticks(a,15,[{x:1,z:0},{x:0,z:0}]);ticks(b,15,[{x:1,z:1},{x:0,z:0}]);assert.ok(Math.abs(c.distance(a.players[0],{x:-1,z:-5})-c.distance(b.players[0],{x:-1,z:-5}))<1e-9);});
test('single-player companion follows',()=>{const s=c.createState();ticks(s,60,[{x:-1,z:0},{x:0,z:0}]);assert.ok(s.players[1].x<1);});
test('shared screen prevents unlimited player separation',()=>{const s=c.createState();s.joined=true;ticks(s,250,[{x:-1,z:0},{x:1,z:0}]);assert.ok(c.distance(...s.players)<=c.MAX_SEPARATION+.001);});
test('house walls and river block movement; bridge is walkable',()=>{assert.equal(c.walkable(-8,2),false);assert.equal(c.walkable(10,5),false);assert.equal(c.walkable(10,-1),true);assert.equal(c.walkable(20,0),false);});
test('movement cannot cross a house',()=>{const s=c.createState();s.players[0].x=-8;s.players[0].z=-2;ticks(s,120,[{x:0,z:1},{x:0,z:0}]);assert.ok(s.players[0].z<0);});
test('joining or dropping out is gated to exploration',()=>{const s=c.createState();assert.ok(c.setCoop(s,true));c.beginBattle(s);assert.equal(c.setCoop(s,false),false);assert.equal(s.joined,true);});
test('ATB reaches full at consistent simulated duration',()=>{const s=ready();assert.equal(s.players[0].atb,1);assert.equal(s.players[1].atb,1);});
test('ATB progression is independent of 30/60/144 Hz',()=>{const values=[30,60,144].map(hz=>{const s=c.createState();s.joined=true;c.beginBattle(s);for(let i=0;i<hz;i++)c.step(s,c.IDLE,1/hz);return s.players[0].atb;});assert.ok(Math.max(...values)-Math.min(...values)<1e-9);});
test('early attack does not spend resources or damage enemies',()=>{const s=c.createState();c.beginBattle(s);assert.equal(c.action(s,0,'attack'),false);assert.equal(s.enemies[0].hp,90);});
test('attack only spends the issuing actor ATB',()=>{const s=ready();assert.ok(c.action(s,0,'attack'));assert.equal(s.players[0].atb,0);assert.equal(s.players[1].atb,1);assert.equal(s.enemies[0].hp,60);});
test('skill checks and spends MP',()=>{const s=ready();assert.ok(c.action(s,1,'skill'));assert.equal(s.players[1].mp,15);assert.equal(s.enemies[1].hp,42);});
test('insufficient MP does not spend ATB',()=>{const s=ready();s.players[0].mp=2;assert.equal(c.action(s,0,'skill'),false);assert.equal(s.players[0].atb,1);});
test('coop combo requires both players to consent',()=>{const s=ready();assert.ok(c.requestCombo(s,0));assert.equal(s.players[0].mp,18);assert.equal(s.enemies[0].hp,90);assert.ok(c.requestCombo(s,1));assert.equal(s.players[0].mp,14);assert.equal(s.players[1].mp,14);assert.deepEqual(s.players.map(p=>p.atb),[0,0]);assert.deepEqual(s.enemies.map(e=>e.hp),[18,18]);});
test('combo is atomic if second player has insufficient MP',()=>{const s=ready();s.players[1].mp=3;c.requestCombo(s,0);assert.equal(c.requestCombo(s,1),false);assert.equal(s.players[0].mp,18);assert.equal(s.players[0].atb,1);});
test('normal attack cancels that actor combo reservation',()=>{const s=ready();c.requestCombo(s,0);c.action(s,0,'attack');assert.equal(s.combo[0],false);});
test('solo AI can participate in requested combo',()=>{const s=ready();s.joined=false;c.requestCombo(s,0);assert.deepEqual(s.players.map(p=>p.mp),[14,14]);});
test('dead player cannot issue attacks',()=>{const s=ready();s.players[0].hp=0;assert.equal(c.action(s,0,'attack'),false);});
test('victory is reached when all enemies are defeated',()=>{const s=ready();s.enemies.forEach(e=>e.hp=10);c.requestCombo(s,0);c.requestCombo(s,1);assert.equal(s.mode,'victory');assert.equal(s.flags.won,true);});
test('enemy attacks and eventual defeat resolve',()=>{const s=ready();s.players.forEach(p=>p.hp=1);ticks(s,900);assert.equal(s.mode,'defeat');});
test('return to village heals and clears encounter',()=>{const s=ready();c.leaveBattle(s);assert.equal(s.mode,'explore');assert.equal(s.enemies.length,0);assert.equal(s.players[0].hp,120);});
test('repair persists across time travel and cannot happen in future',()=>{const s=c.createState();c.travel(s);assert.equal(c.repair(s),false);c.travel(s);assert.ok(c.repair(s));c.travel(s);assert.equal(s.flags.repaired,true);assert.equal(s.flags.visitedFuture,true);assert.equal(c.repair(s),false);});
test('cannot travel or repair during battle',()=>{const s=ready();assert.equal(c.travel(s),false);assert.equal(c.repair(s),false);});
test('save round trip preserves era, party and event flags',()=>{const s=c.createState();c.setCoop(s,true);c.repair(s);c.travel(s);const loaded=c.deserialize(c.serialize(s));assert.equal(loaded.era,'future');assert.deepEqual(loaded.flags,s.flags);assert.equal(loaded.joined,true);assert.equal(loaded.players[0].x,s.players[0].x);});
test('saving is refused mid battle',()=>{assert.throws(()=>c.serialize(ready()));});
test('unsupported and malformed saves are rejected',()=>{assert.throws(()=>c.deserialize('{}'));assert.throws(()=>c.deserialize('not json'));const data=JSON.parse(c.serialize(c.createState()));data.version=2;assert.throws(()=>c.deserialize(JSON.stringify(data)));});
test('invalid coordinates and stats are rejected',()=>{for(const override of [{x:999},{x:-8,z:2},{hp:999},{mp:-1},{x:null}]){const data=JSON.parse(c.serialize(c.createState()));Object.assign(data.players[0],override);assert.throws(()=>c.deserialize(JSON.stringify(data)));}});
test('oversized saves and nonboolean flags are rejected',()=>{assert.throws(()=>c.deserialize(' '.repeat(65537)));const data=JSON.parse(c.serialize(c.createState()));data.flags.won='yes';assert.throws(()=>c.deserialize(JSON.stringify(data)));});
test('unknown save keys cannot change actor internals',()=>{const data=JSON.parse(c.serialize(c.createState()));data.players[0].atb=999;data.players[0].__proto__={hacked:true};const s=c.deserialize(JSON.stringify(data));assert.equal(s.players[0].atb,0);assert.equal(s.players[0].hacked,undefined);});
test('negative, infinite and NaN deltas do not advance simulation',()=>{const s=c.createState();for(const dt of [-1,NaN,Infinity])c.step(s,c.IDLE,dt);assert.equal(s.ticks,0);});
