import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {Scene,FreeCamera,Camera,Vector3,MeshBuilder,StandardMaterial,Color3,DynamicTexture,Texture,TransformNode} from '@babylonjs/core';
import {CpuEngine,createRenderEngine,webglOnly,renderCompatibleScene,inspectCpuRendering,World,createState} from '../.test/cpu-entry.mjs';
import {cpuBaseline} from './helpers/cpu-baseline.mjs';import {cpuTestCanvas} from './cpu-test-canvas.mjs';
const setup=()=>{const port=cpuTestCanvas(),engine=new CpuEngine(port.canvas,port.context);engine.createCanvas=(w,h)=>cpuTestCanvas(w,h).canvas;const scene=new Scene(engine),camera=new FreeCamera('cpu-camera',new Vector3(0,0,-4),scene);camera.setTarget(Vector3.Zero());camera.mode=Camera.ORTHOGRAPHIC_CAMERA;camera.orthoLeft=-2;camera.orthoRight=2;camera.orthoTop=1.5;camera.orthoBottom=-1.5;scene.activeCamera=camera;return {...port,engine,scene,camera,dispose(){scene.dispose();engine.dispose();}};};
test('four CPU wires reverse exactly to CI45; all scene owners, state/input/save and art remain untouched',()=>{const b=cpuBaseline(readFileSync('src/render.ts','utf8'));assert.equal(createHash('sha256').update(b).digest('hex'),'7e71659282287c4b8c8843cc53454805b6d517383c0da2413934e83ddc5b1450');const p=readFileSync('src/prologue-render.ts');assert.equal(createHash('sha1').update(`blob ${p.length}\0`).update(p).digest('hex'),'2711a74185aacf3c6bddf9db85ba99a2afbc507a');assert(!readFileSync('src/cpu-scene.ts','utf8').includes("'./core'"));});
test('actual Canvas2D capability fallback has no WebGL context and a bounded surface',()=>{const p=cpuTestCanvas();const engine=createRenderEngine(p.canvas);assert(engine instanceof CpuEngine);assert.equal(engine.webGLVersion,0);assert.equal(engine.getRenderingCanvas(),p.canvas);p.canvas.clientWidth=100000;p.canvas.clientHeight=100000;engine.resize();assert(engine.getRenderWidth()*engine.getRenderHeight()<=640*480);engine.dispose();const blocked={...p.canvas,getContext(){return null;}};assert.throws(()=>createRenderEngine(blocked),/Canvas2D/);});
test('CPU scene consumes Babylon geometry, world transforms, vertex colors and alpha textures',()=>{const k=setup();try{const m=MeshBuilder.CreatePlane('existing-mesh',{size:2},k.scene);const material=new StandardMaterial('original',k.scene);material.disableLighting=true;material.diffuseColor=new Color3(1,0,0);m.material=material;renderCompatibleScene(k.engine,k.scene);let v=inspectCpuRendering(k.engine);assert.equal(v.backend,'cpu-canvas2d');assert(v.cpu.fragments>0&&v.cpu.meshes===1);assert(k.pixels().some((n,i)=>i%4===0&&n===255));const before=k.pixels().slice();m.position.x=1;renderCompatibleScene(k.engine,k.scene);assert.notDeepEqual(k.pixels(),before);m.setEnabled(false);renderCompatibleScene(k.engine,k.scene);assert.equal(inspectCpuRendering(k.engine).cpu.meshes,0);}finally{k.dispose();}});
test('cached original texture pixels invalidate on the real texture update, not on each frame',()=>{const k=setup();try{const t=new DynamicTexture('same-runtime-canvas',{width:2,height:2},k.scene,false,Texture.NEAREST_SAMPLINGMODE),m=new StandardMaterial('painted',k.scene),mesh=MeshBuilder.CreatePlane('pixel-actor',{size:2},k.scene);const c=t.getContext();c.fillStyle='#ff0000';c.fillRect(0,0,2,2);t.update();m.disableLighting=true;m.diffuseTexture=t;mesh.material=m;renderCompatibleScene(k.engine,k.scene);const before=k.pixels().slice(),info=inspectCpuRendering(k.engine).cpu.textureMemory;renderCompatibleScene(k.engine,k.scene);assert.deepEqual(k.pixels(),before);assert.deepEqual(inspectCpuRendering(k.engine).cpu.textureMemory,info);c.fillStyle='#00ff00';c.fillRect(0,0,2,2);t.update();renderCompatibleScene(k.engine,k.scene);assert.notDeepEqual(k.pixels(),before);assert.equal(inspectCpuRendering(k.engine).cpu.unsupportedResources,0);}finally{k.dispose();}});
test('parent enablement, render callbacks, resize and copied diagnostic data stay coherent',()=>{const k=setup();try{const root=new TransformNode('original-root',k.scene),mesh=MeshBuilder.CreateBox('box',{},k.scene);mesh.material=new StandardMaterial('m',k.scene);mesh.parent=root;let before=0,after=0;k.scene.onBeforeRenderObservable.add(()=>before++);k.scene.onAfterRenderObservable.add(()=>after++);root.setEnabled(false);renderCompatibleScene(k.engine,k.scene);assert.equal(inspectCpuRendering(k.engine).cpu.meshes,0);root.setEnabled(true);renderCompatibleScene(k.engine,k.scene);assert.equal(before,2);assert.equal(after,2);let info=inspectCpuRendering(k.engine);info.cpu.meshSamples.length=0;assert(inspectCpuRendering(k.engine).cpu.meshSamples.length);k.canvas.clientWidth=80;k.canvas.clientHeight=80;k.engine.resize();renderCompatibleScene(k.engine,k.scene);assert.equal(k.pixels().length,80*80*4);}finally{k.dispose();}});
test('the unmodified World scene constructors build and draw through CPU without a browser or rule writes',()=>{
 const oldWindow=globalThis.window,oldDocument=globalThis.document;const p=cpuTestCanvas(96,64);
 const doc={createElement(tag){if(tag==='canvas')return cpuTestCanvas(1,1).canvas;return {style:{}};},getElementById(){return null;},addEventListener(){},removeEventListener(){}};
 p.canvas.ownerDocument=doc;globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};
 let world;try{world=new World(p.canvas);for(const chapter of [...readFileSync('src/fair-data.ts','utf8').split('export type Chapter =')[1].split(';')[0].matchAll(/'([a-z0-9]+)'/g),...readFileSync('src/trial-data.ts','utf8').split('export type TrialMap=')[1].split(';')[0].matchAll(/'([a-z0-9]+)'/g)].map(m=>m[1])){const s=createState(chapter),before=structuredClone(s);world.draw(s,0,false);assert.deepEqual(s,before,chapter);const r=world.inspectRenderer();assert.equal(r.backend,'cpu-canvas2d');assert(r.cpu.fragments>0,chapter);assert.equal(r.cpu.unsupportedResources,0,chapter);}}
 finally{world?.engine.dispose();globalThis.window=oldWindow;globalThis.document=oldDocument;}
});

test('only explicit WebGL preference disables CPU; empty/unknown preferences stay automatic',()=>{assert(webglOnly('?test=1&renderer=webgl'));for(const query of ['', '?renderer=auto', '?renderer=cpu', '?renderer=unknown'])assert(!webglOnly(query));const p=cpuTestCanvas();p.canvas.ownerDocument={defaultView:{location:{search:'?renderer=webgl'}}};assert.throws(()=>createRenderEngine(p.canvas),/僅使用 WebGL/);});
test('disposed original textures promptly release CPU pixel cache entries',()=>{const k=setup();try{const t=new DynamicTexture('owned-pixels',{width:16,height:16},k.scene,false);t.update();k.engine.readTexturePixels(t.getInternalTexture());assert.equal(k.engine.textureMemory().entries,1);t.dispose();assert.equal(k.engine.textureMemory().entries,0);assert.equal(k.engine.textureMemory().bytes,0);}finally{k.dispose();}});
