import test from 'node:test';import assert from 'node:assert/strict';
import {Scene,FreeCamera,Vector3,Camera,MeshBuilder,StandardMaterial,Color3,Color4,DirectionalLight,Material} from '@babylonjs/core';
import {CpuEngine,renderCompatibleScene,inspectCpuRendering,CpuRaster} from '../.test/cpu-entry.mjs';
import {CpuEngine as CEngine,renderCompatibleScene as renderC} from '../.test/visibility-baseline-cpu-entry.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';
function box(alpha,old=false,configure=()=>{}){const port=cpuTestCanvas(64,64),engine=new (old?CEngine:CpuEngine)(port.canvas,port.context),scene=new Scene(engine),camera=new FreeCamera('camera',new Vector3(0,5,-5),scene);scene.clearColor=new Color4(0,0,0,1);scene.ambientColor=Color3.Black();camera.setTarget(Vector3.Zero());camera.mode=Camera.ORTHOGRAPHIC_CAMERA;camera.orthoLeft=-1;camera.orthoRight=1;camera.orthoTop=1;camera.orthoBottom=-1;scene.activeCamera=camera;new DirectionalLight('lit-front',new Vector3(0,0,1),scene);const mesh=MeshBuilder.CreateBox('ordinary-box',{size:1},scene),material=new StandardMaterial('private-lit-box',scene);material.diffuseColor=Color3.White();mesh.material=material;mesh.visibility=alpha;configure({mesh,material,scene});try{(old?renderC:renderCompatibleScene)(engine,scene);return {pixels:port.pixels().slice(),info:old?null:inspectCpuRendering(engine).cpu.transparency};}finally{scene.dispose();engine.dispose();}}
for(const alpha of [.16,.5,.9,.99])test('D single-sided alpha '+alpha+' keeps front lighting; exact C reproduces dark backs',()=>{const a=box(alpha),old=box(alpha,true),opaque=box(1);const at=(32*64+32)*4;assert.equal(opaque.pixels[at],255);assert(Math.abs(a.pixels[at]-Math.round(255*alpha))<=1);assert(old.pixels[at]<a.pixels[at]);assert(a.info.faceCulled>0);assert.equal(a.info.profile,'vq03d-material-blend-face-culling');});
for(const alpha of [.16,.5,.99,1])test('D double-sided material remains byte-identical at '+alpha,()=>{const set=({material})=>{material.backFaceCulling=false;};const a=box(alpha,false,set),b=box(alpha,true,set);assert.deepEqual(a.pixels,b.pixels);assert.equal(a.info.faceCulled,0);});
for(const setup of [()=>{},({mesh})=>mesh.scaling.x=-1,({material})=>material.sideOrientation=Material.ClockWiseSideOrientation,({material})=>material.cullBackFaces=false])test('D opaque path remains exact for orientation option '+setup.toString(),()=>{const a=box(1,false,setup),b=box(1,true,setup);assert.deepEqual(a.pixels,b.pixels);assert.equal(a.info.faceCulled,0);});
test('D mirrored world determinant preserves the outside lit front',()=>{const a=box(.99),b=box(.99,false,({mesh})=>mesh.scaling.x=-1);assert.deepEqual(a.pixels,b.pixels);assert.equal(a.info.faceCulled,b.info.faceCulled);});
test('D cull-front and explicit reversed material orientation select the opposite side',()=>{const a=box(.99,false,({material})=>material.cullBackFaces=false),b=box(.99,false,({material})=>material.sideOrientation=Material.ClockWiseSideOrientation);assert.deepEqual(a.pixels,b.pixels);assert(a.info.faceCulled>0);assert.equal(a.pixels[(32*64+32)*4],0);});
test('D clipping then culling keeps winding and bounded raster without depth writes for blends',()=>{const v=(x,y,z=0)=>({x,y,z,w:1,u:0,v:0,r:1,g:0,b:0,a:1}),m={texture:null,opacity:null,opacityFromRGB:false,textureAlpha:false,alpha:.5,cutoff:0,blend:true,emission:[0,0,0]};for(const clipped of [false,true]){const a=v(-.8,-.8,clipped?-2:0),b=v(.8,-.8),c=v(0,.8);const front=new CpuRaster(20,20),back=new CpuRaster(20,20);front.clear([0,0,0]);back.clear([0,0,0]);front.triangle(a,b,c,{...m,cullSign:1});back.triangle(a,b,c,{...m,cullSign:-1});assert(front.fragments>0);assert.equal(back.fragments,0);assert(back.faceCulled>0);assert(front.depth.every(x=>x===Infinity));assert.equal(back.rgba.byteLength,1600);back.clear([0,0,0]);assert.equal(back.faceCulled,0);}});
for(const alpha of [.16,.5,.99])test('D authored material alpha '+alpha+' keeps original non-visibility blend bytes',()=>{const configure=({material})=>{material.alpha=alpha;};const a=box(1,false,configure),b=box(1,true,configure);assert.deepEqual(a.pixels,b.pixels);assert.equal(a.info.faceCulled,0);});
