/** Offline differential renderer tests; never injected into a browser or used as native evidence. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {Scene,FreeCamera,Camera,Vector3,MeshBuilder,StandardMaterial,DynamicTexture,HemisphericLight,DirectionalLight,PointLight,Color3,Matrix,VertexBuffer} from '@babylonjs/core';
import {CpuRaster,CpuScene,CpuEngine,opaqueMipChain,createState} from '../.test/cpu-hot-loop-i-api.mjs';
import {CpuRaster as PriorRaster,CpuScene as PriorScene} from '../.test/cpu-hot-loop-h-api.mjs';
import {ArtDirectedWorld as Current} from '../.test/cpu-hot-loop-i-world.mjs';import {ArtDirectedWorld as Prior} from '../.test/cpu-hot-loop-h-world.mjs';
import {productionWorldRig} from './helpers/production-world-rig.mjs';import {cpuTestCanvas} from './cpu-test-canvas.mjs';
const counts=['boundingPixels','candidatePixels','faceCulled','fractionalTriangles','minifiedTriangles','triangles','fragments','submitted','fastAccepted','trivialRejected','clipped'];
const vertex=(x,y,z=0,w=1)=>({x,y,z,w,u:x/2+.5,v:y/2+.5,r:.8,g:.5,b:.3,a:1});
const material=()=>({texture:null,opacity:null,opacityFromRGB:false,textureAlpha:false,alpha:1,cutoff:0,blend:false,emission:[0,0,0],cullSign:0});
let seed=105;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/2**32);
function texture(){return {width:8,height:8,rgba:Uint8ClampedArray.from({length:256},(_,i)=>i%4===3?[0,127,255][Math.floor(random()*3)]:random()*255),invertY:true,wrapU:1,wrapV:2,matrix:Array.from(Matrix.Identity().m)};}
function parity(primitives,w=63,h=39){const a=new CpuRaster(w,h),b=new PriorRaster(w,h);for(const r of[a,b]){r.clear([.17,.37,.71]);for(const p of primitives)r.triangle(...p);}assert.deepEqual(a.rgba,b.rgba);assert.deepEqual(a.depth,b.depth);for(const n of counts)assert.equal(a[n],b[n],n);return a;}
test('I 4000 deterministic triangles preserve all H pixels, Float32 depth and work counters',()=>{for(let batch=0;batch<20;batch++){const p=[];for(let n=0;n<200;n++){const v=()=>({...vertex(random()*4-2,random()*4-2,random()*3-1.5,random()*2+.01),u:random()*6-3,v:random()*6-3,r:random(),g:random(),b:random(),a:random()});p.push([v(),v(),v(),{...material(),texture:n%2?texture():null,opacity:n%5?null:texture(),textureAlpha:n%3===0,opacityFromRGB:n%7===0,blend:n%4===0,alpha:n%4===0?.5:1,cutoff:n%3===0?.3:0,cullSign:[0,-1,1][n%3]}]);}parity(p);}});
test('I transparent cutouts, separate opacity and RGB opacity retain exact alpha/depth boundaries',()=>{for(const alpha of[0,1/255,.5,1])for(const cutoff of[0,.5,1])for(const rgb of[false,true]){const t=texture();for(let i=3;i<t.rgba.length;i+=4)t.rgba[i]=alpha*255;parity([[vertex(-1,-1),vertex(1,-1),vertex(0,1),{...material(),texture:t,opacity:texture(),textureAlpha:true,opacityFromRGB:rgb,cutoff,blend:true}]]);}});
test('I row bounds preserve horizontal edges, signed zero, slivers and viewport clipping',()=>{for(const d of[0,-0,1e-12,-1e-12,1e-8,-1e-8,.01])for(const reverse of[false,true]){const p=[vertex(-1,-1),vertex(1,1),vertex(1-d,1)];if(reverse)p.reverse();parity([[...p,{...material(),blend:true,alpha:.5}],[...p,material()]],64,64);}});
test('I affine mip blend, wrap/UV/invert-Y and nearest alpha paths remain unchanged',()=>{for(const wrap of[0,1,2])for(const inverted of[false,true]){const t=texture();for(let i=3;i<t.rgba.length;i+=4)t.rgba[i]=255;t.wrapU=t.wrapV=wrap;t.invertY=inverted;t.mips=opaqueMipChain(t,32*1024*1024);const p=[{...vertex(-1,-1),u:-2,v:-4},{...vertex(1,-1),u:16,v:-4},{...vertex(0,1),u:-2,v:20}];parity([[...p,{...material(),texture:t}]],16,16);parity([[...p,{...material(),texture:t,textureAlpha:true,cutoff:.4}]],16,16);}});
test('I nonfinite vertex data are rejected; clear/resize limits remain bounded',()=>{for(const k of['x','y','z','w','u','v','r','g','b','a'])for(const v of[NaN,Infinity,-Infinity])assert.equal(parity([[{...vertex(0,0),[k]:v},vertex(1,0),vertex(0,1),material()]]).fragments,0);for(const size of[[0,1],[641,480],[Infinity,1]])assert.throws(()=>new CpuRaster(...size));const r=parity([],640,480);assert.equal(r.rgba.byteLength+r.depth.byteLength,640*480*8);});
test('I reusable lighting vectors preserve point/directional/hemisphere colors, normal fallback and changed meshes',()=>{const port=cpuTestCanvas(88,56),engine=new CpuEngine(port.canvas,port.context);engine.createCanvas=(w,h)=>cpuTestCanvas(w,h).canvas;const scene=new Scene(engine),camera=new FreeCamera('camera',new Vector3(0,1,-6),scene);camera.mode=Camera.ORTHOGRAPHIC_CAMERA;camera.setTarget(Vector3.Zero());camera.orthoLeft=-3;camera.orthoRight=3;camera.orthoTop=2;camera.orthoBottom=-2;
 const sky=new HemisphericLight('sky',Vector3.Up(),scene),key=new DirectionalLight('key',new Vector3(-.4,-1,.3),scene),point=new PointLight('point',new Vector3(1,2,-2),scene);point.range=8;const mat=new StandardMaterial('paint',scene);mat.diffuseColor=new Color3(.7,.5,.2);const mesh=MeshBuilder.CreateBox('box',{updatable:true},scene);mesh.material=mat;const a=new CpuScene(engine),b=new PriorScene(engine);
 try{for(let n=0;n<8;n++){mesh.position.x=(n-4)*.2;mesh.scaling.set(n%2?-1:1,1+n*.1,.8);mesh.rotation.y=n*.2;point.position.x=n*.4;key.direction.set(.3-n*.1,-1,.2);sky.intensity=.3+n*.05;mat.disableLighting=n===6;if(n===7)mesh.removeVerticesData(VertexBuffer.NormalKind);a.draw(scene);const pixels=port.pixels().slice(),ia=a.inspect();b.draw(scene);assert.deepEqual(port.pixels(),pixels);const ib=b.inspect();for(const k of['triangles','fragments','meshes','texturedSurfaces','unsupportedResources','work','sampling','bufferBytes','transparency','textureMemory'])assert.deepEqual(ia[k],ib[k],k);}
 }finally{scene.dispose();engine.dispose();}
});
const chapters=['bedroom','downstairs','overworld1000','fair','canyon','truce','forest','castle','chamber','cathedral','passage','sanctum','guardia1000','hall1000','courtroom','cellblock','futuregate'];
for(const ch of chapters)test('I actual '+ch+' composition and held/source pixels remain identical H',()=>{const a=productionWorldRig(Current,144,96),b=productionWorldRig(Prior,144,96),s=createState(ch),original=structuredClone(s);try{for(const minify of[false,true]){a.world.engine.setOpaqueMinification(minify);b.world.engine.setOpaqueMinification(minify);a.world.draw(s,0,false,[]);b.world.draw(s,0,false,[]);assert.deepEqual(a.canvas.pixels(),b.canvas.pixels());assert.deepEqual(a.world.inspect().renderer.cpu.work,b.world.inspect().renderer.cpu.work);assert.deepEqual(s,original);}}finally{b.close();a.close();}});
const route=JSON.parse(readFileSync('tests/fixtures/ci105-cpu-hot-loop.json'));
for(const pos of['before','after'])test('I original CI105 '+pos+' positions retain full CPU image and scene accounting',()=>{const a=productionWorldRig(Current,679,453),b=productionWorldRig(Prior,679,453),s=structuredClone(route[pos]),original=structuredClone(s);try{for(const minify of[false,true]){a.world.engine.setOpaqueMinification(minify);b.world.engine.setOpaqueMinification(minify);a.world.draw(s,0,false,[]);b.world.draw(s,0,false,[]);assert.equal(a.canvas.canvas.width,543);assert.equal(a.canvas.canvas.height,362);assert.deepEqual(a.canvas.pixels(),b.canvas.pixels());assert.deepEqual(a.world.inspect().renderer.cpu.work,b.world.inspect().renderer.cpu.work);assert.deepEqual(s,original);}}finally{b.close();a.close();}});
