import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as c from '../.test/core.mjs';
import * as e from '../.test/equipment.mjs';
import {newConduct} from '../.test/fair-conduct-data.mjs';
// Explicit isolated unit fixtures. Real browser acceptance never injects these states.
function shop(){const s=c.createState('fair');s.prologue.stage='fair';s.prologue.conduct=newConduct();Object.assign(s.players[0],{x:7.5,z:-6.3});return s;}
function bought(id='bronze-katana'){const s=shop();assert(c.tradeItem(s,id,1,true));return s;}
function kit(){let g=e.tradeEquipment(e.newEquipment(),'bronze-katana',1,true);g=e.tradeEquipment(g,'bronze-mail',1,true);g=e.tradeEquipment(g,'bronze-helm',1,true);return g;}
function settle(s){for(let i=0;i<30;i++)c.step(s,c.IDLE,1/60);}
const returned=readFileSync(new URL('./fixtures/returned-ci13-v5.json',import.meta.url),'utf8');
const fixtures=JSON.parse(readFileSync(new URL('./fixtures/equipment-legacy/manifest.json',import.meta.url),'utf8'));
function legacy(name){return readFileSync(new URL('./fixtures/equipment-legacy/'+name,import.meta.url),'utf8');}
function at(s,x,z){s.players.forEach((p,i)=>Object.assign(p,{x:x+i*.3,z}));Object.assign(s.rescue.guest,{x:x-.3,z});}
function talk(s,x,z){if(x!==undefined)at(s,x,z);const r=c.interactTrial(s,0);settle(s);return r;}
function fight(s){for(let n=0;n<1500&&s.mode==='battle';n++){c.step(s,c.IDLE,.05);for(const i of [0,1])if(s.players[i].atb>=1)c.action(s,i,'attack');}assert.equal(s.mode,'victory');c.leaveBattle(s);settle(s);}
function escortedGear(){const s=c.deserialize(returned);s.equipment=kit();assert(c.equipItem(s,'crono','bronze-katana'));at(s,0,-7.5);assert(c.interactFair(s,0));settle(s);return s;}
function prisonGear(){const s=escortedGear();talk(s,-2.9,4.5);talk(s,0,6);talk(s,0,0);talk(s,0,-2);c.chooseTrial(s,true);talk(s);c.chooseTrial(s,false);talk(s);talk(s);assert.equal(s.chapter,'cellblock');return s;}

test('default equipment is independent, reserves four kits and does not mutate a read-only visit',()=>{const a=e.newEquipment(),b=e.newEquipment(),s=c.createState();assert.equal(a.gold,400);assert.equal(e.freeCopies(a,'cloth-tunic'),0);a.worn.crono.body='bronze-mail';a.owned['cloth-tunic']=1;assert.equal(b.worn.crono.body,'cloth-tunic');assert.equal(b.owned['cloth-tunic'],4);assert.deepEqual(e.equipmentBonuses(null,'crono'),{attack:0,defense:0});assert.equal(s.equipment,null);assert.equal(JSON.parse(c.serialize(s)).version,1);});
test('catalog IDs are unique, costs integral and each role has a compatible starter weapon',()=>{assert.equal(new Set(e.EQUIPMENT.map(i=>i.id)).size,e.EQUIPMENT.length);for(const i of e.EQUIPMENT){assert(Number.isSafeInteger(i.price));assert(i.price>=0);assert(e.GEAR_SLOTS.includes(i.slot));assert(i.members.length>0);}assert.deepEqual(e.restoreEquipment(e.newEquipment()),e.newEquipment());});
test('buy, equip, sell and return to starter kit conserve copies and gold without mutating inputs',()=>{const initial=e.newEquipment(),copy=structuredClone(initial);let g=e.tradeEquipment(initial,'bronze-katana',1,true);assert.deepEqual(initial,copy);assert.equal(g.gold,250);g=e.wearEquipment(g,'crono','bronze-katana');assert.equal(e.freeCopies(g,'bronze-katana'),0);assert.equal(e.tradeEquipment(g,'bronze-katana',1,false),null);g=e.wearEquipment(g,'crono','wood-katana');g=e.tradeEquipment(g,'bronze-katana',1,false);assert.equal(g.gold,325);assert.equal(g.owned['bronze-katana'],0);assert.deepEqual(e.restoreEquipment(g),g);});
test('buying several units is atomic and repeated cycling cannot generate profit',()=>{let g=e.newEquipment();g=e.tradeEquipment(g,'bronze-helm',3,true);assert.equal(g.gold,160);assert.equal(g.owned['bronze-helm'],3);g=e.tradeEquipment(g,'bronze-helm',3,false);assert.equal(g.gold,280);assert.deepEqual(e.restoreEquipment(g),g);const before=structuredClone(g);assert.equal(e.tradeEquipment(g,'iron-katana',1,true),null);assert.deepEqual(g,before);});
for(const quantity of [0,-1,.5,100,NaN,Infinity,'1',true,null])test(`invalid quantity ${String(quantity)} leaves gear untouched`,()=>{const g=e.newEquipment(),before=structuredClone(g);assert.equal(e.tradeEquipment(g,'bronze-helm',quantity,true),null);assert.equal(e.tradeEquipment(g,'bronze-helm',quantity,false),null);assert.deepEqual(g,before);});
for(const id of ['missing','__proto__','constructor','cloth-cap','wood-katana'])test(`invalid or unsaleable item ${id} cannot mint currency`,()=>{const g=e.newEquipment();assert.equal(e.tradeEquipment(g,id,1,true),null);assert.equal(e.tradeEquipment(g,id,1,false),null);});
test('trade flags and stock/ledger/currency bounds fail closed',()=>{const g=e.newEquipment();assert.equal(e.tradeEquipment(g,'bronze-helm',1,'buy'),null);g.gold=999999;g.owned['bronze-helm']=99;assert.equal(e.tradeEquipment(g,'bronze-helm',1,true),null);assert.equal(e.tradeEquipment(g,'bronze-helm',1,false),null);g.gold=1000;g.owned['bronze-helm']=1;g.bought['bronze-helm']=9999;assert.equal(e.tradeEquipment(g,'bronze-helm',1,true),null);});
test('gear cannot be copied to a second actor or assigned to an incompatible owner/slot',()=>{let g=e.tradeEquipment(e.newEquipment(),'bronze-mail',1,true);g=e.wearEquipment(g,'marle','bronze-mail');assert.equal(e.wearEquipment(g,'crono','bronze-mail'),null);assert.equal(e.wearEquipment(g,'marle','bronze-mail'),null);assert.equal(e.wearEquipment(g,'frog','wood-katana'),null);assert.equal(e.wearEquipment(g,'fake','bronze-mail'),null);assert.equal(e.wearEquipment(g,'crono','iron-katana'),null);assert.equal(e.tradeEquipment(g,'bronze-mail',1,false),null);});
test('only an actual visible merchant proximity enables shop, without inventing pendant testimony',()=>{const s=shop(),facts=structuredClone(s.prologue.conduct);assert(c.shopAvailable(s));assert(c.tradeItem(s,'bronze-katana',1,true));assert.deepEqual(s.prologue.conduct,facts);s.players[0].x=0;const before=structuredClone(s);assert.equal(c.tradeItem(s,'bronze-helm',1,true),false);assert.deepEqual(s,before);});
for(const [name,change] of [
 ['battle',s=>s.mode='battle'],['victory',s=>s.mode='victory'],['defeat',s=>s.mode='defeat'],['another map',s=>s.chapter='lab'],
 ['time travel',s=>s.opening.phase='lost'],['rescue',s=>s.rescue.stage='allied'],['hidden merchant',s=>s.prologue.conduct=null],['sealed conduct',s=>s.prologue.conduct.sealed=true],
 ['kingdom phase',s=>s.kingdom.phase='rescue'],['early waking',s=>s.prologue.stage='waking'],['pendant choice',s=>s.prologue.choice='sell-pendant'],['trial choice',s=>s.trial.choice='wealth'],['candy wait',s=>s.prologue.conduct.candy='waiting']
])test(`shop rejects ${name} with no partial stock or balance mutation`,()=>{const s=shop();change(s);const before=structuredClone(s);assert.equal(c.shopAvailable(s),false);assert.equal(c.tradeItem(s,'bronze-katana',1,true),false);assert.deepEqual(s,before);});
test('equipment follows story identity: absent Lucca/Frog cannot be activated, autonomous guest stays autonomous',()=>{const s=bought('bronze-mail');assert.equal(c.equipItem(s,'lucca','bronze-mail'),false);assert.equal(c.equipItem(s,'frog','bronze-mail'),false);assert.equal(s.players.length,2);s.kingdom.phase='rescue';s.rescue.stage='allied';s.chapter='cathedral';assert.equal(c.partyMember(s,1),'lucca');assert(c.equipItem(s,'frog','bronze-mail'));assert.equal(s.joined,false);assert.equal(s.players.length,2);assert.equal(c.equipItem(s,'crono','bronze-mail'),false);assert.equal(s.equipment.worn.marle.body,'cloth-tunic');});
test('all four present story identities can equip their own weapons, never each other’s',()=>{const s=shop();s.equipment=e.newEquipment();for(const [m,id] of [['crono','bronze-katana'],['marle','iron-bow'],['lucca','dart-gun'],['frog','steel-sword']]){const g=e.tradeEquipment(e.newEquipment(),id,1,true);s.equipment=g;s.prologue.stage='companions';s.kingdom.phase=(m==='lucca'||m==='frog')?'rescue':'none';s.rescue.stage=m==='frog'?'allied':'none';assert(c.equipItem(s,m,id));assert.equal(e.equipmentBonuses(s.equipment,m).attack,6);}});
test('equipping during battle, cinematic or unresolved choice is rejected, never changes ATB',()=>{for(const change of [s=>s.mode='battle',s=>s.trial.fade=.3,s=>s.prologue.choice='company']){const s=bought();change(s);const before=structuredClone(s);assert.equal(c.equipItem(s,'crono','bronze-katana'),false);assert.deepEqual(s,before);}});
test('weapon affects an actual normal attack but not skill MP, ATB or spell strength',()=>{const s=bought();assert(c.equipItem(s,'crono','bronze-katana'));assert(c.beginBattle(s));s.players[0].atb=1;const hp=s.enemies[0].hp,mp=s.players[0].mp;assert(c.action(s,0,'attack'));assert.equal(s.enemies[0].hp,hp-36);assert.equal(s.players[0].mp,mp);assert.equal(s.players[0].atb,0);s.players[0].atb=1;assert(c.action(s,0,'skill'));assert.equal(s.enemies[0].hp,hp-36-48);assert.equal(s.players[0].mp,mp-3);});
test('armor reduces a real enemy turn, not healing costs or maximum HP',()=>{const s=bought('bronze-mail');assert(c.equipItem(s,'crono','bronze-mail'));assert(c.beginBattle(s));s.enemies[0].atb=1;const hp=s.players[0].hp;c.step(s,c.IDLE,1/60);assert.equal(s.players[0].hp,hp-9);assert.equal(c.MAX_HP,120);assert.equal(c.MAX_MP,18);assert.equal(s.equipment.gold,280);});
test('Frog weapon affects independent guest ATB without granting P3 or consuming P1 gauge',()=>{const s=c.deserialize(legacy('v5.json'));s.equipment=e.tradeEquipment(e.newEquipment(),'steel-sword',1,true);assert(c.equipItem(s,'frog','steel-sword'));assert(c.beginBattle(s));s.rescue.guest.atb=.999;s.players.forEach(p=>p.atb=0);const before=s.enemies.reduce((n,x)=>n+x.hp,0);c.step(s,c.IDLE,1/60);assert.equal(s.enemies.reduce((n,x)=>n+x.hp,0),before-32);assert(s.players.every(p=>p.atb<.01));assert.equal(s.players.length,2);});

for(const f of fixtures.files)test(`unaltered real CI18 v${f.version} save wraps and reloads equipment without rewriting adventure provenance`,()=>{const raw=legacy(f.file);assert.equal(createHash('sha256').update(raw).digest('hex'),f.sha256);const s=c.deserialize(raw),canonical=c.serialize(s);assert.equal(JSON.parse(canonical).version,f.version);assert.equal(s.equipment,null);s.equipment=kit();const encoded=c.serialize(s),v=JSON.parse(encoded);assert.equal(v.version,8);assert.equal(v.adventure,canonical);const r=c.deserialize(encoded);assert.deepEqual(r.equipment,s.equipment);assert.equal(r.chapter,s.chapter);assert.deepEqual(r.trial,s.trial);assert.equal(c.serialize(r),encoded);});
test('equipment persists across real trial transition; immutable returned history is v5, not recursive v8',()=>{const s=escortedGear(),data=JSON.parse(c.serialize(s));assert.equal(data.version,8);assert.equal(JSON.parse(data.adventure).version,7);assert.equal(JSON.parse(s.trial.history).version,5);const d=c.deserialize(c.serialize(s));assert.equal(d.equipment.gold,50);assert.equal(d.equipment.worn.crono.weapon,'bronze-katana');assert.equal(d.trial.history,s.trial.history);assert.equal(c.activeSlot(d,1),false);assert.equal(c.equipItem(d,'lucca','air-gun'),false);});
test('v8 prison equipment survives saves, normal guard battle, Lucca return and tank fire shield',()=>{const s=prisonGear();assert.equal(c.activeSlot(s,1),false);for(let i=0;i<3;i++)talk(s,0,-1.3);fight(s);talk(s,0,6);at(s,0,-.5);c.step(s,c.IDLE,.05);fight(s);talk(s,0,6);assert.equal(s.chapter,'warden');const restored=c.deserialize(c.serialize(s));assert.deepEqual(restored.equipment,s.equipment);talk(s,0,6);at(s,3.7,0);c.step(s,c.IDLE,.05);assert.equal(s.trial.encounter,'tank');s.targets[1]=0;s.players[1].atb=1;const hp=s.enemies[0].hp,mp=s.players[1].mp;assert(c.action(s,1,'skill'));assert.equal(s.enemies[0].hp,hp);assert.equal(s.players[1].mp,mp-3);s.players[0].atb=1;s.targets[0]=0;assert(c.action(s,0,'attack'));assert.equal(s.enemies[0].hp,hp-36);});
for(const [name,modify] of [
 ['schema',o=>o.schema=2],['unearned gold',o=>o.gold++],['fractional balance',o=>o.gold=.5],['unearned stock',o=>o.owned['iron-katana']=1],
 ['negative count',o=>o.owned['bronze-katana']=-1],['fractional ledger',o=>o.bought['bronze-katana']=.5],['null count',o=>o.owned['iron-katana']=null],
 ['array inventory',o=>o.owned=[]],['unknown inventory',o=>o.owned.hack=0],['oversize ledger',o=>o.bought['bronze-katana']=10000],
 ['starter sale',o=>o.sold['wood-katana']=1],['incompatible weapon',o=>o.worn.marle.weapon='wood-katana'],['unknown actor',o=>o.worn.robo=o.worn.crono],
 ['missing actor',o=>delete o.worn.frog],['unknown slot',o=>o.worn.crono.accessory='cloth-cap'],['unowned worn item',o=>o.worn.crono.weapon='iron-katana'],
 ['duplicated worn item',o=>{o.worn.crono.body='bronze-mail';o.worn.marle.body='bronze-mail';}],['missing slot',o=>delete o.worn.crono.head]
])test(`v8 rejects ${name}; no original state lost`,()=>{const s=c.createState();s.equipment=kit();const original=c.serialize(s),data=JSON.parse(original);modify(data.equipment);assert.throws(()=>c.deserialize(JSON.stringify(data)));assert.equal(c.serialize(s),original);});
for(const [name,modify] of [['wrong outer schema',o=>o.schema='unknown'],['object adventure',o=>o.adventure={}],['recursive v8',o=>o.adventure=JSON.stringify(o)],['zero adventure version',o=>o.adventure='{"version":0}'],['array adventure',o=>o.adventure='[]'],['oversize adventure',o=>o.adventure=' '.repeat(49153)],['missing gear',o=>delete o.equipment]])test(`v8 envelope rejects ${name}`,()=>{const s=c.createState();s.equipment=kit();const o=JSON.parse(c.serialize(s));modify(o);assert.throws(()=>c.deserialize(JSON.stringify(o)));});
test('unknown top-level runtime fields are filtered; ledger is conservation validation, not proof of historic earnings',()=>{const s=c.createState();s.equipment=kit();const o=JSON.parse(c.serialize(s));o.mode='victory';o.flags={won:true};o.equipment.atb=1;const r=c.deserialize(JSON.stringify(o));assert.equal(r.mode,'explore');assert.equal(r.flags.won,false);assert(!('atb'in r.equipment));assert.equal(r.equipment.gold,50);});
test('DOM actions require the existing inventory ownership and keep disabled-action focus on its stable in-modal row',()=>{const ui=readFileSync(new URL('../src/equipment-ui.ts',import.meta.url),'utf8'),main=readFileSync(new URL('../src/main.ts',import.meta.url),'utf8');assert(ui.includes('if(canAct())action()'));assert(ui.includes('retainPanelPosition(root)'));assert(ui.includes('restorePosition()'));assert(ui.includes('row.dataset.focusRow=item.id'));assert(ui.includes('row.tabIndex=-1'));assert(main.includes('()=>bagOpen&&!manualPause&&!document.hidden'));assert(!ui.includes('innerHTML'));});
