import {runtimeBaselineBytes} from './helpers/runtime-baseline.mjs';
// VQ02B explicitly advances only renderer/main pins for requested context/density wiring.
// Original draw/camera/scene functions are verified in render-preserved.test.mjs.
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {Vector3,Mesh,MeshBuilder,VertexData,StandardMaterial} from '@babylonjs/core';
import {festivalTestScene} from './festival-test-scene.mjs';
import {buildFair} from '../.test/fair-render.mjs';
import {EarlyOcclusion} from '../.test/early-occlusion.mjs';
import {fairOcclusionPoints} from '../.test/fair-occlusion-points.mjs';
import {createState} from '../.test/core.mjs';
import {World} from '../.test/render.mjs';
import {drawSurface} from '../.test/world-art.mjs';
import {drawFairPaving} from '../.test/early-art.mjs';
import {surface} from '../scripts/asset-export.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
const tag=(mesh,group='test-canopy')=>{mesh.metadata={artKit:'vq01',kind:'awning',gameCollision:false,occlusionGroup:group};return mesh;};
function simple(){const k=festivalTestScene(),o=new EarlyOcclusion(k.scene);const m=tag(MeshBuilder.CreateBox('cloth',{size:2},k.scene));m.position.z=0;m.material=new StandardMaterial('shared',k.scene);return {...k,o,m,update(t=0,points=[new Vector3(0,0,3)],chapter='fair'){o.update(t,chapter,Vector3.Forward(),points);},close(){o.dispose();k.dispose();}};}
test('retained festival paving is used byte-for-byte by drawSurface without replacing forest layout',()=>{
 const a=surface(512,512),b=surface(512,512);drawSurface(a.ink,512,512,'fair');drawFairPaving(b.ink,512,512);assert.deepEqual(a.rgba,b.rgba);
 const forest=surface(384,352);drawSurface(forest.ink,384,352,'forest');assert.equal(sha(forest.rgba),'855dffc91ac0275eeee13aa2784f0b9ca87861be798d4dc6e2bf4d2f30d169ac');
});
test('saved painters/kit are not repainted and held renderer remains exact',()=>{
 for(const [p,h] of Object.entries({"src/early-art.ts": "12b0f9db63ff3cf0e22bda3a758ca3d3a33995c6c74c4c7b431a8a94f38a4b10", "src/surface-layout.ts": "5a0e6520e80dbd609b6e5ebaab93c78e5be1a67b5b3068261336a36d8d7fb995", "src/early-kit.ts": "b66cbaf7778652424f75c257d41f6b83211b3b426e95b3dd59cb42b5f4b4faea", "src/hd-hero-art.ts": "5669a62f90149d6162036190ebae9616cb76db39b8bb36ca4d60c246a65ec39a", "src/witness-art.ts": "a1b671039b2fda7a4f504d825b1e08b326b2dd8c03e03f4029e7381612751ea2", "src/fair-conduct-render.ts": "56907ec0a785c3cb9cb0119372ac9bd3cb6a572330f458a75f44ee89f515849a", "src/fair-data.ts": "2b8468df90484e17b346aef4e3ecd0205a68ff49bff40a455dbf2b38904e2115", "src/core.ts": "d8a7cf8f2f0bf9f66715a22e4a4896f6b74415b19e48c660e392bd56278ecd6d", "src/main.ts": "89c2980be9219b0cd80408b10524250e9a97afa3321a39acb782f8cfc484d120", "src/input.ts": "f4e49695188d941194c2bcdbc737fa7e0bc9f8d5f1d7d04ca6a325c50d2dded8", "src/early-comfort.ts": "1e0785e83acbe50490a40d2b18586de00649d9d3314ea63538af9b6217dfec1b", "src/camera-motion.ts": "204c37b179202f7672aaecc144cdf8ca2524ba307489ac7c5573957bd372ac44", "src/sprite-contact.ts": "52bf06b4245d85fdec9def280c504b6c9fc4ed57e8baafea9b8c9698deb8f0fa"}))assert.equal(sha(runtimeBaselineBytes(p,readFileSync(p))),h,p);
 const b=readFileSync('src/prologue-render.ts');assert.equal(createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex'),'2711a74185aacf3c6bddf9db85ba99a2afbc507a');
});
test('complete fair assembly reuses bounded stalls, separate curved canopies and existing native witnesses',()=>{
 const k=festivalTestScene();try{const fair=buildFair(k.scene,k.shadow),s=createState('fair');fair.root.setEnabled(true);const before=structuredClone(s);fair.draw(s,0);k.scene.render();assert.deepEqual(s,before);
 const v=fair.inspect(),g=v.festival.geometry;assert.equal(v.festival.approved,false);assert.equal(v.festival.collisionSource,'FAIR_STALLS');assert(g.decorativeOnly);assert.equal(g.awnings.length,24);assert.equal(g.canopyGroups.length,3);
 for(const a of g.awnings){assert.equal(a.vertices,36);assert.equal(a.triangles,32);assert(a.heightSpan>.35);}
 assert(v.festival.models.some(m=>m.id.includes('earthenware')));assert(v.festival.models.some(m=>m.id.includes('cloth-roll')));assert(v.festival.models.some(m=>m.id.includes('sweet')));assert(v.festival.models.some(m=>m.id.includes('telepod-coil')));
 assert.equal(v.vendors.actors.length,3);assert(v.vendors.actors.every(a=>a.kind==='shopper'));assert.equal(v.vendorContacts.length,4);
 for(const a of v.vendorContacts){assert(a.footError<1e-5);assert(a.shadow.visible);assert(Math.hypot(a.shadow.x-a.foot.x,a.shadow.y-a.foot.y,a.shadow.z-a.foot.z)<1e-5);}
 for(const a of v.vendors.actors)assert.deepEqual({...k.scene.getMeshByName(a.name).material.diffuseTexture.getSize()},{width:48,height:64});
 const ids=new Set(g.canopyGroups);for(const m of k.scene.meshes.filter(m=>m.metadata?.occlusionGroup))assert(ids.has(m.metadata.occlusionGroup));
 v.festival.models[0].id='mutable-observation';assert.notEqual(fair.inspect().festival.models[0].id,'mutable-observation');
 }finally{k.dispose();}
});
test('whole bell swings at one pivot, vendor animation freezes at fixed ticks, Lucca shadow hides with her',()=>{
 const k=festivalTestScene();try{const fair=buildFair(k.scene,k.shadow),s=createState('fair');fair.root.setEnabled(true);s.fair.bellHeard=true;fair.draw(s,0);const first=fair.inspect();s.ticks=190;fair.draw(s,1);const next=fair.inspect();assert.notDeepEqual(next.vendors,first.vendors);
 const bell=k.scene.getTransformNodeByName('leene-bell-assembly');assert.equal(bell.getChildMeshes().length,4);assert(next.bell.swing!==0);assert(bell.getChildMeshes().every(m=>m.parent===bell));
 for(let n=0;n<4;n++)fair.draw(s,1);assert.deepEqual(fair.inspect().vendors,next.vendors);assert.equal(fair.inspect().bell.swing,next.bell.swing);
 s.rescue.stage='returned';fair.draw(s,1);assert(!k.scene.getMeshByName('lucca-handdrawn-contact').isEnabled());assert.equal(fair.inspect().vendorContacts.length,3);
 }finally{k.dispose();}
});
test('triangle hit fades only tagged group and never shared material alpha or unrelated geometry',()=>{const k=simple();try{const untagged=MeshBuilder.CreateBox('wall',{size:2},k.scene);untagged.material=k.m.material;k.update();assert.equal(k.m.visibility,.3);assert.equal(untagged.visibility,1);assert.equal(k.m.material.alpha,1);assert(k.o.inspect().groups[0].blocked);}finally{k.close();}});
test('triangle rays do not fade a bounding-box hole',()=>{const k=simple();try{k.m.dispose();const mesh=tag(new Mesh('triangle',k.scene)),v=new VertexData();v.positions=[-1,-1,0,1,-1,0,-1,1,0];v.indices=[0,1,2];v.applyToMesh(mesh);k.update(0,[new Vector3(.75,.75,3)]);assert.equal(mesh.visibility,1);assert.equal(k.o.inspect().groups[0].blocked,false);}finally{k.close();}});
test('orthographic rays remain parallel for an off-center actor',()=>{const k=simple();try{k.m.position.x=9;k.update(0,[new Vector3(9,0,3)]);assert.equal(k.m.visibility,.3);assert(k.o.inspect().groups[0].blocked);}finally{k.close();}});
test('foreground group is independent of another canopy and actor endpoint/behind it',()=>{const k=simple();try{const m=tag(MeshBuilder.CreateBox('other',{size:1},k.scene),'other');m.position.set(5,0,0);k.update();assert.equal(m.visibility,1);k.m.position.z=5;k.update(100);assert.equal(k.o.inspect().groups.find(g=>g.id==='test-canopy').blocked,false);}finally{k.close();}});
test('pause keeps fade amount unchanged and resume consumes simulation ticks only',()=>{const k=simple();try{k.update(0,[]);k.update(3);const v=k.m.visibility;assert(v>.3&&v<1);for(let i=0;i<50;i++)k.update(3);assert.equal(k.m.visibility,v);k.update(12);assert(k.m.visibility<v);}finally{k.close();}});
test('clear hold then restoration is stable across frame partitions',()=>{const a=simple(),b=simple();try{a.update();b.update();a.update(11,[]);assert.equal(a.m.visibility,.3);a.update(42,[]);for(let t=1;t<=42;t++)b.update(t,[]);assert(Math.abs(a.m.visibility-b.m.visibility)<1e-12);assert(a.m.visibility>.9);}finally{a.close();b.close();}});
test('fresh-state reset removes old fade even when import ticks equal previous ticks',()=>{const k=simple();try{k.update(200);assert.equal(k.m.visibility,.3);const port={floats:[],slashes:[],posePlayers:[{reset(){}}],guestPose:{reset(){}},poseHistory:[],lunges:[],fairWorld:{resetOcclusion:()=>k.o.reset()}};World.prototype.resetTransientPresentation.call(port);assert.equal(k.m.visibility,1);assert.equal(k.o.inspect().tick,null);k.update(200,[]);assert.equal(k.m.visibility,1);}finally{k.close();}});
test('map exit, tick rollback and invalid camera each restore the original mesh visibility',()=>{const k=simple();try{k.m.visibility=.8;k.update();assert.equal(k.m.visibility,.24);k.update(10,[],'outside-festival');assert.equal(k.m.visibility,.8);k.update(100);k.update(1,[]);assert.equal(k.m.visibility,.8);k.update(2);k.o.update(3,'fair',new Vector3(NaN,0,1),[]);assert.equal(k.m.visibility,.8);}finally{k.close();}});
test('disabled parent resets group and observer discovers later meshes without stale references',()=>{const k=simple();try{k.update();k.m.setEnabled(false);k.update(1);assert.equal(k.m.visibility,1);const m=tag(MeshBuilder.CreateBox('late',{size:2},k.scene),'late');k.update(2);assert(k.o.inspect().groups.some(g=>g.id==='late'&&g.blocked));m.dispose();k.update(3);assert(!k.o.inspect().groups.some(g=>g.id==='late'));}finally{k.close();}});
test('decorative-only opt-in excludes tagged collision and malformed groups',()=>{const k=simple();try{k.m.metadata.gameCollision=true;k.update();assert.equal(k.m.visibility,1);assert.deepEqual(k.o.inspect().groups,[]);const other=MeshBuilder.CreateBox('no-group',{size:2},k.scene);other.metadata={artKit:'vq01',gameCollision:false};k.update(1);assert.equal(other.visibility,1);}finally{k.close();}});
test('dispose restores visibility and removes the mesh observer',()=>{const k=simple();try{k.update();const count=k.scene.onNewMeshAddedObservable.observers.length;k.o.dispose();assert.equal(k.m.visibility,1);assert.equal(k.scene.onNewMeshAddedObservable.observers.filter(x=>!x._willBeUnregistered).length,count-1);}finally{k.dispose();}});
test('actual billboard points track scale, parent and lunge transform without state writes',()=>{const k=festivalTestScene();try{const mesh=MeshBuilder.CreatePlane('actor',{width:1.35,height:1.85},k.scene);mesh.billboardMode=Mesh.BILLBOARDMODE_ALL;mesh.position.set(4,1.1,2);mesh.scaling.setAll(.46);const before=mesh.position.clone(),pts=fairOcclusionPoints([{id:'p0',mesh}]);assert.equal(pts.length,9);assert.deepEqual(mesh.position.asArray(),before.asArray());const span=Math.max(...pts.map(p=>p.x))-Math.min(...pts.map(p=>p.x));assert(Math.abs(span-1.35*.46*.56)<1e-6);mesh.position.x+=.6;const moved=fairOcclusionPoints([{id:'p0',mesh}]);assert(Math.abs(moved[0].x-pts[0].x-.6)<1e-6);mesh.setEnabled(false);assert.deepEqual(fairOcclusionPoints([{id:'p0',mesh}]),[]);}finally{k.dispose();}});
test('real merged festival canopy hits a walkable actor position; no synthetic blocker required',()=>{const k=festivalTestScene();try{const fair=buildFair(k.scene,k.shadow);fair.root.setEnabled(true);const mesh=MeshBuilder.CreatePlane('player',{width:1.35,height:1.85},k.scene);mesh.billboardMode=Mesh.BILLBOARDMODE_ALL;const up=k.camera.getDirection(Vector3.Up());mesh.position.copyFrom(new Vector3(-8,.14,-4.05).add(up.scale(1.85*(62/64-.5))));const o=new EarlyOcclusion(k.scene);o.update(0,'fair',k.camera.getDirection(Vector3.Forward()),fairOcclusionPoints([{id:'p0',mesh}]));assert(o.inspect().groups.some(g=>g.id==='vq01-festival-cloth-canopy'&&g.blocked));assert(o.inspect().groups.filter(g=>g.blocked).every(g=>g.id==='vq01-festival-cloth-canopy'));o.dispose();}finally{k.dispose();}});
test('production scope keeps framing, input and held renderer intact; observer runs after camera',()=>{const s=readFileSync('src/render.ts','utf8');assert(s.indexOf('this.fairWorld.updateOcclusion(')>s.indexOf('this.frameEarlyScene(s,ratio'));const fair=readFileSync('src/fair-render.ts','utf8');assert.match(fair,/root.isEnabled\(\)\?'fair':'outside-festival'/);assert.match(s,/fairWorld\?\.resetOcclusion\?\.\(\)/);assert.match(fair,/onDisposeObservable.add/);assert.doesNotMatch(readFileSync('src/fair-occlusion-points.ts','utf8'),/\.position\.set|\.hp\s*=|\.alpha\s*=/);});
