import {rescueSIfDeclared} from './helpers/rescue-s-baseline.mjs';
import {partyPIfDeclared} from './helpers/party-p-baseline.mjs';
/** Unit/CPU ports only. Synthetic fixtures below are never native evidence. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import * as core from '../.test/core.mjs';import {FIELD_BODY,bodyEnvelope} from '../.test/field-enemy-body.mjs';
import {World} from '../.test/cpu-entry.mjs';import {World as PriorWorld} from '../.test/body-o-prior-world.mjs';import {bodyOSpec,bodyOBaseline,bodyOIfDeclared} from './helpers/body-o-baseline.mjs';import {cpuTestCanvas} from './cpu-test-canvas.mjs';
const battle=(chapter='canyon')=>{const s=core.createState(chapter);if(chapter==='canyon')s.opening.phase='canyon';assert(core.beginBattle(s));return s;};
const advance=(s,n)=>{for(let i=0;i<n;i++)core.step(s,core.IDLE,1/60);};
function rig(width=96,height=64,WorldType=World){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};
 globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;
 const c=cpuTestCanvas(width,height);c.canvas.ownerDocument=doc;const w=new WorldType(c.canvas);return {w,media,c,close(){w.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};
}
function draw(k,s){const effects=s.effects.splice(0),before=structuredClone(s),eb=structuredClone(effects);k.w.draw(s,0,false,effects);assert.deepEqual(s,before);assert.deepEqual(effects,eb);return k.w.inspect().fieldEnemyBody;}
const near=(a,b)=>assert(Math.abs(a-b)<1e-10,`${a} != ${b}`);
const residue=k=>({mesh:k.w.scene.meshes.filter(m=>m.name.startsWith('field-remnant-')).length,mat:k.w.scene.materials.filter(m=>m.name.startsWith('field-remnant-')).length,tex:k.w.scene.textures.filter(m=>m.name.startsWith('field-remnant-')).length});
function hitAndKill(k,s){draw(k,s);advance(s,143);assert(core.action(s,0,'attack'));draw(k,s);const i=s.enemies.findIndex(e=>e.hp===18);assert(i>=0);advance(s,143);draw(k,s);assert(core.action(s,0,'attack'));const b=draw(k,s);return {i,b};}
for(const duration of [18,24])test('O tick envelope has exact neutral endpoints and bounded interior '+duration,()=>{for(const age of [-1,0,duration,duration+1,NaN,Infinity])assert.equal(bodyEnvelope(age,duration),0);for(let age=1;age<duration;age++)assert(bodyEnvelope(age,duration)>0&&bodyEnvelope(age,duration)<=1);near(bodyEnvelope(duration/2,duration),1);});
test('O runtime leaves core, M/N painters, input and held furniture untouched',()=>{const sha=p=>createHash('sha256').update(rescueSIfDeclared(p,readFileSync(p,'utf8'))).digest('hex');for(const [p,h] of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03o-unchanged-inputs.json'))))assert.equal(sha(p),h,p);});
for(const chapter of ['canyon','forest'])test('O actual source attack is directed and restores its exact anchor '+chapter,()=>{const k=rig();try{const s=battle(chapter);s.joined=true;/* Unit fixture: P2 is independently controlled, not auto-attacking. */draw(k,s);while(!s.effects.some(e=>e.enemyAction))advance(s,1);const action=structuredClone(s.effects.find(e=>e.enemyAction));draw(k,s);advance(s,6);let b=draw(k,s);const a=b.actors.find(a=>a.index===action.enemyAction.index),e=s.enemies[a.index],d=Math.hypot(action.x-e.x,action.z-e.z);near(a.offset.x,(action.x-e.x)/d*.2*Math.sin(Math.PI*6/24));near(a.offset.z,(action.z-e.z)/d*.2*Math.sin(Math.PI*6/24));const first=structuredClone(b);k.w.draw(s,45,false);assert.deepEqual(k.w.inspect().fieldEnemyBody,first,'same tick no accumulating transforms');advance(s,18);b=draw(k,s);assert(b.actors.every(a=>a.offset.x===0&&a.offset.z===0));assert.deepEqual(residue(k),{mesh:0,mat:0,tex:0});}finally{k.close();}});
test('O nonlethal recoil moves away from actual origin; no origin is never guessed',()=>{const k=rig();try{const s=battle();draw(k,s);advance(s,143);assert(core.action(s,0,'attack'));const eff=structuredClone(s.effects[0]);draw(k,s);advance(s,4);let b=draw(k,s),a=b.actors.find(a=>s.enemies[a.index].hp===18),distance=Math.hypot(eff.x-eff.origin.x,eff.z-eff.origin.z);near(a.offset.x,(eff.x-eff.origin.x)/distance*.1*Math.sin(Math.PI*4/18));near(a.offset.z,(eff.z-eff.origin.z)/distance*.1*Math.sin(Math.PI*4/18));advance(s,14);b=draw(k,s);assert(b.actors.every(a=>a.offset.x===0&&a.offset.z===0));k.w.draw(s,0,false,[{kind:'combo',x:s.enemies[0].x,z:s.enemies[0].z,text:'unit-only'}]);advance(s,4);b=draw(k,s);assert(b.actors.every(a=>a.offset.x===0&&a.offset.z===0));}finally{k.close();}});
test('O witnessed lethal hit hides original immediately and owns one static nearest-alpha remnant',()=>{const k=rig();try{const s=battle();const {i,b}=hitAndKill(k,s);assert.equal(s.enemies[i].hp,0);assert.equal(k.w.foes[i].mesh.isEnabled(),false);assert.equal(b.remnants.length,1);const r=b.remnants[0];assert.equal(r.originalEnabled,false);assert.equal(r.hpBefore,18);assert.equal(r.hpAfter,0);assert.equal(r.textureUploads,1);assert.deepEqual(r.cell,{width:24,height:32});assert.deepEqual(r.pixels.map(p=>p.rgba),[[224,209,122,255],[41,43,56,255],[48,45,64,255]]);assert.deepEqual(residue(k),{mesh:1,mat:1,tex:1});assert.equal(b.resources.rawTextureBytes,3072);
 let uploads=0;const orig=k.w.foes[i].texture.update.bind(k.w.foes[i].texture);k.w.foes[i].texture.update=(...a)=>{uploads++;return orig(...a);};const g=k.w.fieldEnemyBody.ghosts[i],foot=g.base.subtract(g.up.scale(g.height*g.scale.y/2));advance(s,12);const halfway=draw(k,s).remnants[0];near(halfway.alpha,.5);near(halfway.scale[1],1.3*.65);const actualFoot=g.mesh.position.subtract(g.up.scale(g.height*g.mesh.scaling.y/2));near(actualFoot.x,foot.x);near(actualFoot.y,foot.y);near(actualFoot.z,foot.z);advance(s,12);const end=draw(k,s);assert.equal(end.remnants.length,0);assert.equal(end.resources.created,end.resources.released);assert.equal(uploads,0);assert.deepEqual(residue(k),{mesh:0,mat:0,tex:0});assert(end.history.some(h=>h.kind==='death'&&h.phase==='expired'));}finally{k.close();}});
test('O last enemy defeat preserves original victory tick; ghosts are presentation only',()=>{const k=rig();try{const s=battle();s.enemies=s.enemies.slice(0,1);draw(k,s);advance(s,143);assert(core.action(s,0,'skill'));assert.equal(s.mode,'victory');const tick=s.ticks,b=draw(k,s);assert.equal(s.ticks,tick);assert.equal(s.mode,'victory');assert.equal(b.remnants.length,1);advance(s,24);assert.equal(draw(k,s).remnants.length,0);assert.equal(s.mode,'victory');}finally{k.close();}});
test('O real forest combo has bounded independent remnants without guessing an origin',()=>{const k=rig();try{const s=battle('forest');s.joined=true;draw(k,s);advance(s,143);core.requestCombo(s,0);core.requestCombo(s,1);assert.equal(s.mode,'victory');const b=draw(k,s);assert.equal(b.remnants.length,2);assert(b.history.every(h=>h.kind!=='death'||h.cause.origin===null));assert(b.resources.active<=3);advance(s,24);assert.deepEqual(residue(k),{mesh:2,mat:2,tex:2});draw(k,s);assert.deepEqual(residue(k),{mesh:0,mat:0,tex:0});}finally{k.close();}});
for(const mode of ['first-draw','rebase','enemy-array'])test('O zero-HP '+mode+' is not a witnessed death',()=>{const k=rig();try{let s=battle();if(mode!=='first-draw')draw(k,s);if(mode==='rebase')s=structuredClone(s);if(mode==='enemy-array')s.enemies=structuredClone(s.enemies);s.enemies[0].hp=0;s.effects.push({kind:'hit',actor:0,x:s.enemies[0].x,z:s.enemies[0].z,text:'unit-only',origin:{...s.players[0]}});const b=draw(k,s);assert.equal(b.remnants.length,0);assert.equal(b.resources.created,0);}finally{k.close();}});
test('O reduced motion zeroes offsets, hides live residue, restores same tick and never replays expired residue',()=>{const k=rig();try{const s=battle();const {b}=hitAndKill(k,s);const first=structuredClone(b.remnants[0]);k.media.matches=true;let x=draw(k,s);assert(x.actors.every(a=>a.offset.x===0&&a.offset.z===0));assert.equal(x.remnants[0].enabled,false);k.media.matches=false;x=draw(k,s);assert.deepEqual(x.remnants[0],first);k.media.matches=true;advance(s,24);x=draw(k,s);assert.equal(x.resources.active,0);k.media.matches=false;assert.equal(draw(k,s).resources.active,0);}finally{k.close();}});
test('O lethal event received while reduced does not warm-start a ghost later',()=>{const k=rig();try{const s=battle();k.media.matches=true;hitAndKill(k,s);assert.equal(k.w.inspect().fieldEnemyBody.resources.created,0);k.media.matches=false;assert.equal(draw(k,s).resources.active,0);}finally{k.close();}});
test('O hidden enemy never allocates residue and never updates dead original texture',()=>{const k=rig();try{const s=battle();draw(k,s);k.w.foes[1].mesh.isVisible=false;advance(s,143);draw(k,s);assert(core.action(s,0,'skill'));const b=draw(k,s);assert.equal(s.enemies[1].hp,0);assert.equal(b.resources.created,0);}finally{k.close();}});
for(const reset of ['rewind','rebase','chapter','dispose'])test('O '+reset+' releases owned resources and drops stale events',()=>{const k=rig();try{let s=battle();hitAndKill(k,s);const ctrl=k.w.fieldEnemyBody;assert.equal(ctrl.inspect().resources.active,1);if(reset==='rewind'){s.ticks=1;draw(k,s);}else if(reset==='rebase'){s=structuredClone(s);draw(k,s);}else if(reset==='chapter'){s.chapter='lab';draw(k,s);}else {ctrl.dispose();ctrl.dispose();}assert.equal(ctrl.inspect().resources.active,0);assert.equal(ctrl.inspect().history.length,0);assert.deepEqual(residue(k),{mesh:0,mat:0,tex:0});}finally{k.close();}});
test('O allocation failure is cleaned without undoing death or pretending a visual success',()=>{const k=rig();try{const s=battle();draw(k,s);advance(s,143);draw(k,s);const f=k.w.foes[1],get=f.texture.getContext.bind(f.texture);f.texture.getContext=()=>{throw Error('unit synthetic context loss');};assert(core.action(s,0,'skill'));let b;try{b=draw(k,s);}finally{f.texture.getContext=get;}assert.equal(s.enemies[1].hp,0);assert.equal(b.resources.creationFailures,1);assert.equal(b.resources.created,0);assert.equal(b.remnants.length,0);assert.deepEqual(residue(k),{mesh:0,mat:0,tex:0});}finally{k.close();}});
test('O invalid attacker metadata cannot displace actors',()=>{const k=rig();try{const s=battle();advance(s,2);draw(k,s);const valid={kind:'hit',text:'unit-only',x:0,z:5,enemyAction:{index:0,tick:2,origin:{x:-1.8,z:2.4},target:{x:0,z:5}}};for(const alter of [e=>e.enemyAction.index=3,e=>e.enemyAction.tick=-1,e=>e.enemyAction.tick=3,e=>e.enemyAction.origin.x=99,e=>e.enemyAction.target.z=99,e=>e.enemyAction.origin.x=NaN,e=>e.actor=0,e=>e.kind='heal',e=>delete e.enemyAction]){const e=structuredClone(valid);alter(e);k.w.draw(s,0,false,[e]);assert.equal(k.w.inspect().fieldEnemyBody.history.length,0);}advance(s,25);k.w.draw(s,0,false,[valid]);assert.equal(k.w.inspect().fieldEnemyBody.history.length,0);}finally{k.close();}});
test('O detached history stays bounded and source state/effects remain untouched',()=>{const k=rig();try{const s=battle();draw(k,s);const ctrl=k.w.fieldEnemyBody;for(let n=1;n<50;n++){s.ticks=n*30;const e={kind:'hit',actor:0,x:s.enemies[0].x,z:s.enemies[0].z,text:'unit-only',origin:{x:0,z:5}};k.w.draw(s,0,false,[e]);s.ticks+=9;draw(k,s);}const b=ctrl.inspect();assert.equal(b.history.length,24);assert(b.historyDropped>0);const old=structuredClone(b);b.history[0].cause.target.x=99;assert.deepEqual(ctrl.inspect(),old);}finally{k.close();}});
for(const chapter of ['lab','fair','truce'])test('O does not animate unrelated scene '+chapter,()=>{const k=rig();try{const s=core.createState(chapter);draw(k,s);advance(s,60);const b=draw(k,s);assert.equal(b.resources.created,0);assert.equal(b.actors.length,0);}finally{k.close();}});

for(const name of Object.keys(bodyOSpec.files))test('O exact source-only inverse with missing/duplicate/unrelated negatives: '+name,()=>{const sha=b=>createHash('sha256').update(b).digest('hex'),raw=partyPIfDeclared(name,readFileSync(name,'utf8')),old=bodyOBaseline(name,raw);assert.equal(sha(old),bodyOSpec.originalSha256[name]);assert.equal(bodyOIfDeclared(name,old),old);for(const h of bodyOSpec.files[name]){assert.throws(()=>bodyOBaseline(name,raw+h.after));assert.throws(()=>bodyOBaseline(name,raw.replace(h.after,'')));}assert.notEqual(sha(bodyOBaseline(name,raw+'\n// unrelated drift\n')),bodyOSpec.originalSha256[name]);});
test('O autonomous P2 recoil takes precedence over an overlapping forest enemy turn',()=>{const k=rig();try{const s=battle('forest');draw(k,s);while(!s.effects.some(e=>e.enemyAction))advance(s,1);const delivered=structuredClone(s.effects);assert(delivered.some(e=>e.actor===1));draw(k,s);advance(s,6);const b=draw(k,s);assert(b.history.some(h=>h.kind==='recoil'&&h.cause.effect.actor===1));assert(b.actors.some(a=>a.phase!=='rest'));}finally{k.close();}});
for(const [width,height]of [[192,128],[256,160],[240,180]])test(`O current CPU pixels match N outside transient action ${width}x${height}`,()=>{const current=rig(width,height),prior=rig(width,height,PriorWorld);try{const s=battle();s.joined=true;draw(current,s);draw(prior,structuredClone(s));assert.deepEqual(current.c.pixels(),prior.c.pixels(),'neutral battle exact N');while(!s.effects.some(e=>e.enemyAction))advance(s,1);const old=structuredClone(s);draw(current,s);draw(prior,old);advance(s,12);advance(old,12);draw(current,s);draw(prior,old);assert.notDeepEqual(current.c.pixels(),prior.c.pixels(),'delivered action is visible on actual CPU triangles');advance(s,12);advance(old,12);draw(current,s);draw(prior,old);assert.deepEqual(current.c.pixels(),prior.c.pixels(),'exact neutral restoration, no extra tolerance');assert.equal(current.w.inspect().fieldEnemyBody.resources.active,0);}finally{prior.close();current.close();}});
