import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {deflateSync} from 'node:zlib';
import {assertFieldEnemies,decodeCanvasPng,FIELD_PALETTE,paletteCounts} from '../scripts/field-enemy-evidence.mjs';
import {surface,png} from '../scripts/asset-export.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
function fixture(chapter='canyon'){
 const image=surface(120,80);image.ink.fillStyle='#71895f';image.ink.fillRect(0,0,120,80);const ids=Array.from({length:chapter==='canyon'?3:2},(_,i)=>'enemy-'+i);
 const rects=ids.map((id,i)=>({id,left:i*.3,right:i*.3+.2,top:.2,bottom:.8}));
 for(const [i,r]of rects.entries())for(let j=0;j<4;j++){image.ink.fillStyle='#'+FIELD_PALETTE[j].slice(0,3).map(n=>n.toString(16).padStart(2,'0')).join('');image.ink.fillRect(i*36+4,20+j*5,12,4);}
 const bytes=png(image),samples=[[0,0,[0,0,0,0]],[6,13,FIELD_PALETTE[0]],[8,15,FIELD_PALETTE[1]],[9,16,FIELD_PALETTE[2]],[6,29,FIELD_PALETTE[3]]].map(([x,y,rgba])=>({x,y,rgba}));
 const o={profile:'vq03c-native-field-enemies',state:{chapter,mode:'explore',ticks:32,opening:{canyonWon:false},kingdom:{forestWon:false}},art:{profile:'vq03c-field-enemy-palette',chapter,tick:32,active:true,approved:false,actors:ids.map((name,i)=>({name,texture:name+'-pixels',cell:{width:24,height:32},sampling:1,alpha:true,alphaTest:true,disableLighting:true,emissiveMatchesDiffuse:true,emissionOnly:true,linked:false,emissive:[0,0,0],ambient:[0,0,0],specular:[0,0,0],samples,scale:[1,1.3,1],position:[i,1,3]})),rects},renderer:{backend:'cpu-canvas2d',webglVersion:0,canvas2dFallback:true,width:120,height:80},canvas:{source:'actual-cpu-canvas',width:120,height:80,palette:FIELD_PALETTE,counts:paletteCounts(image.rgba,120,80,rects)},canvasImage:{path:'field-'+chapter+'-canvas.png',bytes:bytes.length,sha256:hash(bytes)},physicalDevice:false,artApproved:false};
 return {o,bytes};
}
for(const chapter of ['canyon','forest'])test('C structural '+chapter+' PNG fixture accepted only as unit verifier input',()=>{const {o,bytes}=fixture(chapter);assert(assertFieldEnemies(o,chapter,bytes));});
for(const [name,mutate]of [
 ['different tick',o=>o.art.tick++],['wrong chapter',o=>o.state.chapter='fair'],['cleared battle',o=>o.state.opening.canyonWon=true],['legacy lighting',o=>o.art.actors[0].disableLighting=false],['gray emission',o=>o.art.actors[0].emissive=[.52,.52,.52]],['squared palette',o=>o.art.actors[0].emissionOnly=false],['lighting linked',o=>o.art.actors[0].linked=true],['missing enemy',o=>o.art.actors.pop()],['duplicate enemy',o=>o.art.actors[1].name=o.art.actors[0].name],['unknown owner',o=>o.art.rects[0].id='guest'],['wrong texture',o=>o.art.actors[0].texture='other'],['smooth cutout',o=>o.art.actors[0].sampling=2],['no alpha',o=>o.art.actors[0].alpha=false],['wrong original pixel',o=>o.art.actors[0].samples[1].rgba=[255,255,255,255]],['wrong cell',o=>o.art.actors[0].cell.width=48],['human scale changed',o=>o.art.actors[0].scale=[1,2,1]],['wrong canvas size',o=>o.canvas.width=100],['count invented',o=>o.canvas.counts[0].values[0]++],['wrong file',o=>o.canvasImage.path='other.png'],['wrong hash',o=>o.canvasImage.sha256='0'.repeat(64)],['false native approval',o=>o.physicalDevice=true],['nonfinite projection',o=>o.art.rects[0].left=NaN]])test('C rejects '+name,()=>{const {o,bytes}=fixture();mutate(o);assert.throws(()=>assertFieldEnemies(o,'canyon',bytes));});
test('C rejects saturated pixels even when both raw PNG receipt and reported counts agree',()=>{const {o}=fixture(),s=surface(120,80);s.ink.fillStyle='#ffffff';s.ink.fillRect(0,0,120,80);const bytes=png(s);o.canvasImage.bytes=bytes.length;o.canvasImage.sha256=hash(bytes);o.canvas.counts=paletteCounts(s.rgba,120,80,o.art.rects);assert.throws(()=>assertFieldEnemies(o,'canyon',bytes),/washed out/);});
test('C PNG decoder checks CRC, truncated data, terminal chunk and decompression bounds',()=>{const {bytes}=fixture();assert.equal(decodeCanvasPng(bytes).rgba.length,120*80*4);for(const broken of [bytes.subarray(0,20),bytes.subarray(0,bytes.length-1),Buffer.concat([bytes,Buffer.from([0])])])assert.throws(()=>decodeCanvasPng(broken));const wrong=Buffer.from(bytes);wrong[50]^=1;assert.throws(()=>decodeCanvasPng(wrong));assert.throws(()=>decodeCanvasPng(Buffer.alloc(4*1024*1024+1)));});
test('C existing era inspector requires both additional original PNGs without replacing old reports',()=>{const s=readFileSync('scripts/cpu-era-evidence.mjs','utf8');assert(s.includes("for(const c of ['canyon','forest'])"));assert(s.includes('assertFieldEnemies(o,c,b)'));assert(s.includes('assertTownRoute(r.townReadability'));assert(s.includes('assertTownMotion(parentReport.nativeVideo'));assert(s.includes("for(const v of r.townReadability.stops)"));assert(s.includes('const parentReport=JSON.parse'));});
// Exercise every legal Canvas filter, RGB and RGBA. Encoded bytes are test fixtures only.
const ctable=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function chunk(type,body){const a=Buffer.concat([Buffer.from(type),body]),out=Buffer.alloc(body.length+12);out.writeUInt32BE(body.length);a.copy(out,4);let c=0xffffffff;for(const b of a)c=ctable[(c^b)&255]^(c>>>8);out.writeUInt32BE((c^0xffffffff)>>>0,out.length-4);return out;}
function filteredPng(channels,filter){const width=7,height=5,stride=width*channels,raw=Buffer.alloc(stride*height);for(let i=0;i<raw.length;i++)raw[i]=(i*37+i%9*11)&255;const scan=Buffer.alloc((stride+1)*height);const paeth=(a,b,c)=>{const p=a+b-c,da=Math.abs(p-a),db=Math.abs(p-b),dc=Math.abs(p-c);return da<=db&&da<=dc?a:db<=dc?b:c;};for(let y=0;y<height;y++){scan[y*(stride+1)]=filter;for(let x=0;x<stride;x++){const n=y*stride+x,a=x>=channels?raw[n-channels]:0,b=y?raw[n-stride]:0,c=y&&x>=channels?raw[n-stride-channels]:0;scan[y*(stride+1)+1+x]=(raw[n]-[0,a,b,Math.floor((a+b)/2),paeth(a,b,c)][filter])&255;}}const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=channels===4?6:2;const bytes=Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(scan)),chunk('IEND',Buffer.alloc(0))]);const expected=Buffer.alloc(width*height*4);for(let i=0;i<width*height;i++){raw.copy(expected,i*4,i*channels,i*channels+3);expected[i*4+3]=channels===4?raw[i*channels+3]:255;}return {bytes,expected};}
for(const channels of [3,4])for(const filter of [0,1,2,3,4])test('C independently decodes '+channels+' channels with PNG filter '+filter,()=>{const {bytes,expected}=filteredPng(channels,filter);assert.deepEqual(decodeCanvasPng(bytes).rgba,expected);});
