import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {NullEngine,Scene,StandardMaterial,Texture,Material,Color3} from '@babylonjs/core';
import {PixelPalettePass} from '../.test/pixel-presentation.mjs';
import {PosePlayer} from '../.test/pose-player.mjs';import {ambientFrame,readyFrame} from '../.test/actor-motion.mjs';
import {drawHDHero,HD_HERO_IDS,HD_ART} from '../.test/hd-hero-art.mjs';import {drawWitness,WITNESS_KINDS} from '../.test/witness-art.mjs';
import {surface,png} from '../scripts/asset-export.mjs';import {hdSheet} from '../scripts/hd-asset-export.mjs';import {CLIP_MS} from '../.test/hero-art.mjs';
test('idle breathing and ready stance are real timed frame changes; pause freezes time',()=>{const p=new PosePlayer();assert.equal(p.sample(0,false).frame,0);assert.equal(p.sample(1.6,false).frame,1);assert.equal(p.sample(3.02,false).frame,2);assert.equal(p.sample(3.2,false).frame,3);assert.equal(p.sample(1,false,true).pose,'ready');const frozen=p.sample(1.4,false,true);for(let i=0;i<10;i++)assert.deepEqual(p.sample(1.4,false,true),frozen);p.trigger('hurt',2);assert.equal(p.sample(2,false,true).pose,'hurt');assert.equal(p.sample(3,false,true).pose,'ready');});
for(const hero of HD_HERO_IDS)test(`${hero}: four distinct idle/ready frames have stable feet and selective dark outline`,()=>{for(const pose of ['idle','ready']){const imgs=[];for(let n=0;n<4;n++){const s=surface(48,64);drawHDHero(s.ink,hero,0,n,pose);imgs.push(s);assert(s.rgba.filter((v,i)=>i%4===3).some(v=>v===0));}assert.equal(new Set(imgs.map(s=>png(s).toString('hex'))).size,4);if(pose==='idle')for(const s of imgs.slice(1))assert.deepEqual(s.rgba.subarray(58*48*4),imgs[0].rgba.subarray(58*48*4));}assert.equal(HD_ART.approved,false);});
for(const kind of WITNESS_KINDS)test(`${kind}: four ambient NPC poses have stable foot contact, no static-only replacement`,()=>{const imgs=[];for(let f=0;f<4;f++){const s=surface(48,64);drawWitness(s.ink,kind,f);imgs.push(s);}assert.equal(new Set(imgs.map(s=>png(s).toString('hex'))).size,4);for(const s of imgs.slice(1))assert.deepEqual(s.rgba.subarray(58*48*4),imgs[0].rgba.subarray(58*48*4));});
test('export clips carry same actual idle and ready timing as runtime',()=>{const {frames,clips}=hdSheet((c,d,f,p)=>drawHDHero(c,'crono',d,f,p),HD_ART,CLIP_MS);const idle=clips['idle.down'].frames.map(i=>frames[i]);assert.deepEqual(idle.map(f=>f.durationMs),[1500,1500,150,850]);for(const [ticks,frame] of [[0,0],[89,0],[90,1],[180,2],[189,3],[240,0]])assert.equal(ambientFrame(ticks),frame);assert.equal(readyFrame(18),1);assert(clips['ready.down'].loop);assert.equal(clips['ready.down'].frames.length,4);});
test('unlit alpha actor uses one authored palette contribution and excludes unrelated materials',()=>{const e=new NullEngine(),s=new Scene(e),t=new Texture(null,s),m=new StandardMaterial('actor',s);m.diffuseTexture=m.emissiveTexture=t;m.disableLighting=true;m.transparencyMode=Material.MATERIAL_ALPHATEST;m.emissiveColor=new Color3(.52,.52,.52);const label=new StandardMaterial('label',s),lit=new StandardMaterial('wall',s);label.disableLighting=true;const pass=new PixelPalettePass();pass.apply(s);assert(m.useEmissiveAsIllumination);assert.deepEqual(m.emissiveColor.asArray(),[0,0,0]);assert(!label.useEmissiveAsIllumination);assert(!lit.useEmissiveAsIllumination);assert.equal(pass.count,1);pass.apply(s);assert.equal(pass.count,1);s.dispose();e.dispose();});
test('production connects animation to actual visible NPCs and preserves state/collision boundaries',()=>{for(const file of ['fair-conduct-render','trial-render'])assert.match(readFileSync('src/'+file+'.ts','utf8'),/motion.draw\(s.ticks\)/);const s=readFileSync('src/render.ts','utf8');assert.match(s,/palettePass.apply\(this.scene\)/);assert.match(s,/groundActor/);assert.match(s,/sample\(s.ticks,p.walking,s.mode==='battle',/);assert.doesNotMatch(readFileSync('src/npc-motion.ts','utf8'),/Object.assign\(s|\.hp\s*=|\.position\.set/);});

test('palette normalization repairs reused actor material without recounting it',()=>{const e=new NullEngine(),s=new Scene(e),t=new Texture(null,s),m=new StandardMaterial('reused-actor',s);m.diffuseTexture=m.emissiveTexture=t;m.disableLighting=true;m.transparencyMode=Material.MATERIAL_ALPHATEST;const pass=new PixelPalettePass();pass.apply(s);m.useEmissiveAsIllumination=false;m.linkEmissiveWithDiffuse=true;m.emissiveColor.set(.3,.3,.3);m.ambientColor.set(.2,.1,.4);pass.apply(s);assert(m.useEmissiveAsIllumination);assert(!m.linkEmissiveWithDiffuse);assert.deepEqual(m.emissiveColor.asArray(),[0,0,0]);assert.deepEqual(m.ambientColor.asArray(),[0,0,0]);assert.equal(pass.count,1);s.dispose();e.dispose();});
test('palette pass ignores lit scenery, alpha-blended effects and different-texture materials',()=>{const e=new NullEngine(),s=new Scene(e),a=new Texture(null,s),b=new Texture(null,s),pass=new PixelPalettePass();for(const kind of ['lit','effect','other-image']){const m=new StandardMaterial(kind,s);m.diffuseTexture=a;m.emissiveTexture=kind==='other-image'?b:a;m.disableLighting=kind!=='lit';m.transparencyMode=kind==='effect'?Material.MATERIAL_ALPHABLEND:Material.MATERIAL_ALPHATEST;}pass.apply(s);assert.equal(pass.count,0);assert(s.materials.filter(m=>m instanceof StandardMaterial).every(m=>!m.useEmissiveAsIllumination));s.dispose();e.dispose();});
