import {artHIfDeclared,artHFrozenBytes,artHIsNew} from './helpers/architecture-h-baseline.mjs';
/** G -> F SOURCE-only contract; never applied to native reports, pixels or game State. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {createHash} from 'node:crypto';import {artGSpec,artGBaseline,artGIfDeclared} from './helpers/npc-attention-g-baseline.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
for(const [name,e]of Object.entries(artGSpec.files))test('G source predecessor and drift rejection '+name,()=>{const raw=artHIfDeclared(name,readFileSync(name,'utf8')),old=artGBaseline(name,raw);assert.equal(sha(old),e.sha256);assert.equal(artGIfDeclared(name,old),old);assert.equal(artGIfDeclared(name,raw+'\n// drift\n'),old+'\n// drift\n');for(const h of e.hunks)for(const bad of [raw.replace(h.after,''),raw+h.after,raw+'\n// drift\n'])assert.throws(()=>artGBaseline(name,bad));});
test('G all undeclared F program inputs, original native routes/assertions/goldens and held prologue remain byte exact',()=>{const pin=JSON.parse(readFileSync('tests/baselines/vq04g-unchanged-inputs.json')),names=[...pin.rootFiles];function walk(d){for(const e of readdirSync(d,{withFileTypes:true})){if(e.name==='__pycache__'||e.name.endsWith('.pyc'))continue;assert(!e.isSymbolicLink());const n=d+'/'+e.name;if(e.isDirectory())walk(n);else if(e.isFile())names.push(n);}}for(const d of pin.roots)walk(d);const rows=names.sort().filter(n=>!pin.exclude.includes(n)&&!artHIsNew(n)).map(n=>[n,sha(artHFrozenBytes(n,readFileSync(n)))]);assert.equal(rows.length,pin.expectedCount);assert.equal(sha(JSON.stringify(rows)),pin.sha256);for(const n of ['src/core.ts','src/render.ts','src/prologue-render.ts','src/story-npc-motion.ts','src/production-story-npc-art.ts','src/production-combat-art.ts','tests/party_combat.py','tests/trial_browser.py','tests/npc_comfort_capture.py','tests/baselines/vq04f-declared-art-edits.json','tests/baselines/vq04f-unchanged-inputs.json','.github/workflows/ci.yml'])assert(rows.some(([p])=>p===n),n);const b=readFileSync('src/prologue-render.ts');assert.equal(createHash('sha1').update(Buffer.concat([Buffer.from('blob '+b.length+'\0'),b])).digest('hex'),'2711a74185aacf3c6bddf9db85ba99a2afbc507a');});
test('G source inverse rejects undeclared native/image/State/golden inputs',()=>{for(const n of ['native.json','image.png','src/core.ts','src/render.ts','src/production-story-npc-art.ts','tests/party_combat.py','tests/fixtures/party-combat-frames.json','__proto__','constructor'])assert.throws(()=>artGBaseline(n,'{}'));});
test('G current composition activates real attention with no device bypass; original author cells and combat hold retained',()=>{const entry=artHIfDeclared('src/art-directed-world.ts',readFileSync('src/art-directed-world.ts','utf8')),b=artHIfDeclared('scripts/build.mjs',readFileSync('scripts/build.mjs','utf8')),s=readFileSync('src/production-npc-attention.ts','utf8');assert(entry.includes('this.npcAttention.begin(state)'));assert(entry.includes('this.npcAttention.select(name,x,z)'));assert(entry.includes('super.draw(state,dt,animate,frameEffects)'));assert(!/navigator|location|readPixels/.test(entry));assert(b.includes("version:'0.9.80',batch:'VQ04G'"));assert(artGBaseline('scripts/build.mjs',b).includes("version:'0.9.79',batch:'VQ04F'"));assert(!/fetch\(|setTimeout|setInterval|Date\.|performance\.|localStorage|\.ticks\s*[+]=|\.hp\s*=/.test(s));assert(readFileSync('src/production-combat-art.ts','utf8').includes('runtimeApplied:false'));});
test('G asset register extends all F entries without marking any approved',()=>{const raw=artHIfDeclared('assets/manifest.json',readFileSync('assets/manifest.json','utf8')),m=JSON.parse(raw),f=JSON.parse(artGBaseline('assets/manifest.json',raw));assert.deepEqual(m.items.slice(0,f.items.length),f.items);const g=m.items.find(a=>a.id==='story-npc-attention-vq04g');assert(g.required);assert.equal(g.stage,'review');assert(g.evidence.length>0);});
