import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {assertNpcComfort} from '../scripts/npc-comfort-evidence.mjs';import {surface,png} from '../scripts/asset-export.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
function fixture(){
 const s=surface(120,80);s.ink.fillStyle='#52795f';s.ink.fillRect(0,0,120,80);s.ink.fillStyle='#e2d496';s.ink.fillRect(10,10,20,20);const bytes=png(s);
 const state={chapter:'truce',ticks:140,mode:'explore',players:[{x:0,z:0}]};
 const phases=['before','reduced','restored'].map((phase,i)=>{
  const reduced=i===1,observation={chapter:'truce',paused:true,mediaReduce:reduced,npc:{profile:'vq02q-story-npc-cloth-and-silhouette',approved:false,motion:{profile:'vq03e-npc-motion-preference',clock:'simulation-ticks',tick:140,reducedMotion:reduced,bindingCount:2,stateMutation:false},actors:[['townsperson','resident'],['innkeeper','innkeeper']].map(([name,kind],seed)=>({name,kind,seed,frame:reduced?0:1,uploads:1+i,cell:{width:48,height:64}}))},renderer:{backend:'cpu-canvas2d',webglVersion:0,width:120,height:80,samplingEnabled:true},viewport:{width:960,height:640},focus:'resume'};
  return {phase,state:structuredClone(state),observation,repeated:structuredClone(observation),image:{path:'npc-comfort/'+phase+'.png',source:'actual-cpu-canvas',bytes:bytes.length,sha256:sha(bytes)}};
 });
 return {r:{schema:'chrono-native-npc-comfort-v1',status:'passed',physicalDevice:false,artApproved:false,realTimeComfortApproved:false,originalReduce:false,beforeState:state,afterState:structuredClone(state),fullStateEqual:true,phases},bytes};
}
test('structural PNG fixtures exercise the extra verifier only, not native certification',()=>{const {r,bytes}=fixture();assert.equal(assertNpcComfort(r,()=>bytes).length,3);});
const changes={missing:r=>r.phases.pop(),reordered:r=>r.phases.reverse(),notCompleted:r=>r.status='running',approval:r=>r.realTimeComfortApproved=true,changedState:r=>r.afterState.ticks++,fakeChapter:r=>r.beforeState.chapter='fair',notPaused:r=>r.phases[1].observation.paused=false,preferenceIgnored:r=>r.phases[1].observation.npc.motion.reducedMotion=false,wrongClock:r=>r.phases[1].observation.npc.motion.clock='wall-time',wrongTick:r=>r.phases[1].observation.npc.motion.tick++,wrongFrame:r=>r.phases[1].observation.npc.actors[0].frame=1,wrongCell:r=>r.phases[1].observation.npc.actors[0].cell.width=24,wrongRole:r=>r.phases[0].observation.npc.actors[0].kind='queen',duplicateSeed:r=>r.phases[0].observation.npc.actors[1].seed=0,missingNpc:r=>r.phases[0].observation.npc.actors.pop(),leak:r=>r.phases[0].observation.npc.motion.bindingCount=20,negativeUploads:r=>r.phases[0].observation.npc.actors[0].uploads=-1,repeatedUploads:r=>r.phases[1].repeated.npc.actors[0].uploads++,doubleUpload:r=>{r.phases[1].observation.npc.actors[0].uploads++;r.phases[1].repeated=structuredClone(r.phases[1].observation);},wrongBackend:r=>r.phases[0].observation.renderer.backend='webgl',lowerQuality:r=>r.phases[0].observation.renderer.samplingEnabled=false,changedFocus:r=>r.phases[2].observation.focus='other',wrongPath:r=>r.phases[1].image.path='../before.png',wrongHash:r=>r.phases[1].image.sha256='0'.repeat(64),wrongBytes:r=>r.phases[1].image.bytes++,wrongDimensions:r=>r.phases[1].observation.renderer.width++,canvasInvented:r=>r.phases[1].image.source='fixture'};
for(const [name,change] of Object.entries(changes))test('NPC extra verifier rejects '+name,()=>{const {r,bytes}=fixture();change(r);assert.throws(()=>assertNpcComfort(r,()=>bytes));});
test('decode failure cannot be hidden behind matching PNG receipt',()=>{const {r,bytes}=fixture(),bad=Buffer.from(bytes);bad[40]^=1;r.phases.forEach(p=>p.image.sha256=sha(bad));assert.throws(()=>assertNpcComfort(r,()=>bad));});
test('blank native image is rejected even when metadata and hashes match',()=>{const {r}=fixture(),s=surface(120,80);s.ink.fillStyle='#ffffff';s.ink.fillRect(0,0,120,80);const b=png(s);r.phases.forEach(p=>Object.assign(p.image,{bytes:b.length,sha256:sha(b)}));assert.throws(()=>assertNpcComfort(r,()=>b),/nonblank/);});
test('restored image must be the exact original bytes',()=>{const {r,bytes}=fixture(),s=surface(120,80);s.ink.fillStyle='#547a60';s.ink.fillRect(0,0,120,80);s.ink.fillStyle='#ffff00';s.ink.fillRect(10,10,20,20);const changed=png(s);Object.assign(r.phases[2].image,{bytes:changed.length,sha256:sha(changed)});assert.throws(()=>assertNpcComfort(r,p=>p.endsWith('restored.png')?changed:bytes),/restored exact/);});
