import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {selectPagesRun} from '../scripts/pages-select.mjs';
const good={id:36441789439,status:'completed',conclusion:'success',head_branch:'main',path:'.github/workflows/ci.yml',head_repository:{id:1374143773},event:'push',head_sha:'da615f1e4a803fa8fdaddf4723ab782038e14266',run_attempt:1};
function rig(overrides={}) {const calls=[];return {calls,args:{owner:'KartChang',repo:'ChronoTrigger_reMaster',repositoryId:1374143773,eventName:'workflow_run',trigger:{...good},actions:{async getWorkflowRun(q){calls.push(['get',q]);return {data:{...good,...overrides}};},async listWorkflowRuns(q){calls.push(['list',q]);return {data:{workflow_runs:[]}};}}}};}
test('Pages workflow_run uses exact GET even when the success listing is empty',async()=>{const r=rig();assert.deepEqual(await selectPagesRun(r.args),good);assert.deepEqual(r.calls,[['get',{owner:'KartChang',repo:'ChronoTrigger_reMaster',run_id:good.id}]]);});
for(const bad of [{status:'in_progress'},{conclusion:'failure'},{head_branch:'other'},{event:'pull_request'},{head_repository:{id:2}},{path:'.github/workflows/other.yml'},{head_sha:'a'.repeat(40)},{id:1},{run_attempt:2}])test('Pages refuses exact-trigger drift without falling back: '+JSON.stringify(bad),async()=>{const r=rig(bad);await assert.rejects(selectPagesRun(r.args));assert.equal(r.calls.length,1);});
for(const trigger of [null,{}, {id:0,head_sha:good.head_sha},{id:good.id,head_sha:'bad'}])test('Pages malformed trigger is rejected before any network call '+JSON.stringify(trigger),async()=>{const r=rig();r.args.trigger=trigger;await assert.rejects(selectPagesRun(r.args));assert.equal(r.calls.length,0);});
test('Pages exact GET transport error is preserved, never converted to another source',async()=>{const r=rig(),error=new Error('transport');r.args.actions.getWorkflowRun=async()=>{throw error;};await assert.rejects(selectPagesRun(r.args),e=>e===error);assert.equal(r.calls.length,0);});
test('Explicit dispatch retains strict manual selection and no invalid run',async()=>{const r=rig();r.args.eventName='workflow_dispatch';r.args.actions.listWorkflowRuns=async()=>({data:{workflow_runs:[{...good,conclusion:'failure'},good]}});assert.deepEqual(await selectPagesRun(r.args),good);});
test('Unsupported event cannot deploy a previously successful source',async()=>{const r=rig();r.args.eventName='push';await assert.rejects(selectPagesRun(r.args));assert.equal(r.calls.length,0);});
test('Manual empty listing fails closed',async()=>{const r=rig();r.args.eventName='workflow_dispatch';await assert.rejects(selectPagesRun(r.args),/No successful/);assert.equal(r.calls.length,1);});
test('Workflow wires exact trigger helper, tests it, and only deploys after CI or explicit dispatch',()=>{const s=readFileSync('.github/workflows/pages.yml','utf8');assert(!/^  push:/m.test(s));assert(s.includes('trigger:context.payload.workflow_run'));assert(s.includes('actions:github.rest.actions'));assert(s.includes('tests/pages-select.test.mjs'));assert(s.includes('artifact.workflow_run?.head_sha!==selected.head_sha'));assert(s.includes("matches.length!==1"));assert(s.includes('persist-credentials: false'));assert(!s.includes('listWorkflowRuns'));});
