/** P unit/offline fixtures only. These are not native input or physical-device evidence. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import * as core from '../.test/core.mjs';import {PartyCombatMotion,PARTY_COMBAT,actionFacing,fallenFrame,rgbaFingerprint} from '../.test/party-combat-motion.mjs';
import {drawHDHero,HD_HERO_IDS} from '../.test/hd-hero-art.mjs';import {CLIP_MS} from '../.test/hero-art.mjs';import {ActorTimeline} from '../.test/actor-timeline.mjs';
import {World} from '../.test/cpu-entry.mjs';import {World as PriorWorld} from '../.test/party-p-prior-world.mjs';import {cpuTestCanvas} from './cpu-test-canvas.mjs';import {surface} from '../scripts/asset-export.mjs';
import {partyPSpec,partyPBaseline,partyPIfDeclared} from './helpers/party-p-baseline.mjs';
import {reactionQIfDeclared} from './helpers/reaction-q-baseline.mjs';
const frame=(hero,dir,f,pose)=>{const p=surface(48,64);drawHDHero(p.ink,hero,dir,f,pose);return p.rgba;};
const sha=b=>createHash('sha256').update(b).digest('hex');
const battle=(chapter='forest')=>{const s=core.createState(chapter);if(chapter==='canyon')s.opening.phase='canyon';s.joined=true;assert(core.beginBattle(s));return s;};
const advance=(s,n)=>{for(let i=0;i<n;i++)core.step(s,core.IDLE,1/60);};
const actor=(s,slot)=>slot===2?s.rescue.guest:s.players[slot];
function fixture(slot=0,guest='frog'){const s=battle();if(slot===2)s.rescue.stage=guest==='frog'?'allied':'reunited';const c=new PartyCombatMotion();c.begin(s,false);return{s,c,p:actor(s,slot)};}
function effect(s,slot=0,dir=1,style='slash'){const p=actor(s,slot),d=[{x:0,z:-2},{x:2,z:0},{x:0,z:2},{x:-2,z:0}][dir];return{kind:'hit',...(slot===2?{guest:true}:{actor:slot}),origin:{x:p.x,z:p.z},x:p.x+d.x,z:p.z+d.z,text:'fixture',style};}
const sample=(c,slot=0,pose='attack',f=0,dir=0)=>c.sample(slot,{pose,frame:f},dir);
function rig(width=128,height=96,W=World){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;const c=cpuTestCanvas(width,height);c.canvas.ownerDocument=doc;const w=new W(c.canvas);return{w,c,media,close(){w.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};}
function draw(k,s){const effects=s.effects.splice(0),before=structuredClone(s),eb=structuredClone(effects);k.w.draw(s,0,false,effects);assert.deepEqual(s,before);assert.deepEqual(effects,eb);return k.w.inspect().partyCombat;}
function texture(k,slot){const t=slot===2?k.w.guest.texture:k.w.heroes[slot].texture;return Buffer.from(t.getContext().getImageData(0,0,48,64).data);}
for(const [dir,target]of [[0,{x:0,z:-2}],[1,{x:2,z:0}],[2,{x:0,z:2}],[3,{x:-2,z:0}]])test('P exact cardinal source direction '+dir,()=>assert.equal(actionFacing({x:0,z:0},target),dir));
test('P direction tie follows existing Z convention; zero/nonfinite sources rejected',()=>{assert.equal(actionFacing({x:0,z:0},{x:1,z:1}),2);for(const v of [null,{x:0,z:0},{x:NaN,z:1},{x:1,z:Infinity}])assert.equal(actionFacing({x:0,z:0},v),null);});
for(const slot of [0,1,2])for(const style of ['slash','fire'])test(`P explicit slot${slot}/${style} locks source through retained clip and then releases`,()=>{const{s,c}=fixture(slot),e=effect(s,slot,3,style),before=structuredClone(s);c.receive(s,e);const pose=style==='fire'?'cast':'attack',end=CLIP_MS[pose].reduce((a,b)=>a+b,0)*60/1000;assert.equal(sample(c,slot,pose,0,1).facing,3);s.ticks=Math.ceil(end)-1;c.begin(s,false);assert.equal(sample(c,slot,pose,3,1).facing,3);s.ticks=Math.ceil(end);c.begin(s,false);assert.equal(sample(c,slot,pose,0,1).facing,1);before.ticks=s.ticks;assert.deepEqual(s,before);assert.equal(c.inspect().additionalGpuResources,0);});
test('P explicit guest healing is a sourced cast; actor heal and unowned combo never infer a direction',()=>{const{s,c}=fixture(2);const e={...effect(s,2,1),kind:'heal'};c.receive(s,e);assert.equal(sample(c,2,'cast',0,3).facing,1);for(const event of [{...e,actor:0,guest:undefined},{...e,guest:undefined,kind:'combo'}]){c.reset();c.begin(s,false);c.receive(s,event);assert.equal(sample(c,0,'cast',0,3).facing,3);assert.equal(c.inspect().history.length,0);}});
for(const invalid of ['no-origin','enemy','ambiguous','bad-owner','bad-origin','dead','inactive'])test('P rejects nonsourced '+invalid+' action',()=>{const{s,c,p}=fixture();let e=effect(s);if(invalid==='no-origin')delete e.origin;if(invalid==='enemy')e.enemyAction={index:0,tick:0,origin:e.origin,target:{x:e.x,z:e.z}};if(invalid==='ambiguous')e.guest=true;if(invalid==='bad-owner')e.actor=5;if(invalid==='bad-origin')e.origin.x+=1;if(invalid==='dead')p.hp=0;if(invalid==='inactive'){s.opening.phase='canyon';e=effect(s,1);}c.begin(s,false);c.receive(s,e);assert.equal(c.inspect().history.length,0);sample(c,invalid==='inactive'?1:0);assert.equal(c.inspect().history.length,0);});
test('P actual interruption discards the prior outgoing lock rather than turning later hurt into attack',()=>{const{s,c}=fixture();c.receive(s,effect(s,0,1));sample(c);sample(c,0,'hurt');assert.equal(sample(c,0,'attack',1,3).facing,3);});
for(const slot of [0,1,2])test('P observed living->zero sequences all retained down frames and holds final slot'+slot,()=>{const{s,c,p}=fixture(slot);sample(c,slot,'ready',0,3);s.ticks=10;p.hp=0;c.begin(s,false);for(const [age,f]of [[0,0],[7,0],[8,1],[14,1],[15,2],[22,2],[23,3],[200,3]]){s.ticks=10+age;c.begin(s,false);assert.deepEqual(sample(c,slot,'ready',0,1),{pose:'down',frame:f,facing:3});}assert.deepEqual([...new Set(c.inspect().history.map(h=>h.frame))],[0,1,2,3]);p.hp=10;s.ticks++;c.begin(s,false);assert.equal(sample(c,slot,'ready',0,1).pose,'ready');});
for(const reset of ['first-dead','same-tick','new-state','new-actor','rewind','defeat','lab'])test('P '+reset+' does not manufacture a fall',()=>{let{s,c,p}=fixture();if(reset==='first-dead')c.reset();if(reset==='new-state')s=structuredClone(s);if(reset==='new-actor')s.players[0]=structuredClone(p);if(reset==='rewind'){s.ticks=20;c.begin(s,false);s.ticks=0;}else if(reset!=='same-tick')s.ticks=1;s.players[0].hp=0;if(reset==='defeat')s.mode='defeat';if(reset==='lab')s.chapter='lab';c.begin(s,false);assert.equal(sample(c,0,'down',3).frame,3);assert.equal(c.inspect().history.length,0);});
test('P same tick and reduced preference retain essential combat phase without wall-clock advancement',()=>{const{s,c,p}=fixture();s.ticks=1;p.hp=0;c.begin(s,false);sample(c,0,'down');const before=structuredClone(s);for(let i=0;i<50;i++){c.begin(s,false);sample(c,0,'down');}assert.equal(c.inspect().history.length,1);c.begin(s,true);assert.equal(sample(c,0,'down').frame,0);c.begin(s,false);assert.equal(sample(c,0,'down').frame,0);assert.deepEqual(s,before);});
test('P bounded history is detached and reads exactly one existing texture per new draw pose',()=>{const{s,c}=fixture();let reads=0;for(let i=0;i<40;i++){s.ticks=i*40;c.begin(s,false);c.receive(s,effect(s,0,i%4));sample(c);c.recordDraw(0,()=>{reads++;return{width:48,height:64,data:frame('crono',i%4,0,'attack')};});c.recordDraw(0,()=>{throw Error('must not reread');});}const h=c.inspect();assert.equal(reads,40);assert.equal(h.history.length,24);assert.equal(h.historyDropped,16);h.history[0].cause.origin.x=999;assert.notEqual(c.inspect().history[0].cause.origin.x,999);assert(h.history.every(x=>x.texture&&x.scope==='draw-texture-not-framebuffer'));});
test('P diagnostic read failures are explicit, never synthetic texture or gameplay failure',()=>{const{s,c}=fixture();c.receive(s,effect(s));sample(c);c.recordDraw(0,()=>{throw Error('tainted fixture');});assert.equal(c.inspect().textureReadFailures,1);assert.equal(c.inspect().history[0].texture,null);c.dispose();c.begin(s,false);c.receive(s,effect(s));assert.equal(c.inspect().history.length,0);assert.equal(c.inspect().disposed,true);});
test('P inactive slots and guest identity changes cannot inherit outgoing or down state',()=>{const{s,c}=fixture(2);c.receive(s,effect(s,2,1));sample(c,2);s.rescue.stage='reunited';c.begin(s,false);assert.equal(sample(c,2,'attack',0,3).facing,3);s.rescue.stage='none';c.begin(s,false);assert.equal(c.inspect().current[2],null);});
for(const hero of HD_HERO_IDS)test('P frozen directional clip fingerprints match every retained painter cell '+hero,()=>{const g=JSON.parse(readFileSync('tests/fixtures/party-combat-frames.json'));assert.equal(g.schema,'retained-hd-party-combat-cells-v1');for(const pose of ['attack','cast','down'])for(let d=0;d<4;d++)for(let f=0;f<4;f++){const b=frame(hero,d,f,pose),x=g.cells[`${hero}/${pose}/${d}/${f}`];assert.equal(sha(b),x.sha256);assert.equal(rgbaFingerprint(b),x.fnv1a32);}});
for(const slot of [0,1])test('P actual core action remains facing delivered target after real target UI selection slot'+slot,()=>{const k=rig();try{const s=battle();draw(k,s);advance(s,143);assert(core.action(s,slot,'attack'));const e=s.effects.find(x=>x.actor===slot);draw(k,s);const d=actionFacing(e.origin,e);assert(core.cycleTarget(s,slot,1));advance(s,6);const b=draw(k,s);assert.equal(b.current[slot].facing,d);assert.deepEqual(texture(k,slot),frame(slot?'marle':'crono',d,b.current[slot].frame,'attack'));assert(b.history.some(h=>h.slot===slot&&h.texture?.fnv1a32===rgbaFingerprint(frame(h.actor,h.facing,h.frame,h.pose))));}finally{k.close();}});
for(const [slot,hero] of [[0,'crono'],[1,'marle'],[1,'lucca'],[2,'frog'],[2,'marle']])test(`P World actual retained down pixels and no GPU allocation ${slot}/${hero}`,()=>{const k=rig();try{const s=battle();if(hero==='lucca')s.kingdom.phase='rescue';if(slot===2)s.rescue.stage=hero==='frog'?'allied':'reunited';draw(k,s);const n=[k.w.scene.meshes.length,k.w.scene.materials.length,k.w.scene.textures.length];actor(s,slot).hp=0;s.ticks++;let b=draw(k,s);for(const age of [0,8,15,23,24]){s.ticks=1+age;b=draw(k,s);const a=b.current[slot];assert.equal(a.frame,fallenFrame(age));assert.deepEqual(texture(k,slot),frame(hero,a.facing,a.frame,'down'));}assert.deepEqual([k.w.scene.meshes.length,k.w.scene.materials.length,k.w.scene.textures.length],n);const before=structuredClone(b);draw(k,s);assert.deepEqual(k.w.inspect().partyCombat,before);}finally{k.close();}});
test('P actual normal enemy damage produces a nonfinal ally fall, preserving core death tick and queue',()=>{const k=rig();try{const s=battle();s.players[0].hp=1;draw(k,s);let found=false;for(let n=0;n<600;n++){core.step(s,core.IDLE,1/60);const hp=s.players[0].hp;const b=draw(k,s);if(hp===0){assert.equal(s.mode,'battle');assert.equal(b.current[0].frame,0);assert.equal(b.history.find(h=>h.cause.kind==='down').cause.tick,s.ticks);found=true;break;}}assert(found);}finally{k.close();}});
for(const [w,h]of [[192,128],[256,160],[240,180]])test(`P CPU down phases differ then settle exactly to O ${w}x${h}`,()=>{const a=rig(w,h),b=rig(w,h,PriorWorld);try{const s=battle();draw(a,s);draw(b,s);s.players[0].hp=0;s.ticks=1;draw(a,s);draw(b,s);a.w.scene.render();b.w.scene.render();assert.notDeepEqual(a.c.pixels(),b.c.pixels());s.ticks=24;draw(a,s);draw(b,s);a.w.scene.render();b.w.scene.render();assert.deepEqual(a.c.pixels(),b.c.pixels());}finally{b.close();a.close();}});
for(const name of Object.keys(partyPSpec.files))test('P strict inverse exact O and negative drift '+name,()=>{const raw=reactionQIfDeclared(name,readFileSync(name,'utf8')),old=partyPBaseline(name,raw);assert.equal(sha(old),partyPSpec.originalSha256[name]);assert.equal(partyPIfDeclared(name,old),old);assert.equal(partyPIfDeclared(name,raw+'\n// unrelated drift\n'),old+'\n// unrelated drift\n');const e=partyPSpec.files[name][0];assert.throws(()=>partyPBaseline(name,raw.replace(e.after,'')));assert.throws(()=>partyPBaseline(name,raw+e.after));assert.throws(()=>partyPBaseline(name,raw+'\n//unrelated drift\n'));});
test('P held and rules and prior foe work remain exact unchanged input hashes',()=>{for(const [p,h]of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03p-unchanged-inputs.json'))))assert.equal(sha(readFileSync(p)),h,p);});
for(const lethal of [false,true])test('P source-facing differs from O on an opposed target change, then fully restores; lethal='+lethal,()=>{const a=rig(),b=rig(128,96,PriorWorld);try{const s=battle();/* Explicit offline spatial fixture; actions/selection use the real unchanged core. */const p=s.players[0];Object.assign(s.enemies[0],{x:p.x+2,z:p.z,hp:lethal?30:48});Object.assign(s.enemies[1],{x:p.x-2,z:p.z});s.targets[0]=0;s.players[0].atb=1;let o=structuredClone(s);draw(a,s);draw(b,o);assert(core.action(s,0,'attack'));assert(core.action(o,0,'attack'));draw(a,s);draw(b,o);if(!lethal){assert(core.cycleTarget(s,0,1));assert(core.cycleTarget(o,0,1));}s.ticks++;o.ticks++;const actual=draw(a,s);draw(b,o);assert.equal(actual.current[0].facing,1);assert.deepEqual(texture(a,0),frame('crono',1,0,'attack'));assert.deepEqual(texture(b,0),frame('crono',3,0,'attack'));assert.notDeepEqual(texture(a,0),texture(b,0));assert.deepEqual(s,o);s.ticks=30;o.ticks=30;draw(a,s);draw(b,o);assert.deepEqual(texture(a,0),texture(b,0));assert.deepEqual(s,o);}finally{b.close();a.close();}});
