/** Q synthetic/offline fixtures. Only provider native reports can establish native evidence. */
import {combatTimingRIfDeclared} from './helpers/combat-timing-r-baseline.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{createHash}from'node:crypto';
import * as core from '../.test/core.mjs';import{PartyCombatMotion,rgbaFingerprint}from'../.test/party-combat-motion.mjs';
import{ActorTimeline}from'../.test/actor-timeline.mjs';import{drawHDHero,HD_HERO_IDS}from'../.test/hd-hero-art.mjs';import{surface}from'../scripts/asset-export.mjs';
import{World}from'../.test/cpu-entry.mjs';import{World as PriorWorld}from'../.test/reaction-q-prior-world.mjs';import{cpuTestCanvas}from'./cpu-test-canvas.mjs';
import{reactionQSpec,reactionQBaseline,reactionQIfDeclared}from'./helpers/reaction-q-baseline.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
const cell=(h,d,f,pose='hurt')=>{const s=surface(48,64);drawHDHero(s.ink,h,d,f,pose);return s.rgba;};
const actor=(s,slot)=>slot===2?s.rescue.guest:s.players[slot];
const battle=()=>{const s=core.createState('forest');s.joined=true;assert(core.beginBattle(s));return s;};
const enter=(slot=0,hero=slot===0?'crono':slot===1?'marle':'frog')=>{const s=battle();if(hero==='lucca')s.kingdom.phase='rescue';if(slot===2)s.rescue.stage=hero==='frog'?'allied':'reunited';const c=new PartyCombatMotion(),p=actor(s,slot);c.begin(s,false);return{s,c,p,slot,hero};};
const incoming=k=>({kind:'hit',x:k.p.x,z:k.p.z,text:'offline real-target fixture'});
const sample=(k,pose='hurt',frame=0,dir=1)=>k.c.sample(k.slot,{pose,frame},dir);
function drawCell(k,pose='hurt',frame=0,dir=1){const v=sample(k,pose,frame,dir);k.c.recordDraw(k.slot,()=>({width:48,height:64,data:cell(k.hero,v.facing,v.frame,v.pose)}));return v;}
function hit(k){k.s.ticks++;k.c.begin(k.s,false);const e=incoming(k);k.c.receive(k.s,e);return e;}
const view=k=>k.c.inspect().reactions;
for(const [slot,hero]of [[0,'crono'],[1,'marle'],[1,'lucca'],[2,'frog'],[2,'marle']])for(const d of [0,1,2,3])test(`Q retained facing and actual cell for ${hero}/slot${slot}/dir${d}`,()=>{const k=enter(slot,hero);drawCell(k,'ready',0,d);const before=structuredClone(k.s);hit(k);const v=drawCell(k,'hurt',0,(d+2)%4);assert.equal(v.facing,d);const r=view(k);assert.equal(r.history.length,1);assert.equal(r.history[0].cause.beforeDraw.facing,d);assert.deepEqual(r.history[0].texture,{width:48,height:64,fnv1a32:rgbaFingerprint(cell(hero,d,0))});before.ticks=k.s.ticks;assert.deepEqual(k.s,before);assert.equal(r.additionalGpuResources,0);});
test('Q retains all existing hurt clip boundaries then releases, without resetting the clock',()=>{const k=enter(),t=new ActorTimeline();drawCell(k,'ready',0,3);hit(k);t.trigger('hurt',k.s.ticks);for(const[age,frame]of[[0,0],[5,0],[6,1],[10,1],[11,2],[16,2],[17,3],[24,3]]){k.s.ticks=1+age;k.c.begin(k.s,false);const base=t.sample(k.s.ticks,false,true,{x:k.p.x,z:k.p.z,scale:1,seed:0,reducedMotion:false});assert.equal(base.frame,frame);assert.equal(drawCell(k,base.pose,base.frame,1).facing,3);}k.s.ticks=26;k.c.begin(k.s,false);assert.equal(drawCell(k,'ready',0,1).facing,1);assert.deepEqual([...new Set(view(k).history.map(h=>h.frame))],[0,1,2,3]);});
for(const invalid of ['never-drawn','heal','combo','outgoing','guest-outgoing','near-not-exact','ambiguous-target','dead','inactive','lab','explore','nonfinite'])test('Q no inferred incoming direction for '+invalid,()=>{const k=enter();if(invalid!=='never-drawn')drawCell(k,'ready',0,3);k.s.ticks++;if(invalid==='dead')k.p.hp=0;if(invalid==='inactive'){k.s.opening.phase='canyon';k.s.chapter='canyon';k.slot=1;k.p=k.s.players[1];}if(invalid==='lab')k.s.chapter='lab';if(invalid==='explore')k.s.mode='explore';if(invalid==='ambiguous-target'){k.s.players[1].x=k.p.x;k.s.players[1].z=k.p.z;}k.c.begin(k.s,false);const e=incoming(k);if(invalid==='heal')e.kind='heal';if(invalid==='combo')e.kind='combo';if(invalid==='outgoing')e.actor=0;if(invalid==='guest-outgoing')e.guest=true;if(invalid==='near-not-exact')e.x+=.01;if(invalid==='nonfinite')e.x=NaN;k.c.receive(k.s,e);drawCell(k);assert.equal(view(k).history.length,0);});
for(const reset of ['new-state','new-actor','rewind','guest-change','leave-battle'])test('Q '+reset+' cannot inherit a previous draw or reaction',()=>{const k=enter(reset==='guest-change'?2:0);drawCell(k,'ready',0,3);hit(k);drawCell(k);if(reset==='new-state'){k.s=structuredClone(k.s);k.p=actor(k.s,k.slot);}if(reset==='new-actor'){k.s.players[0]=structuredClone(k.p);k.p=k.s.players[0];}if(reset==='rewind')k.s.ticks=0;if(reset==='guest-change'){k.s.rescue.stage='reunited';k.hero='marle';}if(reset==='leave-battle')k.s.mode='explore';k.c.begin(k.s,false);const h=view(k).history.length;k.c.receive(k.s,incoming(k));assert.equal(drawCell(k,'hurt',0,1).facing,1);assert.equal(view(k).history.length,h);});
test('Q a sample without recordDraw is not a previous displayed facing',()=>{const k=enter();sample(k,'ready',0,3);hit(k);assert.equal(drawCell(k,'hurt',0,1).facing,1);assert.equal(view(k).history.length,0);});
test('Q target-only event locks observed direction, not invented origin',()=>{const k=enter();drawCell(k,'ready',0,3);const e=hit(k);drawCell(k);const h=view(k).history[0];assert.deepEqual(h.cause.effect,e);assert.equal('origin'in h.cause.effect,false);assert.equal(h.cause.kind,'delivered-target-hit');});
test('Q repeated hit restarts only at its real delivery tick and preserves current facing',()=>{const k=enter();drawCell(k,'ready',0,3);hit(k);drawCell(k);k.s.ticks=8;k.c.begin(k.s,false);k.c.receive(k.s,incoming(k));assert.equal(drawCell(k,'hurt',0,1).facing,3);assert.deepEqual(view(k).history.map(h=>h.cause.tick),[1,8]);});
test('Q same tick repeated delivery/redraw and pause do not accumulate or reread',()=>{const k=enter();let reads=0;drawCell(k,'ready',0,3);hit(k);for(let i=0;i<30;i++){k.c.begin(k.s,false);k.c.receive(k.s,incoming(k));sample(k);k.c.recordDraw(0,()=>{reads++;return{width:48,height:64,data:cell('crono',3,0)};});}assert.equal(reads,1);assert.equal(view(k).history.length,1);assert.equal(k.s.ticks,1);});
test('Q reduced preference retains the same essential hurt phase and facing',()=>{const k=enter();drawCell(k,'ready',0,3);hit(k);drawCell(k);const before=structuredClone(k.s);k.c.begin(k.s,true);assert.equal(drawCell(k,'hurt',0,1).facing,3);assert.equal(view(k).history.at(-1).reducedMotion,true);k.c.begin(k.s,false);assert.equal(drawCell(k,'hurt',0,1).facing,3);assert.deepEqual(k.s,before);});
test('Q outgoing action interrupted by actual incoming hit retains outgoing drawn facing',()=>{const k=enter();drawCell(k,'ready',0,0);k.c.receive(k.s,{kind:'hit',actor:0,origin:{x:k.p.x,z:k.p.z},x:k.p.x-2,z:k.p.z,style:'slash',text:'offline'});drawCell(k,'attack',0,1);hit(k);assert.equal(drawCell(k,'hurt',0,1).facing,3);assert.equal(view(k).history.at(-1).cause.beforeDraw.facing,3);});
test('Q reaction interrupted by cast cannot resume from a later unrelated hurt',()=>{const k=enter();drawCell(k,'ready',0,3);hit(k);drawCell(k);k.s.ticks++;k.c.begin(k.s,false);drawCell(k,'cast',0,1);assert.equal(drawCell(k,'hurt',1,1).facing,1);assert.equal(view(k).history.length,1);});
test('Q down transition cancels reaction and leaves P down ownership intact',()=>{const k=enter();drawCell(k,'ready',0,3);hit(k);drawCell(k);k.s.ticks++;k.p.hp=0;k.c.begin(k.s,false);assert.deepEqual(drawCell(k,'down',0,1),{pose:'down',frame:0,facing:3});assert.equal(view(k).history.length,1);});
test('Q history is bounded and inspector snapshots cannot mutate retained events',()=>{const k=enter();for(let i=0;i<30;i++){k.s.ticks=30*i;k.c.begin(k.s,false);drawCell(k,'ready',0,3);hit(k);drawCell(k);}const h=view(k);assert.equal(h.history.length,24);assert.equal(h.historyDropped,6);h.history[0].cause.effect.x=999;assert.notEqual(view(k).history[0].cause.effect.x,999);});
test('Q texture failure stays explicit and disposal releases pending references',()=>{const k=enter();drawCell(k,'ready',0,3);hit(k);sample(k);k.c.recordDraw(0,()=>{throw Error('fixture read failure');});assert.equal(view(k).textureReadFailures,1);assert.equal(view(k).history[0].texture,null);k.c.dispose();k.c.begin(k.s,false);k.c.receive(k.s,incoming(k));drawCell(k);assert.equal(view(k).history.length,0);assert.equal(view(k).disposed,true);});
for(const hero of HD_HERO_IDS)test('Q every retained hurt cell is frozen '+hero,()=>{const golden=JSON.parse(readFileSync('tests/fixtures/party-reaction-frames.json'));for(let d=0;d<4;d++)for(let f=0;f<4;f++){const b=cell(hero,d,f),g=golden.cells[`${hero}/hurt/${d}/${f}`];assert.equal(sha(b),g.sha256);assert.equal(rgbaFingerprint(b),g.fnv1a32);}});
function rig(w=192,h=128,W=World){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;const c=cpuTestCanvas(w,h);c.canvas.ownerDocument=doc;const world=new W(c.canvas);return{w:world,c,media,close(){world.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};}
function draw(k,s){const effects=s.effects.splice(0),before=structuredClone(s),eb=structuredClone(effects);k.w.draw(s,0,false,effects);assert.deepEqual(s,before);assert.deepEqual(effects,eb);return k.w.inspect().partyCombat;}
const texture=(k,slot)=>Buffer.from((slot===2?k.w.guest:k.w.heroes[slot]).texture.getContext().getImageData(0,0,48,64).data);
for(const[w,h]of[[192,128],[256,160],[240,180]])test(`Q real core enemy hit and selector change preserves pixels then restores exact P ${w}x${h}`,()=>{const a=rig(w,h),b=rig(w,h,PriorWorld);try{const s=battle(),p=s.players[0];/* Explicit offline positions; damage and target selection use unchanged core. */Object.assign(s.enemies[0],{x:p.x-2,z:p.z});Object.assign(s.enemies[1],{x:p.x+2,z:p.z});s.targets[0]=0;draw(a,s);let o=structuredClone(s);draw(b,o);let found=false;for(let i=0;i<500;i++){core.step(s,core.IDLE,1/60);core.step(o,core.IDLE,1/60);const incoming=s.effects.some(e=>e.kind==='hit'&&e.actor===undefined&&!e.guest&&e.x===p.x&&e.z===p.z);draw(a,s);draw(b,o);assert.deepEqual(s,o);if(incoming&&p.hp>0){found=true;assert(core.cycleTarget(s,0,1));assert(core.cycleTarget(o,0,1));s.ticks++;o.ticks++;const q=draw(a,s);draw(b,o);assert.equal(q.current[0].facing,3);assert.deepEqual(texture(a,0),cell('crono',3,q.current[0].frame));assert.notDeepEqual(texture(a,0),texture(b,0));a.w.scene.render();b.w.scene.render();assert.notDeepEqual(a.c.pixels(),b.c.pixels());s.ticks+=30;o.ticks+=30;draw(a,s);draw(b,o);a.w.scene.render();b.w.scene.render();assert.deepEqual(a.c.pixels(),b.c.pixels());assert.deepEqual(s,o);break;}}assert(found);assert.deepEqual([a.w.scene.meshes.length,a.w.scene.materials.length,a.w.scene.textures.length],[b.w.scene.meshes.length,b.w.scene.materials.length,b.w.scene.textures.length]);assert.equal(a.w.inspect().partyCombat.reactions.additionalGpuResources,0);assert(a.w.inspect().partyCombat.reactions.history.every(x=>x.texture));}finally{b.close();a.close();}});
for(const name of Object.keys(reactionQSpec.files))test('Q strict source inverse P and missing/duplicate/unrelated negatives '+name,()=>{const raw=combatTimingRIfDeclared(name,readFileSync(name,'utf8')),old=reactionQBaseline(name,raw),e=reactionQSpec.files[name][0];assert.equal(sha(old),reactionQSpec.originalSha256[name]);assert.equal(reactionQIfDeclared(name,old),old);assert.equal(reactionQIfDeclared(name,raw+'\n//drift\n'),old+'\n//drift\n');for(const x of[raw+e.after,raw.replace(e.after,''),raw+'\n//unrelated\n'])assert.throws(()=>reactionQBaseline(name,x));});
test('Q held render, core, M/N/O, painters, timelines, saves and original workflow bytes unchanged',()=>{for(const[name,h]of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03q-unchanged-inputs.json'))))assert.equal(sha(combatTimingRIfDeclared(name,readFileSync(name,'utf8'))),h,name);});
