/** O tests use actual current production. Offline fixtures below are NOT native evidence. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {VertexData,DynamicTexture} from '@babylonjs/core';
import {TREE_ROWS,TREE_ROW_ART,reshapeTreeRow,SoftwareOverloadBudget,SOFTWARE_OVERLOAD,RenderPolicy,RenderBudget} from '../.test/row-o-art.mjs';
import {ArtDirectedWorld as Current} from '../.test/row-o-world.mjs';import {ArtDirectedWorld as Prior} from '../.test/row-n-world.mjs';import {createState} from '../.test/cpu-entry.mjs';import {productionWorldRig} from './helpers/production-world-rig.mjs';import {assertWoodland} from '../scripts/woodland-evidence.mjs';import {exportProductionTreeRows} from '../scripts/production-tree-row-export.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
for(const [owner,rows]of Object.entries(TREE_ROWS))for(const row of rows)test('O planted row geometry '+owner+' '+row.x+','+row.z,()=>{const src=Array.from(VertexData.CreatePlane({width:row.width,height:row.width*1.25}).positions),copy=[...src],out=reshapeTreeRow(owner,row.x,row.z,src);assert.notEqual(out,src);assert.deepEqual(src,copy);assert.deepEqual(out,reshapeTreeRow(owner,row.x,row.z,src));for(let i=0;i<src.length;i+=3){assert.equal(out[i+2],src[i+2]);if(src[i+1]<0){assert.equal(out[i],src[i]);assert.equal(out[i+1],src[i+1]);}else{near(out[i],src[i]*row.topWidth+row.width*row.lean);near(out[i+1],-row.width*1.25/2+row.width*1.25*row.height);assert(Math.abs(out[i])<=row.width/2);}}});
for(const owner of ['held-home','home','trial-guardia1000','truce-canyon-600','__proto__','constructor'])test('O rejects non-target owner '+owner,()=>assert.equal(reshapeTreeRow(owner,-10,-7,[]),null));
for(const fault of ['short','nan','shift','duplicate','nonplanar'])test('O rejects malformed known tree '+fault,()=>{const p=Array.from(VertexData.CreatePlane({width:3.7,height:4.625}).positions);if(fault==='short')p.pop();if(fault==='nan')p[0]=NaN;if(fault==='shift')p[0]+=.01;if(fault==='duplicate')p.splice(3,3,...p.slice(0,3));if(fault==='nonplanar')p[2]=.01;assert.throws(()=>reshapeTreeRow('kingdom-truce',-10,-7,p),RangeError);});
function view(Type,ch){const r=productionWorldRig(Type,192,128);try{const state=createState(ch),old=structuredClone(state);for(let i=0;i<3;i++)r.world.draw(state,0,false,[]);assert.deepEqual(state,old);const s=r.world.engine.scenes[0];return {pixels:sha(r.canvas.pixels()),inspection:r.world.inspect(),counts:[s.meshes.length,s.textures.length,s.materials.length,s.geometries.length],meshes:s.meshes.map(m=>({name:m.name,parent:m.parent?.name,pos:m.position.asArray(),scale:m.scaling.asArray(),uv:Array.from(m.getVerticesData('uv')??[]),vertices:Array.from(m.getVerticesData('position')??[]),indices:Array.from(m.getIndices()??[])})),textures:s.textures.filter(t=>t instanceof DynamicTexture).map(t=>[t.name,sha(t.getContext().getImageData(0,0,t.getSize().width,t.getSize().height).data)])};}finally{r.close();}}
for(const [ch,count]of [['truce',4],['forest',12]])test('O actual '+ch+' changes only '+count+' oak geometries; pixels/resources/native helper remain real',()=>{const a=view(Current,ch),b=view(Prior,ch);assert.notEqual(a.pixels,b.pixels);assert.deepEqual(a.textures,b.textures);assert.deepEqual(a.counts.slice(0,3),b.counts.slice(0,3));assert.equal(a.counts[3]-b.counts[3],count);assert.equal(a.inspection.productionArt.treeRows.bindings,count);assert.equal(a.inspection.productionArt.treeRows.geometryPayloadBytes,count*152);assert.equal(a.inspection.renderer.cpu.unsupportedResources,0);assertWoodland(a.inspection.storyNpcs.kingdom.woodland,ch);assert.deepEqual(a.meshes.filter(m=>m.name!=='oak'),b.meshes.filter(m=>m.name!=='oak'));for(const m of a.meshes.filter(m=>m.name==='oak')){const old=b.meshes.find(n=>n.name===m.name&&JSON.stringify(n.pos)===JSON.stringify(m.pos));for(const key of ['name','pos','scale','uv','indices'])assert.deepEqual(m[key],old[key]);const expected=reshapeTreeRow('kingdom-'+ch,m.pos[0],m.pos[2],old.vertices);m.vertices.forEach((v,i)=>near(v,expected[i]));}for(const k of ['partyCombat','actorPlayback','grounding','poses','guest','combatTiming'])assert.deepEqual(a.inspection[k],b.inspection[k]);});
for(const ch of ['bedroom','downstairs','home','fair','canyon','courtroom','guardia1000','castle','chamber','cathedral','passage','sanctum','cell','prison','bridge','future'])test('O '+ch+' full offline frame, geometry, textures and resources unchanged',()=>{const a=view(Current,ch),b=view(Prior,ch);assert.equal(a.pixels,b.pixels);assert.deepEqual(a.meshes,b.meshes);assert.deepEqual(a.textures,b.textures);assert.deepEqual(a.counts,b.counts);});
test('O repeated maps retain at most sixteen geometry payloads and release on disposal',()=>{const r=productionWorldRig(Current,160,100);try{for(let i=0;i<4;i++)for(const c of ['truce','forest','canyon','home'])r.world.draw(createState(c),0,false,[]);const s=r.world.engine.scenes[0],a=r.world.inspect().productionArt.treeRows;assert.equal(a.authored,16);assert.equal(a.bindings,16);assert.equal(a.geometryPayloadBytes,TREE_ROW_ART.maxGeometryPayloadBytes);for(const name of Object.keys(TREE_ROWS))s.getTransformNodeByName(name).dispose();assert.equal(r.world.inspectProductionArt().treeRows.bindings,0);assert.equal(s.geometries.filter(g=>g.id.startsWith('tree-row-art-')).length,0);}finally{r.close();}});
for(const fault of ['root','external','position','texture','sharing'])test('O '+fault+' drift restores own source without overwriting external owner',()=>{const r=productionWorldRig(Current,160,100);try{r.world.draw(createState('truce'),0,false,[]);const s=r.world.engine.scenes[0],root=s.getTransformNodeByName('kingdom-truce'),m=root.getChildMeshes().find(m=>m.name==='oak'),owned=m.geometry;let external;if(fault==='root')root.position.x=.1;if(fault==='position')m.position.z+=.1;if(fault==='external'){external=owned.copy('external-tree');external.applyToMesh(m);}if(fault==='texture')m.material.diffuseTexture=null;if(fault==='sharing')owned.applyToMesh(root.getChildMeshes().find(n=>n.name==='oak'&&n!==m));s.onBeforeRenderObservable.notifyObservers(s);assert.equal(r.world.inspectProductionArt().treeRows.bindings,0);assert.equal(r.world.inspectProductionArt().treeRows.rejections,1);if(external){assert.equal(m.geometry,external);assert(!external.isDisposed());}assert(owned.isDisposed()||owned.meshes.length>0);}finally{r.close();}});
test('O sixteen exported models match actual current mesh arrays and independent exports',async()=>{const out=mkdtempSync(join(tmpdir(),'row-o-')),r=productionWorldRig(Current,160,100);try{const mf=await exportProductionTreeRows(out),raw=readFileSync(join(out,'tree-row-models.json'));assert.equal(sha(raw),mf.modelSha256);assert.equal(mf.modelCount,16);assert.equal(mf.nativeEvidence,false);for(const c of ['truce','forest'])r.world.draw(createState(c),0,false,[]);const scene=r.world.engine.scenes[0];for(const e of JSON.parse(raw).models){const matches=scene.meshes.filter(m=>m.name===e.name&&m.parent?.name===e.owner&&m.position.asArray().every((v,i)=>Math.abs(v-e.position[i])<1e-7));assert.equal(matches.length,1);const m=matches[0];for(const [k,vs]of [['position',e.positions],['normal',e.normals],['uv',e.uvs]])Array.from(m.getVerticesData(k)).forEach((v,i)=>near(v,vs[i]));assert.deepEqual(Array.from(m.getIndices()),e.indices);}await exportProductionTreeRows(join(out,'again'));assert.deepEqual(readFileSync(join(out,'again','tree-row-models.json')),raw);}finally{r.close();rmSync(out,{recursive:true,force:true});}});
// Synthetic timing sequences, never passed as native evidence or edited frame reports.
test('O sustained severe software stalls now progress within the existing three levels',()=>{const p=new RenderPolicy('software');let changed=0;for(let i=0;i<100;i++)if(p.sample(400,true))changed++;assert.equal(changed,3);assert.equal(p.inspect().level,3);assert.equal(p.inspect().reason,'software-sustained-overload');assert.equal(p.scale(1200,800,1),2);assert.equal(p.inspect().frames.meanMs,400);assert.equal(p.inspect().frames.fps,2.5);assert.equal(p.inspect().softwareOverload.lastWindow.meanMs,400);});
test('O original 250ms filter and >250ms raw frame truth remain unchanged',()=>{const b=new RenderBudget(),p=new RenderPolicy('software');for(let i=0;i<150;i++){assert.equal(b.sample(400,true),false);p.sample(400,true);}assert.equal(b.inspect().level,0);assert.equal(b.inspect().samples,0);assert.equal(p.inspect().frames.p95Ms,400);assert.equal(p.inspect().frames.maxMs,400);assert(p.inspect().softwareOverload.samples<24);});
for(const mode of ['quality','compatibility'])test('O explicit '+mode+' remains user-owned',()=>{const p=new RenderPolicy('software');p.setMode(mode);for(let i=0;i<500;i++)assert.equal(p.sample(400,true),false);assert.equal(p.inspect().level,0);assert.equal(p.inspect().reason,'user-'+mode);});
for(const hint of ['unverified','cpu'])test('O no severe software-WebGL policy on '+hint,()=>{const p=new RenderPolicy(hint);for(let i=0;i<200;i++)assert.equal(p.sample(400,true),false);assert.equal(p.inspect().level,0);assert.equal(p.inspect().softwareOverload,undefined);});
test('O isolated spikes, invalid/loading intervals and pauses cannot accumulate a severe verdict',()=>{const p=new SoftwareOverloadBudget();for(let i=0;i<400;i++)assert.equal(p.sample(i%25===0?700:16.67,true),false);assert.equal(p.inspect().level,0);for(let i=0;i<23;i++)p.sample(400,true);p.sample(500,false);assert.equal(p.inspect().samples,0);assert.equal(p.inspect().warmup,4);for(const x of [NaN,Infinity,-1,0,2001,20000]){const b=new SoftwareOverloadBudget();for(let i=0;i<27;i++)b.sample(400,true);assert.equal(b.sample(x,true),false);assert.equal(b.inspect().samples,0);assert.equal(b.inspect().level,0);}});
test('O exact software watchdog boundaries and manual reset are deterministic',()=>{for(const ms of [250,300]){const b=new SoftwareOverloadBudget();for(let i=0;i<100;i++)assert.equal(b.sample(ms,true),false);}const b=new SoftwareOverloadBudget();for(let i=0;i<28;i++)b.sample(301,true);assert.equal(b.inspect().level,1);const snapshot=b.inspect();snapshot.lastWindow.meanMs=0;assert.equal(b.inspect().lastWindow.meanMs,301);b.reset();assert.equal(b.inspect().level,0);assert.equal(b.inspect().lastWindow,null);const p=new RenderPolicy('software');for(let i=0;i<100;i++)p.sample(400,true);p.setMode('auto');assert.equal(p.inspect().level,0);assert.equal(p.scale(1200,800,1),1.25);});
