import {artEIfDeclared,artEFrozenBytes,artEIsNew} from './helpers/production-character-e-baseline.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {createHash} from 'node:crypto';
import {artDSpec,artDBaseline,artDIfDeclared} from './helpers/production-party-d-baseline.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
for(const [name,e]of Object.entries(artDSpec.files))test('D declared source roundtrip and drift rejection '+name,()=>{const s=artEIfDeclared(name,readFileSync(name,'utf8'));assert.equal(sha(artDBaseline(name,s)),e.sha256);assert.equal(artDIfDeclared(name,artDBaseline(name,s)),artDBaseline(name,s));for(const bad of [s.slice(1),s+s,s+'\n// unrelated\n'])assert.throws(()=>artDBaseline(name,bad));});
test('D keeps every other program input byte-exact including legacy poses, native routes, assertions and held prologue',()=>{
 const pin=JSON.parse(readFileSync('tests/baselines/vq04d-unchanged-inputs.json')),names=[...pin.rootFiles];function walk(d){for(const e of readdirSync(d,{withFileTypes:true})){if(e.name==='__pycache__'||e.name.endsWith('.pyc'))continue;assert(!e.isSymbolicLink());const n=d+'/'+e.name;if(e.isDirectory())walk(n);else if(e.isFile())names.push(n);}}for(const root of pin.roots)walk(root);const rows=names.sort().filter(n=>!pin.exclude.includes(n)&&!artEIsNew(n)).map(n=>[n,sha(artEFrozenBytes(n,readFileSync(n)))]);assert.equal(rows.length,pin.expectedCount);assert.equal(sha(JSON.stringify(rows)),pin.sha256);
 for(const n of ['src/hd-hero-art.ts','src/render.ts','src/prologue-render.ts','src/core.ts','tests/party_combat.py','tests/party_reaction.py','tests/fixtures/party-combat-frames.json','.github/workflows/ci.yml'])assert(rows.some(([path])=>path===n));
});
test('D source boundaries expose partial redraw truthfully without state, timing, evidence or browser-specific substitutions',()=>{
 const runtime=readFileSync('src/production-party-finish.ts','utf8'),entry=readFileSync('src/art-directed-world.ts','utf8');assert(entry.includes('this.partyArt.begin(state.chapter);super.draw(state,dt,animate,frameEffects)'));assert(entry.includes('super.inspect().partyCombat.current[slot]'));assert(!/setTimeout|setInterval|requestAnimationFrame|localStorage|location|navigator|fetch\(|takeFrameEffects/.test(runtime));assert(runtime.includes('equalPartyPixels(partyCell(code,true),bytes)'));assert(runtime.includes('PARTY_ART.redrawnPoses.includes(pose.pose)'));assert(artEIfDeclared('scripts/build.mjs',readFileSync('scripts/build.mjs','utf8')).includes("version:'0.9.77',batch:'VQ04D'"));
 for(const n of ['native.json','pixels.png','src/core.ts','src/prologue-render.ts','tests/party_combat.py','tests/fixtures/party-combat-frames.json'])assert.throws(()=>artDBaseline(n,'{}'));
 const m=JSON.parse(readFileSync('assets/manifest.json')),item=m.items.find(x=>x.id==='party-exploration-vq04d');assert.equal(item.required,true);assert.equal(item.stage,'review');assert.equal(item.romExtracted,false);
});
