/** Offline unit tests only. Not a native gameplay capture producer. */
import test from 'node:test';import assert from 'node:assert/strict';import {NpcAttention,NPC_ATTENTION} from '../.test/production-npc-attention.mjs';import {createState} from '../.test/cpu-entry.mjs';
function state(){const s=createState('truce');s.kingdom.phase='arrival';s.players[0].x=0;s.players[0].z=0;return s;}
for(const [x,z,facing] of [[1,0,1],[-1,0,3],[0,1,2],[0,-1,0]])test('G real party direction '+facing+' selects facing and authored greet, not movement',()=>{const s=state(),a=new NpcAttention();s.players[0].x=x;s.players[0].z=z;const copy=structuredClone(s);a.begin(s);assert.deepEqual(a.select('resident',0,0),{facing,pose:'greet'});assert.deepEqual(s,copy);assert.equal(a.inspect().directionalMovementEnabled,false);});
test('G far party stays front ambient; greeting and release radii have hysteresis',()=>{const s=state(),a=new NpcAttention();for(const [x,want] of [[4,'ambient'],[3,'ambient'],[1.8,'greet'],[2.1,'greet'],[2.4,'ambient']]){s.players[0].x=x;a.begin(s);assert.equal(a.select('npc',0,0).pose,want);}s.players[0].x=3.5;a.begin(s);assert.equal(a.select('npc',0,0).facing,1);s.players[0].x=3.7;a.begin(s);assert.deepEqual(a.select('npc',0,0),{facing:0,pose:'ambient'});});
test('G hidden P2 and downed P1 cannot attract an NPC',()=>{const s=state(),a=new NpcAttention();s.players[0].x=8;s.players[1].x=1;s.players[1].z=0;a.begin(s);assert.equal(a.inspect().targets.length,1);assert.equal(a.select('npc',0,0).pose,'ambient');s.kingdom.phase='rescue';a.begin(s);assert.equal(a.inspect().targets.length,2);assert.equal(a.select('npc',0,0).facing,1);s.players[1].hp=0;s.players[0].hp=0;a.begin(s);assert.equal(a.inspect().targets.length,0);assert.equal(a.select('npc',0,0).pose,'ambient');});
test('G closest living party and target hysteresis do not flicker at a P1/P2 tie',()=>{const s=state(),a=new NpcAttention();s.kingdom.phase='rescue';s.players[0].x=1;s.players[1].x=-1;s.players[1].z=0;a.begin(s);assert.equal(a.select('npc',0,0).facing,1);s.players[1].x=-.85;a.begin(s);assert.equal(a.select('npc',0,0).facing,1);s.players[1].x=-.5;a.begin(s);assert.equal(a.select('npc',0,0).facing,3);});
test('G diagonal axis hysteresis, zero-distance and paused repeated input are stable',()=>{const s=state(),a=new NpcAttention();s.players[0].x=1;s.players[0].z=.7;a.begin(s);assert.equal(a.select('npc',0,0).facing,1);s.players[0].z=1.05;a.begin(s);assert.equal(a.select('npc',0,0).facing,1);s.players[0].x=s.players[0].z=0;a.begin(s);assert.equal(a.select('npc',0,0).facing,1);const v=a.inspect();for(let i=0;i<30;i++){a.begin(s);a.select('npc',0,0);}assert.deepEqual(a.inspect(),v);});
for(const mode of ['battle','victory','defeat'])test('G '+mode+' clears attention without advancing the simulation',()=>{const s=state(),a=new NpcAttention();a.begin(s);a.select('npc',0,0);s.mode=mode;a.begin(s);assert.equal(a.inspect().choices.length,0);assert.equal(a.inspect().targets.length,0);assert.equal(s.ticks,0);});
test('G cutscene, invalid positions and invalid tick fail closed',()=>{const s=state(),a=new NpcAttention();for(const bad of [NaN,Infinity]){s.players[0].x=bad;a.begin(s);assert.equal(a.inspect().targets.length,0);}s.players[0].x=0;s.kingdom.phase='erasing';a.begin(s);assert.equal(a.inspect().targets.length,0);s.kingdom.phase='none';s.ticks=-1;a.begin(s);assert.equal(a.inspect().targets.length,0);assert.equal(a.select('npc',NaN,0).pose,'ambient');});
test('G copies scalar targets, bounds retained choices and clears on held scene or rewind',()=>{const s=state(),a=new NpcAttention();s.ticks=100;a.begin(s);s.players[0].x=9;assert.equal(a.select('npc',0,0).pose,'greet');for(let n=0;n<30;n++)a.select('npc'+n,0,0);assert.equal(a.inspect().choices.length,NPC_ATTENTION.limit);s.ticks=0;a.begin(s);assert.equal(a.inspect().choices.length,0);s.chapter='home';a.begin(s);assert.equal(a.inspect().targets.length,0);a.clear();assert.equal(a.inspect().tick,null);});
