/** Actual renderer/geometry/framebuffer unit ports; OFFLINE, not browser/native evidence. */
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';
import {MeshBuilder,TransformNode,StandardMaterial,DynamicTexture,VertexBuffer,Vector3,Ray} from '@babylonjs/core';
import {ArtDirectedWorld as Current} from '../.test/art-directed-world.mjs';import {ArtDirectedWorld as Prior} from '../.test/art-directed-world-g.mjs';import {World,createState} from '../.test/cpu-entry.mjs';import {installProductionArchitecture} from '../.test/production-architecture-finish.mjs';import {productionWorldRig} from './helpers/production-world-rig.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex'),canyon=JSON.parse(readFileSync('tests/fixtures/ci82-canyon-state.json')).state;
function state(ch){const s=ch==='canyon'?structuredClone(canyon):createState(ch);s.kingdom.phase='arrival';if(ch==='cathedral')s.rescue.stage='entered';return s;}
const geometry=g=>({positions:Array.from(g.getVerticesData('position')??[]),normals:Array.from(g.getVerticesData('normal')??[]),uv:Array.from(g.getVerticesData('uv')??[]),indices:Array.from(g.getIndices()??[])});
const candidate=m=>m.geometry?.id.startsWith('architecture-art-');
function observed(Type,ch){const r=productionWorldRig(Type,300,200);try{const s=state(ch),copy=structuredClone(s);r.world.draw(s,0,false,[]);assert.deepEqual(s,copy);const scene=r.world.engine.scenes[0],camera=scene.activeCamera,v=r.world.inspect();
 return {frame:sha(r.canvas.pixels()),v,meshes:scene.meshes.map(m=>({name:m.name,position:m.position.asArray(),rotation:m.rotation.asArray(),scale:m.scaling.asArray(),visible:m.isVisible,enabled:m.isEnabled(),material:m.material?.name,shape:m.geometry?geometry(m.geometry):null,xyz:m.getVerticesData('position')?Array.from(m.getVerticesData('position')).map((_,i,a)=>i%3===0?Vector3.TransformCoordinates(new Vector3(a[i],a[i+1],a[i+2]),m.computeWorldMatrix(true)).asArray():null).filter(Boolean):[]})),textures:scene.textures.filter(t=>t instanceof DynamicTexture).map(t=>[t.name,sha(t.getContext().getImageData(0,0,t.getSize().width,t.getSize().height).data)]),camera:[camera.position.asArray(),camera.orthoTop,camera.orthoBottom,camera.orthoLeft,camera.orthoRight]};}finally{r.close();}}
for(const [ch,count]of [['truce',100],['courtroom',10]])test('H actual '+ch+' frame uses private model changes and truthful untouched transforms/textures/State/camera',()=>{const g=observed(Prior,ch),h=observed(Current,ch);assert.notEqual(h.frame,g.frame);assert.deepEqual(h.textures,g.textures);assert.deepEqual(h.camera,g.camera);assert.equal(h.meshes.length,g.meshes.length);let changed=0;
 for(let i=0;i<h.meshes.length;i++){const a=h.meshes[i],b=g.meshes[i],{shape:as,xyz:ax,...ap}=a,{shape:bs,xyz:bx,...bp}=b;assert.deepEqual(ap,bp);if(JSON.stringify(as)!==JSON.stringify(bs)){changed++;assert.deepEqual(as.uv,bs.uv);assert.deepEqual(as.indices,bs.indices);for(let j=0;j<ax.length;j++){assert(Math.abs(ax[j][0]-bx[j][0])<2e-6,a.name);assert(Math.abs(ax[j][2]-bx[j][2])<2e-6,a.name);}for(let j=0;j<as.normals.length;j+=3)assert(Math.abs(Math.hypot(...as.normals.slice(j,j+3))-1)<1e-5);}else assert.deepEqual(ax,bx);}
 assert.equal(changed,count);const p=h.v.productionArt.architecture;assert.equal(p.bindings,count);assert.equal(p.geometryBytes,count*912);assert.equal(p.additionalTextures,0);assert.equal(h.v.renderer.cpu.unsupportedResources,0);assert(h.v.renderer.cpu.textureMemory.bytes<33554432);
 for(const key of ['partyCombat','combatTiming','grounding','trialMaps','storyNpcs','poses','guest','woodlandOcclusion','actorPlayback'])assert.deepEqual(h.v[key],g.v[key],key);
});
for(const ch of ['bedroom','home','downstairs','canyon','fair','forest','castle','chamber','cathedral','sanctum','overworld1000','cellblock','hall1000','guardia1000','futuregate'])test('H held/non-target '+ch+' whole application frame remains exact G',()=>{assert.equal(observed(Current,ch).frame,observed(Prior,ch).frame);});
test('H retained original geometry is untouched; every owned copy restores on disposal and no clone grows on re-entry',()=>{const r=productionWorldRig(Prior,240,160);try{const scene=r.world.engine.scenes[0];for(const ch of ['truce','courtroom','home'])r.world.draw(state(ch),0,false,[]);const original=scene.meshes.map(m=>({mesh:m,geo:m.geometry,shape:m.geometry&&geometry(m.geometry)})),baseCounts=[scene.meshes.length,scene.textures.length,scene.materials.length,scene.geometries.length],pass=installProductionArchitecture(scene);
 for(let i=0;i<3;i++)for(const ch of ['truce','courtroom','home'])r.world.draw(state(ch),0,false,[]);assert.equal(pass.inspect().bindings,110);assert.equal(pass.inspect().authored,110);assert.equal(pass.inspect().geometryBytes,100320);
 assert.deepEqual([scene.meshes.length,scene.textures.length,scene.materials.length],baseCounts.slice(0,3));for(const p of original)if(p.geo)assert.deepEqual(geometry(p.geo),p.shape);
 pass.dispose();for(const p of original)assert.equal(p.mesh.geometry,p.geo);assert.equal(scene.geometries.length,baseCounts[3]);assert.equal(pass.inspect().bindings,0);assert.equal(pass.inspect().geometryBytes,0);pass.dispose();}finally{r.close();}});
test('H owner disposal frees orphan originals/copies and live scene disposal releases counters',()=>{const r=productionWorldRig(Current);try{r.world.draw(state('truce'),0,false,[]);const scene=r.world.engine.scenes[0],root=scene.getTransformNodeByName('kingdom-truce');assert.equal(r.world.inspectProductionArt().architecture.bindings,100);root.dispose();assert.equal(r.world.inspectProductionArt().architecture.bindings,0);assert.equal(scene.geometries.filter(g=>g.id.startsWith('architecture-art-')).length,0);r.world.engine.dispose();assert(r.world.inspectProductionArt().architecture.disposed);}finally{r.close();}});
for(const change of ['material','geometry','parent','name','position','root-transform'])test('H releases on '+change+' drift without overwriting replacement owner properties',()=>{const r=productionWorldRig(Prior);try{r.world.draw(state('courtroom'),0,false,[]);const scene=r.world.engine.scenes[0],pass=installProductionArchitecture(scene);scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(pass.inspect().bindings,10);const root=scene.getTransformNodeByName('trial-courtroom'),m=scene.getMeshByName('courtroom-defendant-stand');let replacement;
 if(change==='material'){replacement=new StandardMaterial('external-owner',scene);m.material=replacement;}else if(change==='geometry'){replacement=m.geometry.copy('external-owner');replacement.applyToMesh(m);}else if(change==='parent'){replacement=new TransformNode('external-owner',scene);m.parent=replacement;}else if(change==='name')m.name='external-owner';else if(change==='position')m.position.y+=.1;else root.scaling.y=.9;
 scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(pass.inspect().bindings,0);assert.equal(pass.inspect().rejections,1);if(change==='material')assert.equal(m.material,replacement);if(change==='geometry')assert.equal(m.geometry,replacement);if(change==='parent')assert.equal(m.parent,replacement);if(change==='name')assert.equal(m.name,'external-owner');if(change==='position')assert.equal(m.position.y,.53);if(change==='root-transform')assert.equal(root.scaling.y,.9);scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(pass.inspect().bindings,0);pass.dispose();}finally{r.close();}});
test('H unknown/incomplete/duplicate or transformed structures allocate nothing and never touch held geometry',()=>{const r=productionWorldRig(World);try{const scene=r.world.engine.scenes[0],pass=installProductionArchitecture(scene);for(const name of ['held-home','kingdom-truce','trial-courtroom']){const root=new TransformNode(name,scene),mesh=MeshBuilder.CreateBox(name==='kingdom-truce'?'truce-plaster':'courtroom-defendant-stand',{},scene);mesh.parent=root;mesh.material=new StandardMaterial('untrusted',scene);}const n=scene.geometries.length;scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(pass.inspect().bindings,0);assert.equal(scene.geometries.length,n);pass.dispose();assert.throws(()=>installProductionArchitecture({isDisposed:true}));}finally{r.close();}});

test('H the unchanged observed court state has fewer real triangle blockers across the same 51 actor samples',()=>{
 const fixture=JSON.parse(readFileSync('tests/fixtures/ci103-court-architecture-regression.json'));
 function observe(Type){const r=productionWorldRig(Type,240,160);try{const state=structuredClone(fixture.state),copy=structuredClone(state);r.world.draw(state,0,false,[]);assert.deepEqual(state,copy);const sc=r.world.engine.scenes[0],m=sc.getMeshByName('player-0'),forward=sc.activeCamera.getDirection(Vector3.Forward()).normalize(),shapes=sc.meshes.filter(m=>/courtroom-(judge-rostrum|defendant-stand)|place-art-stand/.test(m.name));let blocked=0;
 for(const x of [-.25,0,.25])for(let iy=0;iy<17;iy++){const p=Vector3.TransformCoordinates(new Vector3(x,-.6+iy*.075,0),m.computeWorldMatrix(true)),ray=new Ray(p.subtract(forward.scale(64)),forward,63.98);if(shapes.some(g=>{const hit=ray.intersectsMesh(g,false);return hit.hit&&hit.distance>0&&hit.distance<ray.length;}))blocked++;}
 return {blocked,actor:m.position.asArray(),foot:r.world.inspect().grounding};}finally{r.close();}}
 const g=observe(Prior),h=observe(Current);assert(g.blocked>0);assert(h.blocked<g.blocked);assert.deepEqual(h.actor,g.actor);assert.deepEqual(h.foot,g.foot);
});
for(const kind of ['positions','normals','uv','indices','shared','duplicate-root'])test('H known names alone cannot admit changed '+kind+' source',()=>{const r=productionWorldRig(Prior);try{r.world.draw(state('courtroom'),0,false,[]);const scene=r.world.engine.scenes[0],m=scene.getMeshByName('courtroom-defendant-stand');if(kind==='positions'||kind==='normals'||kind==='uv'){const key=kind==='positions'?'position':kind==='normals'?'normal':'uv',a=Array.from(m.getVerticesData(key));a[0]+=.2;m.setVerticesData(key,a,false);}else if(kind==='indices'){const a=Array.from(m.getIndices());[a[0],a[1]]=[a[1],a[0]];m.setIndices(a);}else if(kind==='shared'){const other=MeshBuilder.CreateBox('external',{},scene);m.geometry.applyToMesh(other);}else new TransformNode('trial-courtroom',scene);
 const n=scene.geometries.length,pass=installProductionArchitecture(scene);scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(pass.inspect().bindings,0);assert.equal(scene.geometries.length,n);pass.dispose();}finally{r.close();}});
