/** Actual-application offline tests. These do not operate a browser or create native evidence. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {DynamicTexture,Geometry,Mesh,TransformNode,VertexData} from '@babylonjs/core';
import {ArtDirectedWorld as Current} from '../.test/roof-m-world.mjs';import {ArtDirectedWorld as Prior} from '../.test/roof-l-world.mjs';import {ROOF_ART,dressProductionRoof} from '../.test/roof-m-art.mjs';import {installProductionArchitecture} from '../.test/roof-m-finish.mjs';import {createState} from '../.test/cpu-entry.mjs';import {productionWorldRig} from './helpers/production-world-rig.mjs';import {assertVillage} from '../scripts/village-evidence.mjs';import {assertTownSignOcclusion} from '../scripts/town-route-evidence.mjs';import {exportProductionRoof} from '../scripts/production-roof-export.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex'),fixture=JSON.parse(readFileSync('tests/fixtures/ci109-roof-stops.json'));
const roof=n=>['truce-pitched-roof','truce-roof-course','truce-ridge'].includes(n);
const box=()=>VertexData.CreateBox({width:2,height:.18,depth:4});
function record(m){return {name:m.name,position:m.position.asArray(),rotation:m.rotation.asArray(),scale:m.scaling.asArray(),material:m.material?.name,visibility:m.visibility,vertices:Array.from(m.getVerticesData('position')??[]),uv:Array.from(m.getVerticesData('uv')??[]),normal:Array.from(m.getVerticesData('normal')??[]),indices:Array.from(m.getIndices()??[])};}
function observe(Type,state,w=256,h=170){const r=productionWorldRig(Type,w,h);try{const s=structuredClone(state),before=structuredClone(s);for(let i=0;i<3;i++)r.world.draw(s,0,false,[]);assert.deepEqual(s,before);const scene=r.world.engine.scenes[0];return {frame:sha(r.canvas.pixels()),inspection:r.world.inspect(),meshes:scene.meshes.map(record),textures:scene.textures.filter(t=>t instanceof DynamicTexture).map(t=>[t.name,sha(t.getContext().getImageData(0,0,t.getSize().width,t.getSize().height).data)]),counts:[scene.meshes.length,scene.textures.length,scene.materials.length,scene.geometries.length]};}finally{r.close();}}
for(const name of ['truce-pitched-roof','truce-roof-course','truce-ridge'])test('M pure roof author copies known '+name+' with finite unit UVs',()=>{const b=box(),p=Array.from(b.positions),u=Array.from(b.uvs),before=structuredClone([p,u]),a=dressProductionRoof(name,p,u);assert.deepEqual([p,u],before);assert.equal(a.positions.length,72);assert.equal(a.uvs.length,48);assert(a.positions.every(Number.isFinite));assert(a.uvs.every(v=>v>=0&&v<=1));assert.deepEqual(a,dressProductionRoof(name,p,u));a.positions.fill(0);assert.notDeepEqual(a,dressProductionRoof(name,p,u));});
for(const name of ['oak','truce-plaster','truce-door','inn-sign','__proto__',undefined])test('M unknown or non-roof '+name+' is not authored',()=>assert.equal(dressProductionRoof(name,[],[]),null));
for(const defect of ['short','nan','infinite','uv-short','uv-outside','zero-width'])test('M malformed roof '+defect+' fails closed',()=>{const b=box(),p=Array.from(b.positions),u=Array.from(b.uvs);if(defect==='short')p.pop();if(defect==='nan')p[1]=NaN;if(defect==='infinite')p[2]=Infinity;if(defect==='uv-short')u.pop();if(defect==='uv-outside')u[1]=2;if(defect==='zero-width')for(let i=0;i<p.length;i+=3)p[i]=0;assert.throws(()=>dressProductionRoof('truce-pitched-roof',p,u),RangeError);});
test('M roof sheet UV rows turn across the slope, not the ridge; geometry stays unchanged',()=>{const b=box(),a=dressProductionRoof('truce-pitched-roof',Array.from(b.positions),Array.from(b.uvs));assert.deepEqual(a.positions,Array.from(b.positions));for(let i=0;i<a.uvs.length;i+=2){assert.equal(a.uvs[i],b.uvs[i+1]);assert.equal(a.uvs[i+1],1-b.uvs[i]);}});
test('M narrower roof courses keep centroid and every longitudinal coordinate',()=>{const b=box(),p=Array.from(b.positions),a=dressProductionRoof('truce-roof-course',p,Array.from(b.uvs));for(let i=0;i<p.length;i+=3){assert.equal(a.positions[i],p[i]*ROOF_ART.courseCrossSection);assert.equal(a.positions[i+1],p[i+1]*ROOF_ART.courseCrossSection);assert.equal(a.positions[i+2],p[i+2]);}assert.deepEqual(a.uvs,Array.from(b.uvs));});
test('M ridge taper leaves base and ridge length seated',()=>{const b=box(),p=Array.from(b.positions),a=dressProductionRoof('truce-ridge',p,Array.from(b.uvs));for(let i=0;i<p.length;i+=3){assert.equal(a.positions[i],p[i]*(p[i+1]>0?.6:1));assert.equal(a.positions[i+1],p[i+1]);assert.equal(a.positions[i+2],p[i+2]);}});
test('M actual current Truce changes roof rendering only; textures/native samples/State and resources retained',()=>{const s=createState('truce'),a=observe(Current,s),b=observe(Prior,s);assert.notEqual(a.frame,b.frame);assert.deepEqual(a.textures,b.textures);assert.deepEqual(a.counts,b.counts);assert.equal(a.inspection.productionArt.architecture.roofPartsAuthored,44);assert.equal(a.inspection.productionArt.architecture.geometryBytes,91200);assert.equal(a.inspection.renderer.cpu.unsupportedResources,0);assertVillage(a.inspection.storyNpcs.kingdom.village,'truce');assert.deepEqual(a.meshes.filter(m=>!roof(m.name)),b.meshes.filter(m=>!roof(m.name)));for(let i=0;i<a.meshes.length;i++)if(roof(a.meshes[i].name)){const x=a.meshes[i],y=b.meshes[i];for(const k of ['name','position','rotation','scale','material','indices','visibility'])assert.deepEqual(x[k],y[k],k);if(x.name==='truce-pitched-roof')assert.deepEqual(x.vertices,y.vertices);else assert.deepEqual(x.uv,y.uv);}for(const k of ['partyCombat','actorPlayback','poses','guest','grounding','combatTiming','earlyCamera'])assert.deepEqual(a.inspection[k],b.inspection[k],k);});
for(const ch of ['bedroom','downstairs','home','fair','canyon','forest','castle','chamber','cathedral','passage','sanctum','courtroom','cell','prison','bridge','future'])test('M '+ch+' non-target/held complete pixels and meshes retained',()=>{const a=observe(Current,createState(ch),160,100),b=observe(Prior,createState(ch),160,100);assert.equal(a.frame,b.frame);assert.deepEqual(a.meshes,b.meshes);assert.deepEqual(a.textures,b.textures);assert.equal(a.inspection.productionArt.architecture.roofPartsAuthored,0);});
for(const stop of fixture.stops)test('M original CI109 '+stop.name+' stopping point retains truthful village and inn gates',()=>{const a=observe(Current,stop.state,208,450),b=observe(Prior,stop.state,208,450);assertVillage(a.inspection.storyNpcs.kingdom.village,'truce');assertTownSignOcclusion(a.inspection.townSignOcclusion,stop.state);assert.deepEqual(a.textures,b.textures);assert.deepEqual(a.inspection.townSignOcclusion,b.inspection.townSignOcclusion);assert.equal(a.inspection.productionArt.architecture.roofPartsAuthored,44);});
test('M repeated switching and disposal add no meshes/textures/materials and release private geometry',()=>{const r=productionWorldRig(Current,160,100);try{for(let i=0;i<6;i++)for(const ch of ['truce','courtroom','forest','home'])r.world.draw(createState(ch),0,false,[]);const scene=r.world.engine.scenes[0],before=r.world.inspect().productionArt.architecture;assert.equal(before.roofPartsAuthored,44);assert.equal(before.bindings,110);assert.equal(before.geometryBytes,100320);assert.equal(before.roots,2);for(const n of ['kingdom-truce','trial-courtroom'])scene.getTransformNodeByName(n).dispose();assert.equal(r.world.inspect().productionArt.architecture.bindings,0);assert.equal(scene.geometries.filter(g=>g.id.startsWith('architecture-art-')).length,0);}finally{r.close();}});
test('M existing owner restores on root drift; no recipe replay or extra allocations',()=>{const r=productionWorldRig(Current,160,100);try{r.world.draw(createState('truce'),0,false,[]);const scene=r.world.engine.scenes[0],root=scene.getTransformNodeByName('kingdom-truce'),m=root.getChildMeshes().find(m=>m.name==='truce-pitched-roof'),owned=m.geometry;root.name='held-home';scene.onBeforeRenderObservable.notifyObservers(scene);assert.notEqual(m.geometry,owned);assert(owned.isDisposed());assert.equal(r.world.inspect().productionArt.architecture.bindings,0);assert.equal(r.world.inspect().productionArt.architecture.rejections,1);scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(r.world.inspect().productionArt.architecture.roofPartsAuthored,44);}finally{r.close();}});
test('M external replacement geometry is not overwritten at release',()=>{const r=productionWorldRig(Current,160,100);try{r.world.draw(createState('truce'),0,false,[]);const scene=r.world.engine.scenes[0],m=scene.meshes.find(m=>m.name==='truce-roof-course'),replacement=m.geometry.copy('external-roof');replacement.applyToMesh(m);scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(m.geometry,replacement);assert(!replacement.isDisposed());assert.equal(r.world.inspect().productionArt.architecture.bindings,0);}finally{r.close();}});
test('M actual roof models and exported pure-author arrays agree',async()=>{const out=mkdtempSync(join(tmpdir(),'roof-m-')),r=productionWorldRig(Current,160,100);try{const mf=await exportProductionRoof(out),bytes=readFileSync(join(out,'roof-models.json')),models=JSON.parse(bytes).models;assert.equal(sha(bytes),mf.modelSha256);assert.equal(mf.modelCount,44);assert.equal(mf.nativeEvidence,false);r.world.draw(createState('truce'),0,false,[]);const scene=r.world.engine.scenes[0];for(const e of models){const matches=scene.meshes.filter(m=>m.name===e.name&&m.position.asArray().every((v,i)=>Math.abs(v-e.position[i])<1e-8));assert.equal(matches.length,1);const m=matches[0];for(const [key,expected]of [['position',e.positions],['normal',e.normals],['uv',e.uvs]]){const actual=m.getVerticesData(key);assert.equal(actual.length,expected.length);for(let i=0;i<actual.length;i++)assert(Math.abs(actual[i]-expected[i])<1e-5,key);}assert.deepEqual(Array.from(m.getIndices()),e.indices);}}finally{r.close();rmSync(out,{recursive:true,force:true});}});
