/** Actual application geometry/CPU tests, OFFLINE only; no browser state or native evidence mutation. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {MeshBuilder,StandardMaterial,TransformNode,Vector3,Ray,DynamicTexture} from '@babylonjs/core';
import {ArtDirectedWorld as Current} from '../.test/sightline-j-world.mjs';import {ArtDirectedWorld as Prior} from '../.test/sightline-i-world.mjs';
import {installProductionSightlines} from '../.test/production-sightline-finish.mjs';import {sculptInnSign,sculptCourtDais,SIGHTLINE_ART} from '../.test/production-sightline-art.mjs';
import {createState} from '../.test/cpu-entry.mjs';import {productionWorldRig} from './helpers/production-world-rig.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
const fixture=JSON.parse(readFileSync('tests/fixtures/ci106-sightline-observations.json'));
const shape=m=>({positions:Array.from(m.getVerticesData('position')??[]),normals:Array.from(m.getVerticesData('normal')??[]),uv:Array.from(m.getVerticesData('uv')??[]),indices:Array.from(m.getIndices()??[])});
function observe(Type,ch,aspect=[300,200],native=false){const r=productionWorldRig(Type,...aspect);try{const s=native?structuredClone(fixture.observations[ch].state):createState(ch),copy=structuredClone(s);r.world.draw(s,0,false,[]);assert.deepEqual(s,copy);const sc=r.world.engine.scenes[0],c=sc.activeCamera;return {frame:sha(r.canvas.pixels()),meshes:sc.meshes.map(m=>({name:m.name,position:m.position.asArray(),rotation:m.rotation.asArray(),scale:m.scaling.asArray(),billboard:m.billboardMode,shape:m.geometry?shape(m):null})),textures:sc.textures.filter(t=>t instanceof DynamicTexture).map(t=>[t.name,sha(t.getContext().getImageData(0,0,t.getSize().width,t.getSize().height).data)]),camera:[c.position.asArray(),c.orthoTop,c.orthoBottom,c.orthoLeft,c.orthoRight],v:r.world.inspect()};}finally{r.close();}}
test('J authored sign preserves 2:1 artwork and dais retains original X/Y and winding inputs',()=>{const a=[-.7,-.35,0,.7,-.35,0,.7,.35,0,-.7,.35,0],copy=[...a],b=sculptInnSign(a);assert.deepEqual(a,copy);assert.equal(b[0],-.7*.66);assert.equal(b[1],-.35*.66);const d=sculptCourtDais(a.map((n,i)=>i%3===2?4:n));for(let i=0;i<a.length;i++)assert.equal(d[i],i%3===2?2.8:a[i]);assert.equal(SIGHTLINE_ART.addedTextures,0);});
for(const bad of [[],[NaN,1,2],[Infinity,0,0],Array(11).fill(0)])test('J rejects malformed author positions '+bad.length+'/'+bad[0],()=>{assert.throws(()=>sculptInnSign(bad));assert.throws(()=>sculptCourtDais(bad));});
for(const [ch,count]of [['truce',1],['courtroom',3]])for(const native of[false,true])test('J actual '+ch+(native?' CI106 observed position':' default')+' changes only selected private geometry',()=>{const a=observe(Current,ch,[300,200],native),b=observe(Prior,ch,[300,200],native);assert.notEqual(a.frame,b.frame);assert.deepEqual(a.textures,b.textures);assert.deepEqual(a.camera,b.camera);assert.equal(a.meshes.length,b.meshes.length);let changed=0;
 for(let i=0;i<a.meshes.length;i++){const{shape:sa,...ma}=a.meshes[i],{shape:sb,...mb}=b.meshes[i];assert.deepEqual(ma,mb);if(JSON.stringify(sa)!==JSON.stringify(sb)){changed++;assert(['inn-sign','court-curved-dais'].includes(ma.name));assert.deepEqual(sa.uv,sb.uv);assert.deepEqual(sa.indices,sb.indices);for(let j=0;j<sa.normals.length;j+=3)assert(Math.abs(Math.hypot(...sa.normals.slice(j,j+3))-1)<1e-5);}}
 assert.equal(changed,count);assert.equal(a.v.productionArt.sightlines.bindings,count);assert.equal(a.v.renderer.cpu.unsupportedResources,0);assert(a.v.renderer.cpu.textureMemory.bytes<33554432);
 for(const k of['grounding','partyCombat','combatTiming','poses','guest','actorPlayback'])assert.deepEqual(a.v[k],b.v[k],k);
 const sa=structuredClone(a.v.storyNpcs),sb=structuredClone(b.v.storyNpcs);if(ch==='truce'){const ap=sa.kingdom.village.details.sign.projection,bp=sb.kingdom.village.details.sign.projection;assert(Math.abs(ap.rect.width/bp.rect.width-.66)<1e-5);assert(Math.abs(ap.rect.height/bp.rect.height-.66)<1e-5);delete sa.kingdom.village.details.sign.projection;delete sb.kingdom.village.details.sign.projection;}assert.deepEqual(sa,sb);
});
for(const ch of ['bedroom','downstairs','home','fair','canyon','forest','castle','chamber','cathedral','passage','sanctum','overworld1000','guardia1000','hall1000','cellblock','futuregate'])test('J non-target/held '+ch+' retains complete predecessor CPU frame',()=>{assert.equal(observe(Current,ch,[144,96]).frame,observe(Prior,ch,[144,96]).frame);});
test('J scene cache owns only four clones, preserves original buffers and releases all retained geometry',()=>{const r=productionWorldRig(Prior,144,96);try{const sc=r.world.engine.scenes[0];for(const ch of['truce','courtroom','home'])r.world.draw(createState(ch),0,false,[]);const orig=sc.meshes.filter(m=>['inn-sign','court-curved-dais'].includes(m.name)).map(m=>({m,g:m.geometry,s:shape(m)})),counts=[sc.geometries.length,sc.meshes.length,sc.textures.length,sc.materials.length],pass=installProductionSightlines(sc);
 for(let i=0;i<4;i++)for(const ch of['truce','courtroom','home'])r.world.draw(createState(ch),0,false,[]);assert.equal(pass.inspect().bindings,4);assert.equal(pass.inspect().authored,4);assert.equal(pass.inspect().geometryBytes,15512);assert.equal(sc.geometries.length,counts[0]+4);assert.deepEqual([sc.meshes.length,sc.textures.length,sc.materials.length],counts.slice(1));
 for(const p of orig){assert.notEqual(p.m.geometry,p.g);assert.deepEqual(Array.from(p.g.getVerticesData('position')),p.s.positions);assert.deepEqual(Array.from(p.g.getVerticesData('uv')),p.s.uv);}pass.dispose();pass.dispose();assert.equal(sc.geometries.length,counts[0]);for(const p of orig){assert.equal(p.m.geometry,p.g);assert.deepEqual(shape(p.m),p.s);}assert.equal(pass.inspect().geometryBytes,0);
 }finally{r.close();}});
for(const ch of['truce','courtroom'])test('J '+ch+' root disposal frees clones and scene disposal clears counters',()=>{const r=productionWorldRig(Current,144,96);try{r.world.draw(createState(ch),0,false,[]);const sc=r.world.engine.scenes[0];sc.getTransformNodeByName(ch==='truce'?'kingdom-truce':'trial-courtroom').dispose();assert.equal(r.world.inspectProductionArt().sightlines.bindings,0);assert.equal(sc.geometries.filter(g=>g.id.startsWith('sightline-art-')).length,0);r.world.engine.dispose();assert(r.world.inspectProductionArt().sightlines.disposed);}finally{r.close();}});
for(const kind of ['material','geometry','position','rotation','scale','parent','name','root-transform','billboard'])test('J '+kind+' drift restores only its own geometry and preserves replacement properties',()=>{const r=productionWorldRig(Prior,144,96);try{r.world.draw(createState('truce'),0,false,[]);const sc=r.world.engine.scenes[0],m=sc.getMeshByName('inn-sign'),original=m.geometry,root=m.parent,pass=installProductionSightlines(sc);sc.onBeforeRenderObservable.notifyObservers(sc);assert.equal(pass.inspect().bindings,1);let replacement;
 if(kind==='material')m.material=replacement=new StandardMaterial('external',sc);else if(kind==='geometry'){replacement=m.geometry.copy('external');replacement.applyToMesh(m);}else if(kind==='position')m.position.x+=.25;else if(kind==='rotation')m.rotation.z=.1;else if(kind==='scale')m.scaling.y=3;else if(kind==='parent')m.parent=replacement=new TransformNode('external',sc);else if(kind==='name')m.name='external';else if(kind==='billboard')m.billboardMode=0;else root.position.x=1;
 const values=[m.material,m.position.asArray(),m.rotation.asArray(),m.scaling.asArray(),m.parent,m.name,m.billboardMode,root.position.asArray()];sc.onBeforeRenderObservable.notifyObservers(sc);assert.equal(pass.inspect().bindings,0);assert.equal(pass.inspect().rejections,1);assert.deepEqual([m.material,m.position.asArray(),m.rotation.asArray(),m.scaling.asArray(),m.parent,m.name,m.billboardMode,root.position.asArray()],values);assert.equal(m.geometry,kind==='geometry'?replacement:original);sc.onBeforeRenderObservable.notifyObservers(sc);assert.equal(pass.inspect().bindings,0);pass.dispose();}finally{r.close();}});
for(const kind of['positions','normals','uv','indices','shared','duplicate','missing','material','root'])test('J refuses unknown '+kind+' cylinder source without allocations',()=>{const r=productionWorldRig(Prior,144,96);try{r.world.draw(createState('courtroom'),0,false,[]);const sc=r.world.engine.scenes[0],m=sc.getMeshByName('court-curved-dais'),root=m.parent;if(['positions','normals','uv'].includes(kind)){const key=kind==='positions'?'position':kind==='normals'?'normal':'uv',v=Array.from(m.getVerticesData(key));v[0]+=.01;m.setVerticesData(key,v,false);}else if(kind==='indices'){const v=Array.from(m.getIndices());[v[0],v[1]]=[v[1],v[0]];m.setIndices(v);}else if(kind==='shared')m.geometry.applyToMesh(MeshBuilder.CreateBox('unrelated',{},sc));else if(kind==='duplicate'){const n=m.clone('court-curved-dais');n.parent=root;}else if(kind==='missing')m.dispose();else if(kind==='material')m.material=new StandardMaterial('unknown',sc);else root.scaling.y=.5;
 // Let existing owner passes process the altered root before isolating J allocations.
 sc.onBeforeRenderObservable.notifyObservers(sc);const counts=[sc.geometries.length,sc.meshes.length,sc.textures.length],pass=installProductionSightlines(sc);sc.onBeforeRenderObservable.notifyObservers(sc);assert.equal(pass.inspect().bindings,0);assert.deepEqual([sc.geometries.length,sc.meshes.length,sc.textures.length],counts);pass.dispose();}finally{r.close();}});
test('J exact CI106 court state retreats the projected dais front without moving actor or adding head/chest blockers',()=>{function rays(Type){const r=productionWorldRig(Type,300,200);try{const state=structuredClone(fixture.observations.courtroom.state);r.world.draw(state,0,false,[]);const sc=r.world.engine.scenes[0],m=sc.getMeshByName('player-0'),direction=sc.activeCamera.getDirection(Vector3.Forward()).normalize();let blocked=0;for(const x of[-.25,0,.25])for(let i=0;i<17;i++){const end=Vector3.TransformCoordinates(new Vector3(x,-.6+i*.075,0),m.computeWorldMatrix(true)),ray=new Ray(end.subtract(direction.scale(64)),direction,63.98);if(sc.meshes.filter(g=>g.name==='court-curved-dais').some(g=>{const hit=ray.intersectsMesh(g,false);return hit.hit&&hit.distance>0&&hit.distance<ray.length;}))blocked++;}const viewport=sc.activeCamera.viewport.toGlobal(r.canvas.canvas.width,r.canvas.canvas.height),project=g=>{const p=g.getVerticesData('position'),out=[];for(let i=0;i<p.length;i+=3)out.push(Vector3.Project(new Vector3(p[i],p[i+1],p[i+2]),g.computeWorldMatrix(true),sc.getTransformMatrix(),viewport).y);return out;};return{blocked,frontY:Math.max(...sc.meshes.filter(g=>g.name==='court-curved-dais').flatMap(project)),actorY:project(m),position:m.position.asArray(),grounding:r.world.inspect().grounding};}finally{r.close();}}const a=rays(Current),b=rays(Prior);assert(a.blocked<=b.blocked);assert(a.frontY<b.frontY-5);assert.deepEqual(a.actorY,b.actorY);assert.deepEqual(a.position,b.position);assert.deepEqual(a.grounding,b.grounding);});
test('J dead scene is rejected',()=>{assert.throws(()=>installProductionSightlines({isDisposed:true}));});

for(const kind of['uv','shared-material','shared-geometry','duplicate-root'])test('J refuses unknown inn sign '+kind+' without side effects',()=>{const r=productionWorldRig(Prior,144,96);try{r.world.draw(createState('truce'),0,false,[]);const sc=r.world.engine.scenes[0],m=sc.getMeshByName('inn-sign');if(kind==='uv'){const uv=Array.from(m.getVerticesData('uv'));uv[0]+=.1;m.setVerticesData('uv',uv,false);}else if(kind==='shared-material')MeshBuilder.CreateBox('other',{},sc).material=m.material;else if(kind==='shared-geometry')m.geometry.applyToMesh(MeshBuilder.CreateBox('other',{},sc));else new TransformNode('kingdom-truce',sc);sc.onBeforeRenderObservable.notifyObservers(sc);const before=sc.geometries.length,pass=installProductionSightlines(sc);sc.onBeforeRenderObservable.notifyObservers(sc);assert.equal(pass.inspect().bindings,0);assert.equal(sc.geometries.length,before);pass.dispose();}finally{r.close();}});
