/** Real owned uploads and whole-application OFFLINE framebuffer tests. No browser hooks. */
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';import {inflateSync} from 'node:zlib';
import {DynamicTexture,MeshBuilder,StandardMaterial,TransformNode,Texture} from '@babylonjs/core';
import {World,createState} from '../.test/cpu-entry.mjs';import {ArtDirectedWorld as Current} from '../.test/art-directed-world.mjs';import {ArtDirectedWorld as Prior} from '../.test/art-directed-world-f.mjs';
import {installProductionStoryNpcs} from '../.test/production-story-npc-finish.mjs';import {legacyStoryNpcCell,storyNpcProductionCell} from '../.test/production-story-npc-art.mjs';import {productionWorldRig} from './helpers/production-world-rig.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');const roles=[['townsperson','kingdom-truce','truce','resident'],['innkeeper','kingdom-truce','truce','innkeeper'],['king','kingdom-castle','castle','king'],['guard','kingdom-castle','castle','guard'],['disguised-nun','cathedral-set','cathedral','nun'],['false-chancellor','sanctum-set','sanctum','chancellor'],['true-chancellor','sanctum-set','sanctum','chancellor'],['queen-leene','sanctum-set','sanctum','queen']];
function bytes(t){return new Uint8ClampedArray(t.getContext().getImageData(0,0,48,64).data);}
function write(t,data){const c=t.getContext(),im=c.createImageData(48,64);im.data.set(data);c.putImageData(im,0,0);}
function fixture(row){const r=productionWorldRig(World),scene=r.world.engine.scenes[0];for(const m of scene.meshes)m.setEnabled(false);const root=new TransformNode(row[1],scene),mesh=MeshBuilder.CreatePlane(row[0],{},scene),mat=new StandardMaterial('G-owned',scene),t=new DynamicTexture('G-owned',{width:48,height:64},scene,false,Texture.NEAREST_SAMPLINGMODE);mesh.parent=root;mesh.material=mat;mat.diffuseTexture=t;let selection={facing:0,pose:'ambient'},uploads=0,uploaded,args,ctx,throws=false;const original=t.update,sentinel={original:true};t.update=function(...p){uploads++;uploaded=bytes(t);args=p;ctx=this;if(throws)throw sentinel;original.apply(this,p);return sentinel;};const upload=t.update;
 const pass=installProductionStoryNpcs(scene,()=>selection),notify=()=>scene.onBeforeRenderObservable.notifyObservers(scene);write(t,legacyStoryNpcCell(row[3],0));pass.begin(row[2]);notify();return {...r,scene,root,mesh,mat,t,pass,notify,select:p=>{selection=p;},count:()=>uploads,uploaded:()=>uploaded,args:()=>args,ctx:()=>ctx,sentinel,upload,throwUpload:()=>{throws=true;}};}
for(const row of roles)test('G '+row[0]+' all 32 ambient/greet cells reach the owned upload with actual author bytes and original semantics',()=>{const r=fixture(row);try{for(let f=0;f<4;f++)for(const pose of ['ambient','greet'])for(let d=0;d<4;d++){r.select({facing:d,pose});write(r.t,legacyStoryNpcCell(row[3],f));const n=r.count();assert.equal(r.t.update(false,false),r.sentinel);assert.equal(r.count(),n+1);assert.deepEqual(r.args(),[false,false]);assert.equal(r.ctx(),r.t);const expected=storyNpcProductionCell(row[3],f,d,pose);assert.deepEqual(bytes(r.t),expected);assert.deepEqual(r.uploaded(),expected);const p=r.pass.inspect().actors[0];assert.equal(p.frame,f);assert.equal(p.facing,d);assert.equal(p.pose,pose);}const n=r.count();for(let i=0;i<12;i++)r.notify();assert.equal(r.count(),n);assert.equal(r.pass.inspect().additionalGpuTextures,0);assert(r.pass.inspect().retainedCpuBytes<=24576);}finally{r.close();}});
test('G direction changes at a held source frame upload once; unknown pixels remain untouched',()=>{const r=fixture(roles[0]);try{const n=r.count();r.select({facing:1,pose:'greet'});r.notify();assert.equal(r.count(),n+1);assert.deepEqual(bytes(r.t),storyNpcProductionCell('resident',0,1,'greet'));r.notify();assert.equal(r.count(),n+1);const unknown=new Uint8ClampedArray(12288).fill(127);write(r.t,unknown);r.t.update();r.select({facing:2,pose:'greet'});r.notify();assert.deepEqual(bytes(r.t),unknown);assert.equal(r.pass.inspect().actors[0].styled,false);}finally{r.close();}});
test('G malformed pose provider fails to front ambient; original upload exception is not swallowed',()=>{const r=fixture(roles[0]);try{for(const p of [null,{facing:9,pose:'greet'},{facing:1,pose:'walk'},{facing:NaN,pose:'greet'}]){r.select(p);r.notify();assert.deepEqual(bytes(r.t),storyNpcProductionCell('resident',0));}r.throwUpload();assert.throws(()=>r.t.update(),e=>e===r.sentinel);}finally{r.close();}});
test('G held return restores true raw cells, then re-entry selects real pixels; renamed/borrowed sources release safely',()=>{const r=fixture(roles[0]);try{r.select({facing:3,pose:'greet'});r.notify();r.pass.begin('home');assert.deepEqual(bytes(r.t),legacyStoryNpcCell('resident',0));r.pass.begin('truce');r.notify();assert.deepEqual(bytes(r.t),storyNpcProductionCell('resident',0,3,'greet'));r.mesh.name='mother';r.notify();assert.equal(r.pass.inspect().bindings,0);assert.equal(r.t.update,r.upload);assert.deepEqual(bytes(r.t),legacyStoryNpcCell('resident',0));}finally{r.close();}});
function state(ch){const s=createState(ch);s.kingdom.phase='arrival';if(ch==='cathedral')s.rescue.stage='entered';return s;}
function observed(Type,ch,near=false){const r=productionWorldRig(Type,240,160);try{const s=state(ch);if(near){s.players[0].x=ch==='castle'?-.7:-5.4;s.players[0].z=ch==='castle'?-2.5:-3.3;}const copy=structuredClone(s);r.world.draw(s,0,false,[]);assert.deepEqual(s,copy);const scene=r.world.engine.scenes[0],v=r.world.inspect(),camera=scene.activeCamera;return {frame:sha(r.canvas.pixels()),v,geometry:scene.meshes.map(m=>[m.name,m.position.asArray(),m.rotation.asArray(),m.scaling.asArray(),m.visibility]),textures:scene.textures.filter(t=>t instanceof DynamicTexture&&!['truce-townsperson','truce-innkeeper','castle-guard','castle-king'].includes(t.name)).map(t=>[t.name,sha(t.getContext().getImageData(0,0,t.getSize().width,t.getSize().height).data)]),camera:[camera.position.asArray(),camera.orthoTop,camera.orthoBottom,camera.orthoLeft,camera.orthoRight]};}finally{r.close();}}
for(const [ch,npc] of [['truce','innkeeper'],['castle','guard']])test('G actual '+ch+' application displays new directional/greet pixels without changing existing geometry/camera/non-NPC textures or gameplay',()=>{const f=observed(Prior,ch,true),g=observed(Current,ch,true);assert.notEqual(g.frame,f.frame);assert.deepEqual(g.geometry,f.geometry);assert.deepEqual(g.textures,f.textures);assert.deepEqual(g.camera,f.camera);for(const k of ['partyCombat','fieldEnemyMotion','combatTiming','trialMaps','poses'])assert.deepEqual(g.v[k],f.v[k]);assert.equal(g.v.productionArt.storyNpcs.actors.find(a=>a.name===npc).facing,1);assert.equal(g.v.productionArt.storyNpcs.actors.find(a=>a.name===npc).pose,'greet');assert.equal(g.v.renderer.cpu.unsupportedResources,0);});
for(const ch of ['bedroom','home','downstairs','fair','forest','overworld1000','courtroom','cellblock','hall1000','guardia1000','futuregate'])test('G held/non-target '+ch+' whole framebuffer remains exact F',()=>{assert.equal(observed(Current,ch).frame,observed(Prior,ch).frame);});
test('G current app reduced-motion and restore reuse original frame clock; static draws/re-entry are bounded and dispose clears retention',()=>{const r=productionWorldRig(Current,192,128);try{const s=state('truce');s.players[0].x=-3.4;s.players[0].z=1;s.ticks=100;r.world.draw(s,0,false,[]);const scene=r.world.engine.scenes[0],mesh=scene.getMeshByName('townsperson'),t=mesh.material.diffuseTexture;assert.deepEqual(bytes(t),storyNpcProductionCell('resident',1,1,'greet'));r.media.matches=true;r.world.draw(s,0,false,[]);assert.deepEqual(bytes(t),storyNpcProductionCell('resident',0,1,'greet'));r.media.matches=false;r.world.draw(s,0,false,[]);assert.deepEqual(bytes(t),storyNpcProductionCell('resident',1,1,'greet'));const n=r.world.inspectProductionArt().storyNpcs.redrawnUploads,counts=[scene.meshes.length,scene.textures.length];for(let i=0;i<15;i++)r.world.draw(s,0,false,[]);assert.equal(r.world.inspectProductionArt().storyNpcs.redrawnUploads,n);assert.deepEqual([scene.meshes.length,scene.textures.length],counts);const home=state('home');r.world.draw(home,0,false,[]);assert.equal(r.world.inspectProductionArt().npcAttention.choices.length,0);r.world.draw(s,0,false,[]);r.world.engine.dispose();assert.equal(r.world.inspectProductionArt().storyNpcs.retainedCpuBytes,0);assert.equal(r.world.inspectProductionArt().npcAttention.choices.length,0);}finally{r.close();}});
test('G seven exported PNGs decode to every 224 runtime-eligible author cells, never claim walk/combat activation',async()=>{const {exportNpcAttention}=await import('../scripts/npc-attention-export.mjs'),out='.test/g-export-check',m=await exportNpcAttention(out);assert.equal(m.assets.length,7);assert.equal(m.runtimeEligibleNpcCellSlots,224);assert.equal(m.stagedNpcWalkCellSlots,112);assert.equal(m.runtimeCombatCellSlots,0);assert.equal(m.nativeEvidence,false);let count=0;for(const a of m.assets){const z=readFileSync(out+'/'+a.file);assert.equal(sha(z),a.pngSha256);let at=8;const parts=[];while(at<z.length){const n=z.readUInt32BE(at);if(z.toString('ascii',at+4,at+8)==='IDAT')parts.push(z.subarray(at+8,at+8+n));at+=n+12;}const rows=inflateSync(Buffer.concat(parts)),stride=a.width*4,pix=Buffer.alloc(a.width*a.height*4);for(let y=0;y<a.height;y++){assert.equal(rows[y*(stride+1)],0);rows.copy(pix,y*stride,y*(stride+1)+1,(y+1)*(stride+1));}assert.equal(sha(pix),a.rgbaSha256);for(const c of a.cells){count++;const expected=storyNpcProductionCell(a.kind,c.frame,c.facing,c.pose);assert.equal(c.rgbaSha256,sha(expected));assert(c.runtimeEligible);assert.deepEqual(c.pivot,[24,63]);for(let y=0;y<64;y++)assert.deepEqual(pix.subarray(((c.y+y)*768+c.x)*4,((c.y+y)*768+c.x+48)*4),Buffer.from(expected.subarray(y*192,(y+1)*192)));}}assert.equal(count,224);});
