/** Offline application/framebuffer tests. No local browser or native State injection. */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';import {inflateSync} from 'node:zlib';
import {DynamicTexture,TransformNode,VertexBuffer} from '@babylonjs/core';
import {ArtDirectedWorld as Current} from '../.test/grove-l-world.mjs';import {ArtDirectedWorld as Prior} from '../.test/grove-k-world.mjs';import {GROVE_ART,paintGroveSurface} from '../.test/grove-l-art.mjs';import {installProductionGrove} from '../.test/grove-l-finish.mjs';import {createState} from '../.test/cpu-entry.mjs';import {productionWorldRig} from './helpers/production-world-rig.mjs';import {assertTownSignOcclusion} from '../scripts/town-route-evidence.mjs';import {exportProductionGrove} from '../scripts/production-grove-export.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex'),fixture=JSON.parse(readFileSync('tests/fixtures/ci108-grove-stops.json'));
function meshRecord(m){return {name:m.name,position:m.position.asArray(),rotation:m.rotation.asArray(),scale:m.scaling.asArray(),material:m.material?.name,vertices:Array.from(m.getVerticesData('position')??[]),uv:Array.from(m.getVerticesData('uv')??[]),indices:Array.from(m.getIndices()??[])};}
function observe(Type,state,width=240,height=160){const r=productionWorldRig(Type,width,height);try{const s=structuredClone(state),before=structuredClone(s);for(let i=0;i<3;i++)r.world.draw(s,0,false,[]);assert.deepEqual(s,before);const scene=r.world.engine.scenes[0];return {frame:sha(r.canvas.pixels()),inspection:r.world.inspect(),meshes:scene.meshes.filter(m=>!m.name.startsWith('grove-art-')).map(meshRecord),textures:scene.textures.filter(t=>t instanceof DynamicTexture&&!t.name.startsWith('grove-art-')).map(t=>[t.name,sha(t.getContext().getImageData(0,0,t.getSize().width,t.getSize().height).data)])};}finally{r.close();}}
for(const kind of ['fern-fronds','root-moss'])test('L author '+kind+' has four distinct integer-pixel cells and transparent gutters',()=>{const p=paintGroveSurface(kind),q=paintGroveSurface(kind);assert.deepEqual(p,q);assert.equal(p.width,256);assert.equal(p.height,64);assert.equal(p.rgba.length,65536);const cells=[];
 for(let k=0;k<4;k++){const cell=[];let opaque=0;for(let y=0;y<64;y++)for(let x=0;x<64;x++){const i=(y*256+k*64+x)*4,a=p.rgba[i+3];assert([0,255].includes(a));if(x<3||x>60||y<3||y>60)assert.equal(a,0);if(a)opaque++;cell.push(...p.rgba.slice(i,i+4));}assert(opaque>150&&opaque<2500);cells.push(sha(Buffer.from(cell)));}assert.equal(new Set(cells).size,4);p.rgba.fill(0);assert.deepEqual(q,paintGroveSurface(kind));});
for(const kind of ['unknown',null,'__proto__'])test('L rejects unknown authored surface '+kind,()=>assert.throws(()=>paintGroveSurface(kind)));
for(const chapter of ['truce','forest'])test('L actual '+chapter+' adds rooted vegetation without changing original pixels/models/camera or State',()=>{const s=createState(chapter),a=observe(Current,s),b=observe(Prior,s);assert.notEqual(a.frame,b.frame);assert.deepEqual(a.meshes,b.meshes);assert.deepEqual(a.textures,b.textures);assert.equal(a.inspection.renderer.cpu.unsupportedResources,0);const g=a.inspection.productionArt.grove;assert.equal(g.addedMeshes,chapter==='truce'?8:24);assert.equal(g.textureCount,2);assert.equal(g.textureBytes,GROVE_ART.maxTextureBytes);assert.equal(g.uploads,2);for(const k of ['partyCombat','actorPlayback','poses','guest','grounding','combatTiming','earlyCamera'])assert.deepEqual(a.inspection[k],b.inspection[k],k);});
for(const ch of ['bedroom','downstairs','home','fair','canyon','castle','chamber','cathedral','passage','sanctum','courtroom','cell','prison','bridge','future'])test('L '+ch+' held/non-target full frame unchanged',()=>{const a=observe(Current,createState(ch),160,100),b=observe(Prior,createState(ch),160,100);assert.equal(a.frame,b.frame);assert.deepEqual(a.meshes,b.meshes);assert.deepEqual(a.textures,b.textures);assert.equal(a.inspection.productionArt.grove.textureCount,0);});
for(const stop of fixture.stops)test('L actual original CI108 '+stop.name+' inn-ray contract remains truthful',()=>{const a=observe(Current,stop.state,208,450),b=observe(Prior,stop.state,208,450);assertTownSignOcclusion(a.inspection.townSignOcclusion,stop.state);assert.deepEqual(a.inspection.townSignOcclusion,b.inspection.townSignOcclusion);assert.deepEqual(a.textures,b.textures);});
test('L repeated map transitions have bounded assets and owner disposal releases everything',()=>{const r=productionWorldRig(Current,160,100);try{for(let i=0;i<8;i++)for(const ch of ['truce','forest','home'])r.world.draw(createState(ch),0,false,[]);const scene=r.world.engine.scenes[0],g=r.world.inspect().productionArt.grove;assert.equal(g.roots,2);assert.equal(g.addedMeshes,32);assert.equal(g.textureCount,2);assert.equal(g.uploads,2);assert(g.maps.every(m=>!m.visible));for(const n of ['kingdom-truce','kingdom-forest'])scene.getTransformNodeByName(n).dispose();const empty=r.world.inspect().productionArt.grove;assert.equal(empty.roots,0);assert.equal(empty.addedMeshes,0);assert.equal(empty.textureBytes,0);assert.equal(scene.meshes.filter(m=>m.name.startsWith('grove-art-')).length,0);assert.equal(scene.materials.filter(m=>m.name.startsWith('grove-art-')).length,0);}finally{r.close();}});
for(const defect of ['missing-tree','wrong-root','moved-root','duplicate-root','tree-size','tree-uv','tree-texture'])test('L admission fails closed for '+defect,()=>{const r=productionWorldRig(Prior,160,100);try{const s=createState('truce');r.world.draw(s,0,false,[]);const scene=r.world.engine.scenes[0],root=scene.getTransformNodeByName('kingdom-truce'),tree=root.getChildMeshes().find(m=>m.name==='oak');
 if(defect==='missing-tree')tree.dispose();if(defect==='wrong-root')root.name='held-home';if(defect==='moved-root')root.position.x=1;if(defect==='duplicate-root')new TransformNode(root.name,scene);if(defect==='tree-size')tree.scaling.x=2;if(defect==='tree-uv'){const uv=Array.from(tree.getVerticesData('uv'));uv[0]+=.1;tree.setVerticesData('uv',uv,false);}if(defect==='tree-texture')tree.material.diffuseTexture=null;
 const pass=installProductionGrove(scene);scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(pass.inspect().roots,0);assert.equal(pass.inspect().textureCount,0);pass.dispose();}finally{r.close();}});
test('L drift releases only owned vegetation, never restores over the original tree owner',()=>{const r=productionWorldRig(Prior,160,100);try{const s=createState('forest');r.world.draw(s,0,false,[]);const scene=r.world.engine.scenes[0],pass=installProductionGrove(scene);scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(pass.inspect().addedMeshes,24);const root=scene.getTransformNodeByName('kingdom-forest'),tree=root.getChildMeshes().find(m=>m.name==='oak'),geometry=tree.geometry;tree.position.x+=.25;scene.onBeforeRenderObservable.notifyObservers(scene);assert.equal(pass.inspect().addedMeshes,0);assert.equal(pass.inspect().rejections,1);assert.equal(tree.geometry,geometry);pass.dispose();pass.dispose();}finally{r.close();}});
test('L installed vegetation is nearest-sampled, alpha-tested, not pickable and outside the main path',()=>{const r=productionWorldRig(Current,192,128);try{r.world.draw(createState('forest'),0,false,[]);const scene=r.world.engine.scenes[0],meshes=scene.meshes.filter(m=>m.name.startsWith('grove-art-'));assert.equal(meshes.length,24);for(const m of meshes){assert(Math.abs(m.position.x)>5);assert.equal(m.isPickable,false);assert.equal(m.checkCollisions,false);assert.equal(m.material.diffuseTexture.samplingMode,1);assert.equal(m.material.diffuseTexture,m.material.emissiveTexture);assert(m.getVerticesData(VertexBuffer.UVKind).every(v=>v>=0&&v<=1));}const stats=r.world.inspect().productionArt.grove;r.world.draw(createState('forest'),0,false,[]);assert.equal(r.world.inspect().productionArt.grove.uploads,stats.uploads);}finally{r.close();}});
test('L PNG output is the exact renderer author RGBA, including all transparent cell gutters',async()=>{const out=mkdtempSync(join(tmpdir(),'grove-l-'));try{const manifest=await exportProductionGrove(out);assert.equal(manifest.nativeEvidence,false);for(const a of manifest.assets){const raw=readFileSync(join(out,a.file));assert.equal(sha(raw),a.pngSha256);let offset=8,idat=[];while(offset<raw.length){const len=raw.readUInt32BE(offset),type=raw.toString('ascii',offset+4,offset+8);if(type==='IDAT')idat.push(raw.subarray(offset+8,offset+8+len));offset+=len+12;}const decoded=inflateSync(Buffer.concat(idat)),p=paintGroveSurface(a.kind),rgba=Buffer.alloc(p.rgba.length);for(let y=0;y<p.height;y++){assert.equal(decoded[y*(p.width*4+1)],0);decoded.copy(rgba,y*p.width*4,y*(p.width*4+1)+1,(y+1)*(p.width*4+1));}assert.deepEqual(rgba,Buffer.from(p.rgba));assert.equal(sha(rgba),a.rgbaSha256);}}finally{rmSync(out,{recursive:true,force:true});}});
