import test from 'node:test';
import assert from 'node:assert/strict';
import * as c from '../.test/core.mjs';
import * as p from '../.test/prologue-data.mjs';
import {InputBoundary} from '../.test/input-boundary.mjs';
import {surface} from '../scripts/asset-export.mjs';
import {drawRoomFloor,drawRegionalMap} from '../.test/prologue-art.mjs';
const ticks=(s,n,input=c.IDLE)=>{for(let i=0;i<n;i++)c.step(s,input,1/60);};
const awake=()=>{const s=c.createState('bedroom');ticks(s,160);assert.equal(s.prologue.stage,'home');return s;};
const walk=(s,axis,target)=>{const direction=Math.sign(target-s.players[0][axis]),v={x:0,z:0};v[axis]=direction;let n=0;while(direction*(target-s.players[0][axis])>.065&&n++<1500){c.step(s,[v,{x:0,z:0}],1/60);if(s.prologue.transition)break;}assert.ok(n<1500,`blocked ${axis}:${target} in ${s.chapter} at ${JSON.stringify(s.players[0])}`);};
function fair(){const s=awake();walk(s,'x',0);walk(s,'z',-4.1);ticks(s,35);assert.equal(s.chapter,'home');walk(s,'x',0);c.interactPrologue(s,0);walk(s,'z',-4.2);c.interactPrologue(s,0);ticks(s,35);assert.equal(s.chapter,'overworld1000');walk(s,'x',.1);walk(s,'z',5.1);walk(s,'x',2);c.interactPrologue(s,0);ticks(s,35);assert.equal(s.chapter,'fair');assert.equal(s.prologue.stage,'fair');return s;}
function collision(){const s=fair();walk(s,'z',-3.1);walk(s,'x',-3.5);walk(s,'z',-2.2);assert.equal(s.prologue.stage,'collision');return s;}
function company(first='marle'){
 const s=collision();if(first==='marle')c.interactPrologue(s,0);
 walk(s,'z',-2.8);walk(s,'x',-.5);walk(s,'z',-.8);c.interactPrologue(s,0);assert.equal(s.prologue.pendantPicked,true);
 walk(s,'z',-2.8);walk(s,'x',-3.5);walk(s,'z',-2.2);assert.equal(c.interactPrologue(s,0).choice,'return');c.choosePrologue(s,true);assert.equal(c.interactPrologue(s,0).choice,'company');c.choosePrologue(s,true);assert.equal(s.prologue.stage,'companions');return s;
}
const json=s=>JSON.parse(c.serialize(s));
test('new story is solo before meeting; wake uses simulation time, not rendering',()=>{const s=c.createState('bedroom'),before=structuredClone(s.players);assert.equal(c.activeSlot(s,1),false);ticks(s,30,[{x:1,z:1},{x:1,z:1}]);assert.deepEqual(s.players,before);assert.equal(s.prologue.stage,'waking');assert.throws(()=>c.serialize(s));assert.equal(c.beginBattle(s),false);ticks(s,140);assert.equal(s.prologue.stage,'home');});
test('all real home/stair/overworld/fair travel runs via normal movement and interaction',()=>{const s=fair();assert.equal(s.prologue.motherTalked,true);assert.equal(c.activeSlot(s,1),false);assert.deepEqual(s.flags,{won:false,repaired:false,visitedFuture:false});assert.deepEqual(s.fair,{bellHeard:false,gatoWon:false,luccaMet:false,telepodTested:false});});
test('interior furniture, coast and buildings are collision data, not visual-only obstacles',()=>{for(const map of ['bedroom','home'])for(const r of p.HOME_SOLIDS[map])assert.equal(c.walkable(r.x,r.z,map),false);for(const r of p.WORLD_SOLIDS)assert.equal(c.walkable(r.x,r.z,'overworld1000'),false);for(const [x,z] of [[12,0],[0,12],[7,-5],[NaN,0]])assert.equal(c.walkable(x,z,'overworld1000'),false);});
test('world entrances require proximity plus E; no laboratory combat or repair leaks',()=>{const s=awake();assert.equal(c.beginBattle(s),false);assert.equal(c.repair(s),false);assert.equal(c.travel(s),false);s.chapter='overworld1000';Object.assign(s.players[0],{x:0,z:0});assert.equal(c.interactPrologue(s,0),null);assert.equal(c.beginBattle(s),false);Object.assign(s.players[0],{x:2,z:5.1});ticks(s,20);assert.equal(s.chapter,'overworld1000');c.interactPrologue(s,0);assert.ok(s.prologue.transition);assert.throws(()=>c.serialize(s));});
test('transition drains once per boundary; holding input cannot spill into next room',()=>{const s=awake(),b=new InputBoundary(s);walk(s,'x',0);walk(s,'z',-4.1);assert.equal(b.consume(s),true);assert.equal(b.consume(s),false);let input=[{x:1,z:1},{x:1,z:1}];for(let i=0;i<31;i++){c.step(s,input,1/60);if(b.consume(s))input=c.IDLE;}assert.equal(s.chapter,'home');assert.equal(s.players[0].x,4.5);assert.equal(s.players[0].z,2.2);assert.equal(b.consume(s),false);});
test('P2 and the telepod cannot bypass first collision, return and explicit companionship',()=>{const s=collision();s.joined=true;const before=structuredClone(s.prologue);assert.equal(c.interactPrologue(s,1),null);assert.equal(c.interactFair(s,1),null);assert.equal(c.activeSlot(s,1),false);assert.equal(c.beginBattle(s),false);assert.equal(c.beginOpening(s,0),false);assert.equal(c.choosePrologue(s,true),null);assert.deepEqual(s.prologue,before);});
for(const first of ['marle','pendant'])test(`first ${first} preserves order, genuine returned pendant and companionship through v6`,()=>{const s=company(first),d=c.deserialize(c.serialize(s));assert.equal(d.prologue.first,first);assert.equal(d.prologue.pendantReturned,true);assert.equal(c.activeSlot(d,1),true);assert.equal(json(d).version,6);assert.equal(d.prologue.choice,null);assert.equal(d.prologue.transition,null);});
test('return refusal is not a return, invitation refusal is not party membership',()=>{const s=collision();c.interactPrologue(s,0);walk(s,'z',-2.8);walk(s,'x',-.5);walk(s,'z',-.8);c.interactPrologue(s,0);walk(s,'z',-2.8);walk(s,'x',-3.5);walk(s,'z',-2.2);c.interactPrologue(s,0);const before=structuredClone(s.players);ticks(s,60,[{x:1,z:1},{x:1,z:1}]);assert.deepEqual(s.players,before);assert.throws(()=>c.serialize(s));c.choosePrologue(s,false);assert.equal(s.prologue.pendantReturned,false);c.interactPrologue(s,0);c.choosePrologue(s,true);c.interactPrologue(s,0);c.choosePrologue(s,false);assert.equal(s.prologue.stage,'collision');assert.equal(c.activeSlot(s,1),false);assert.equal(c.deserialize(c.serialize(s)).prologue.pendantReturned,true);});
test('world traversal is slower than normal field movement and has no ATB encounters',()=>{const s=awake();s.chapter='overworld1000';s.players.forEach(p=>Object.assign(p,{x:0,z:0}));ticks(s,60,[{x:0,z:1},{x:0,z:0}]);assert.ok(Math.abs(s.players[0].z-2.4)<.01);assert.equal(s.mode,'explore');assert.equal(s.enemies.length,0);});
test('old v1 and v2 saves remain unchanged with unknown original choice provenance',()=>{for(const map of ['lab','fair']){const s=c.createState(map),raw=c.serialize(s),d=c.deserialize(raw);assert.equal(d.prologue.stage,'legacy');assert.equal(d.prologue.first,'unknown');assert.deepEqual(JSON.parse(c.serialize(d)),JSON.parse(raw));}});
test('v6 inactive P2 distance does not reject a legitimate solo story with coop preset',()=>{const s=collision();s.joined=true;walk(s,'z',-3.6);walk(s,'x',10.3);assert.ok(c.distance(s.players[0],s.players[1])>9);const d=c.deserialize(c.serialize(s));assert.equal(d.joined,true);assert.equal(c.activeSlot(d,1),false);});
test('v6 home/overworld and fair reload same actual position and facts',()=>{for(const s of [awake(),fair(),collision(),company()]){const d=c.deserialize(c.serialize(s));assert.equal(d.chapter,s.chapter);assert.deepEqual(p.prologueSave(d.prologue),p.prologueSave(s.prologue));assert.equal(d.players[0].x,s.players[0].x);assert.equal(d.players[0].z,s.players[0].z);}});
for(const [name,mutate] of [['array stage',o=>o.prologue.stage=['home']],['array first',o=>o.prologue.first=['unknown']],['array chapter',o=>o.chapter=['bedroom']],['made up first',o=>o.prologue.first='innocent'],['pre-earned item',o=>o.prologue.pendantPicked=true],['unplayed return',o=>o.prologue.pendantReturned=true],['coerced bool',o=>o.prologue.checkedMarle=1],['unknown phase',o=>o.prologue.stage='trial'],['wrong era',o=>o.era='middle'],['legacy in v6',o=>o.prologue.stage='legacy'],['solid spawn',o=>o.players[0]={x:3.6,z:1.6,hp:120,mp:18}],['negative hp',o=>o.players[0].hp=-1],['ahead-of-story',o=>o.opening={phase:'vista',canyonWon:true}],['lab flags',o=>o.flags.won=true]])test('v6 rejects '+name,()=>{const o=json(awake());mutate(o);assert.throws(()=>c.deserialize(JSON.stringify(o)));});
test('whitelisted saves do not restore transitions, choices, ATB or injected trial verdicts',()=>{const o=json(awake());o.prologue.choice='company';o.prologue.transition={to:'sanctum'};o.prologue.verdict='innocent';o.players[0].atb=1;const s=c.deserialize(JSON.stringify(o));assert.equal(s.prologue.choice,null);assert.equal(s.prologue.transition,null);assert.equal(s.prologue.verdict,undefined);assert.equal(s.players[0].atb,0);});
test('returning to field and home requires nearby active co-op partner',()=>{const s=company();s.joined=true;Object.assign(s.players[0],{x:0,z:-7.7});Object.assign(s.players[1],{x:0,z:0});c.interactFair(s,0);assert.equal(s.prologue.transition,null);Object.assign(s.players[1],{x:.8,z:-7.2});c.interactFair(s,0);assert.ok(s.prologue.transition);ticks(s,31);assert.equal(s.chapter,'overworld1000');assert.equal(c.activeSlot(s,1),true);assert.equal(c.deserialize(c.serialize(s)).prologue.first,'marle');});
test('v6 crosses into unchanged telepod and canyon with provenance intact',()=>{const s=company();walk(s,'x',-1);walk(s,'z',6.4);c.interactFair(s,0);assert.equal(s.fair.luccaMet,true);walk(s,'x',-2.4);walk(s,'z',8.4);c.interactFair(s,0);assert.equal(s.fair.telepodTested,true);walk(s,'z',6.4);walk(s,'x',0);ticks(s,60);c.interactFair(s,0);ticks(s,400);assert.equal(s.opening.phase,'lost');walk(s,'x',-2.4);walk(s,'z',8.5);c.interactFair(s,0);assert.equal(s.opening.phase,'pendant');const d=c.deserialize(c.serialize(s));assert.equal(d.prologue.first,'marle');assert.equal(d.opening.phase,'pendant');c.interactFair(d,0);ticks(d,90);assert.equal(d.chapter,'canyon');assert.equal(c.activeSlot(d,1),false);assert.equal(c.deserialize(c.serialize(d)).prologue.pendantReturned,true);});
test('new reference-art exports use the same rect-only deterministic painters as runtime',()=>{for(const draw of [drawRoomFloor,drawRegionalMap]){const a=surface(384,352),b=surface(384,352);draw(a.ink,384,352);draw(b.ink,384,352);assert.deepEqual(a.rgba,b.rgba);assert.ok(a.rgba.some(n=>n>0));}});

test('Gato remains optional before Marle; solo ATB win does not fabricate meeting history',()=>{const s=fair();walk(s,'z',-3.6);walk(s,'x',-7);walk(s,'z',3.3);assert.equal(c.interactPrologue(s,0).title,'岡薩雷斯');assert.equal(s.mode,'battle');assert.equal(c.activeSlot(s,1),false);for(let i=0;i<3;i++){ticks(s,150);assert.equal(c.action(s,0,'skill'),true);}assert.equal(s.mode,'victory');c.leaveBattle(s);assert.equal(s.prologue.stage,'fair');assert.equal(s.prologue.first,'unknown');assert.equal(c.deserialize(c.serialize(s)).fair.gatoWon,true);});
