import {nativeBuildYIfDeclared} from './helpers/native-build-y-baseline.mjs';
import {trialUIfDeclared} from './helpers/trial-u-baseline.mjs';
import {rescueBodyTSpec,rescueBodyTBaseline,rescueBodyTIfDeclared} from './helpers/rescue-body-t-baseline.mjs';
/** Explicit offline core/CPU fixtures, never native gameplay or device evidence. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as core from '../.test/core.mjs';
import {World} from '../.test/cpu-entry.mjs';
import {World as PriorWorld} from '../.test/rescue-body-t-prior-world.mjs';
import {RescueEnemyBody,rescueBodyOffset,RESCUE_BODY} from '../.test/rescue-enemy-body.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';
const maps=['cathedral','passage','sanctum'];
const sha=x=>createHash('sha256').update(x).digest('hex');
function seed(chapter='cathedral'){const s=core.createState(chapter);s.era='middle';s.joined=true;s.kingdom={phase:'rescue',heardYear:true,forestWon:true,elapsed:0};s.opening={phase:'vista',canyonWon:true,elapsed:0};s.fair.luccaMet=true;s.fair.telepodTested=true;s.rescue.stage=chapter==='cathedral'?'entered':'allied';s.rescue.organOpen=chapter!=='cathedral';s.rescue.guardsWon=chapter==='sanctum';assert(core.beginBattle(s));return s;}
function rig(width=192,height=128,W=World){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false},doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;const c=cpuTestCanvas(width,height);c.canvas.ownerDocument=doc;const w=new W(c.canvas);return{w,c,media,close(){w.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};}
function draw(k,s,dt=0,animate=false){const effects=s.effects.splice(0),before=structuredClone(s),eb=structuredClone(effects);k.w.draw(s,dt,animate,effects);assert.deepEqual(s,before);assert.deepEqual(effects,eb);return k.w.inspect().rescueEnemyBody;}
function advance(s,n){for(let i=0;i<n;i++)core.step(s,core.IDLE,1/60);}
function actualAttack(s){for(let i=0;i<500;i++){s.effects.length=0;core.step(s,core.IDLE,1/60);if(s.effects.some(e=>e.enemyAction))return s.effects.find(e=>e.enemyAction);}throw Error('No real outgoing attack');}
const sp=(k,s,i=0)=>s.enemies[i].kind==='yakra'?k.w.yakra:k.w.rescueFoes[i];
const pos=(k,s,i=0)=>sp(k,s,i).mesh.position.asArray();
const counts=k=>[k.w.scene.meshes.length,k.w.scene.materials.length,k.w.scene.textures.length];
const pixels=p=>{const d=p.texture.getSize();return Buffer.from(p.texture.getContext().getImageData(0,0,d.width,d.height).data);};
const obs=(k,s)=>({state:structuredClone(s),body:k.w.inspect().rescueEnemyBody});
const save=(name,data)=>{mkdirSync('test-results/rescue-body-offline',{recursive:true});writeFileSync('test-results/rescue-body-offline/'+name+'.json',JSON.stringify(data,null,2));};
for(const kind of ['attack','recoil'])for(const dir of [{x:1,z:0},{x:-1,z:0},{x:0,z:1},{x:0,z:-1}])test(`T pure bounded ${kind} direction ${dir.x}/${dir.z}`,()=>{const n=kind==='attack'?24:18,max=kind==='attack'?.2:.1;for(let t=0;t<=n;t++){const v=rescueBodyOffset(t,kind,dir,false);assert(Math.hypot(v.x,v.z)<=max+1e-12);if(t>0&&t<n){assert.equal(v.x===0?0:Math.sign(v.x),dir.x);assert.equal(v.z===0?0:Math.sign(v.z),dir.z);}else assert.equal(Math.hypot(v.x,v.z),0);assert.deepEqual(rescueBodyOffset(t,kind,dir,true),{x:dir.x*0,z:dir.z*0});}assert(Math.abs(Math.hypot(...Object.values(rescueBodyOffset(n/2,kind,dir,false)))-max)<1e-12);});
for(const chapter of maps){
 test('T actual '+chapter+' attack body follows real source and returns to logical anchor',()=>{const k=rig(),s=seed(chapter);try{s.rescue.guest.hp=0;draw(k,s);const e=actualAttack(s);draw(k,s);const index=e.enemyAction.index,cell=pixels(sp(k,s,index));advance(s,6);let b=draw(k,s);let row=b.history.find(h=>h.phase==='out'&&h.cause.kind==='attack'&&h.offset.z!==0);assert(row);assert.equal(row.cause.tick,e.enemyAction.tick);assert(row.offset.z<0);assert(Math.abs(row.offset.z)<=.2);assert.deepEqual(pixels(sp(k,s,index)),cell);advance(s,8);b=draw(k,s);assert(b.history.some(h=>h.phase==='return'&&h.cause.kind==='attack'));save(chapter+'-attack',obs(k,s));advance(s,30);draw(k,s);assert.equal(pos(k,s,index)[0],s.enemies[index].x);assert.equal(pos(k,s,index)[2],s.enemies[index].z);assert.equal(k.w.inspect().rescueEnemyBody.resources.active,0);}finally{k.close();}});
 test('T '+chapter+' living player hit creates directional recoil without changing S cells',()=>{const k=rig(),s=seed(chapter);try{s.rescue.guest.hp=0;draw(k,s);advance(s,143);s.targets[0]=0;assert(core.action(s,0,'attack'));draw(k,s);const cell=pixels(sp(k,s));advance(s,5);const b=draw(k,s);assert(b.history.some(h=>h.cause.kind==='recoil'&&h.offset.z>0));assert.deepEqual(pixels(sp(k,s)),cell);save(chapter+'-recoil',obs(k,s));advance(s,14);draw(k,s);assert.equal(pos(k,s)[2],s.enemies[0].z);}finally{k.close();}});
 test('T '+chapter+' normal lethal damage hides original immediately and disposes independent remnant',()=>{const k=rig(),s=seed(chapter);try{s.rescue.guest.hp=0;s.enemies[0].hp=30;draw(k,s);const before=counts(k),original=pixels(sp(k,s));s.players[0].atb=1;s.targets[0]=0;assert(core.action(s,0,'attack'));let b=draw(k,s);assert.equal(s.enemies[0].hp,0);assert(!sp(k,s).mesh.isEnabled());assert.equal(b.resources.active,1);assert.deepEqual(pixels(sp(k,s)),original);const peak=counts(k);assert.equal(b.remnants[0].textureUploads,1);const ghost=k.w.scene.textures.find(t=>t.name==='rescue-remnant-0');assert.deepEqual(pixels({texture:ghost}),original);assert.equal(b.resources.rawTextureBytes,original.length);const observations=[obs(k,s)];advance(s,12);b=draw(k,s);assert.equal(b.remnants[0].alpha,.5);assert.equal(b.remnants[0].scale[1],.65);observations.push(obs(k,s));advance(s,12);b=draw(k,s);assert.equal(b.resources.active,0);assert.equal(b.resources.created,b.resources.released);assert.deepEqual(counts(k),peak.map(n=>n-1));observations.push(obs(k,s));advance(s,52);draw(k,s);assert.deepEqual(counts(k),before);save(chapter+'-death',observations);}finally{k.close();}});
}
test('T same simulation tick cannot accumulate body displacement or fade',()=>{const k=rig(),s=seed('sanctum');try{s.rescue.guest.hp=0;draw(k,s);actualAttack(s);draw(k,s);advance(s,6);draw(k,s);const a=pos(k,s),h=k.w.inspect().rescueEnemyBody.history;for(let n=0;n<8;n++)draw(k,s,100,true);assert.deepEqual(pos(k,s),a);assert.deepEqual(k.w.inspect().rescueEnemyBody.history,h);k.media.matches=true;draw(k,s);assert.equal(pos(k,s)[2],s.enemies[0].z);k.media.matches=false;draw(k,s);assert.deepEqual(pos(k,s),a);}finally{k.close();}});
test('T death remnant reduced toggle is reversible, and frozen tick does not consume its lifetime',()=>{const k=rig(),s=seed();try{s.enemies[0].hp=30;draw(k,s);s.players[0].atb=1;s.targets[0]=0;core.action(s,0,'attack');draw(k,s);advance(s,12);const b=draw(k,s);for(let n=0;n<5;n++)draw(k,s,100,true);assert.deepEqual(k.w.inspect().rescueEnemyBody,b);k.media.matches=true;draw(k,s);assert(!k.w.inspect().rescueEnemyBody.remnants[0].enabled);k.media.matches=false;draw(k,s);assert.deepEqual(k.w.inspect().rescueEnemyBody.remnants,b.remnants);}finally{k.close();}});
for(const reset of ['rebase','rewind','chapter','identity','mode','dispose'])test('T '+reset+' releases all own resources without resurrecting a foe',()=>{const k=rig();let s=seed();try{s.ticks=100;s.enemies[0].hp=30;draw(k,s);s.players[0].atb=1;core.action(s,0,'attack');draw(k,s);assert.equal(k.w.inspect().rescueEnemyBody.resources.active,1);const peak=counts(k);if(reset==='rebase')s=structuredClone(s);if(reset==='rewind')s.ticks--;if(reset==='chapter')s.chapter='passage';if(reset==='identity')s.enemies[0]=structuredClone(s.enemies[0]);if(reset==='mode')s.mode='explore';if(reset==='dispose')k.w.rescueEnemyBody.dispose();else{if(s.ticks<0)s.ticks=0;draw(k,s);}assert.equal(k.w.inspect().rescueEnemyBody.resources.active,0);assert.equal(s.enemies[0].hp,0);if(!['chapter','rebase','rewind'].includes(reset))assert.deepEqual(counts(k),peak.map(n=>n-1));assert.equal(k.w.inspect().rescueEnemyBody.resources.created,k.w.inspect().rescueEnemyBody.resources.released);}finally{k.close();}});
test('T first draw at zero HP and reduced death do not invent remnants',()=>{for(const reduced of [true,false]){const k=rig(),s=seed();try{k.media.matches=reduced;s.enemies[0].hp=0;draw(k,s);assert.equal(k.w.inspect().rescueEnemyBody.resources.created,0);s.enemies[1].hp=30;draw(k,s);s.players[0].atb=1;s.targets[0]=1;core.action(s,0,'attack');draw(k,s);assert.equal(k.w.inspect().rescueEnemyBody.resources.created,reduced?0:1);}finally{k.close();}}});
for(const bad of ['future','stale','index','origin','target','actor','guest','kind','nan','dead','outside'])test('T rejects '+bad+' outgoing metadata',()=>{const s=seed();s.rescue.guest.hp=0;const e=structuredClone(actualAttack(s)),c=new RescueEnemyBody();s.effects=[];if(bad==='future')e.enemyAction.tick++;if(bad==='stale')e.enemyAction.tick-=24;if(bad==='index')e.enemyAction.index=3;if(bad==='origin')e.enemyAction.origin.x+=1;if(bad==='target')e.enemyAction.target.z+=1;if(bad==='actor')e.actor=0;if(bad==='guest')e.guest=true;if(bad==='kind')e.kind='heal';if(bad==='nan')e.x=NaN;if(bad==='dead')s.enemies[e.enemyAction.index].hp=0;if(bad==='outside')s.chapter='forest';c.begin(s,false);c.receive(s,e);assert(c.moves.every(x=>x===null));});
test('T ambiguous targets and no-origin combo cannot invent a recoil direction',()=>{const s=seed(),c=new RescueEnemyBody();c.begin(s,false);const e={kind:'combo',x:s.enemies[0].x,z:s.enemies[0].z,text:'offline fixture'};c.receive(s,e);assert(c.moves.every(x=>x===null));Object.assign(s.enemies[1],{x:e.x,z:e.z});c.receive(s,{...e,kind:'hit',actor:0,origin:{x:0,z:-1}});assert(c.moves.every(x=>x===null));});
test('T Yakra multi-target hit is one outgoing body action and duplicate replay does not restart it',()=>{const s=seed('sanctum');let events;for(let i=0;i<1500;i++){s.effects=[];core.step(s,core.IDLE,1/60);if(s.effects.filter(e=>e.enemyAction).length===3){events=s.effects;break;}}assert(events);const c=new RescueEnemyBody();c.begin(s,false);for(const e of events)c.receive(s,e);assert.equal(c.moves.filter(Boolean).length,1);assert.deepEqual(c.moves[0].cause.effect,events[0]);const old=c.moves[0];c.receive(s,events[0]);assert.equal(c.moves[0],old);});
test('T failure during texture copy is explicit and frees the partial allocation',()=>{const k=rig(),s=seed();try{s.enemies[0].hp=30;draw(k,s);const count=counts(k),old=globalThis.document.createElement;globalThis.document.createElement=t=>{const canvas=old(t);if(t==='canvas')canvas.getContext('2d').putImageData=()=>{throw Error('offline allocation/copy fault');};return canvas;};s.players[0].atb=1;core.action(s,0,'attack');draw(k,s);const b=k.w.inspect().rescueEnemyBody;assert.equal(b.resources.creationFailures,1);assert.equal(b.resources.active,0);assert.equal(s.enemies[0].hp,0);assert(!k.w.scene.textures.some(t=>t.name==='rescue-remnant-0'));advance(s,76);draw(k,s);assert.deepEqual(counts(k),count);}finally{k.close();}});
for(const [width,height]of[[192,128],[256,160],[240,180]])test(`T actual CPU pixels have bounded motion and restore exact S ${width}x${height}`,()=>{const a=rig(width,height),b=rig(width,height,PriorWorld);try{const s=seed('sanctum');s.rescue.guest.hp=0;draw(a,s);const p=structuredClone(s);draw(b,p);actualAttack(s);Object.assign(p,structuredClone(s));draw(a,s);draw(b,p);advance(s,6);advance(p,6);draw(a,s);draw(b,p);assert.deepEqual(s,p);assert.notDeepEqual(a.c.pixels(),b.c.pixels());advance(s,30);advance(p,30);draw(a,s);draw(b,p);assert.deepEqual(a.c.pixels(),b.c.pixels());assert.deepEqual(counts(a),counts(b));save('pixels-'+width+'x'+height,{scope:'offline actual CPU triangles,not native',positiveMotionPixels:true,expiredExactS:true,logicalStateUnchanged:true});}finally{b.close();a.close();}});
test('T inspector copies are isolated and history bound is enforced',()=>{const k=rig(),s=seed();try{draw(k,s);for(let i=0;i<40;i++){s.ticks+=20;const e={kind:'hit',actor:0,x:s.enemies[0].x,z:s.enemies[0].z,origin:{x:0,z:-1},text:'offline bound fixture'};s.effects=[e];draw(k,s);}const h=k.w.inspect().rescueEnemyBody;assert.equal(h.history.length,24);assert(h.historyDropped>0);h.history[0].cause.effect.text='changed';assert.notEqual(k.w.inspect().rescueEnemyBody.history[0].cause.effect.text,'changed');assert.equal(RESCUE_BODY.maxTextureBytes,27648);}finally{k.close();}});
for(const chapter of maps)test('T actual CPU '+chapter+' death pixels differ only within remnant lifetime',()=>{const a=rig(),b=rig(192,128,PriorWorld);try{const s=seed(chapter);s.rescue.guest.hp=0;s.enemies[0].hp=30;const p=structuredClone(s);draw(a,s);draw(b,p);s.players[0].atb=p.players[0].atb=1;s.targets[0]=p.targets[0]=0;core.action(s,0,'attack');core.action(p,0,'attack');draw(a,s);draw(b,p);assert.deepEqual(s,p);assert.notDeepEqual(a.c.pixels(),b.c.pixels());assert.deepEqual(counts(a),counts(b).map(n=>n+1));advance(s,12);advance(p,12);draw(a,s);draw(b,p);assert.notDeepEqual(a.c.pixels(),b.c.pixels());advance(s,12);advance(p,12);draw(a,s);draw(b,p);assert.deepEqual(a.c.pixels(),b.c.pixels());assert.deepEqual(counts(a),counts(b));save(chapter+'-death-pixels',{scope:'offline actual CPU rendering,not native',deathPositive:true,halfPositive:true,expiredExactS:true});}finally{b.close();a.close();}});
test('T three same-tick offline ordinary attacks fit the three-slot budget and release once',()=>{const k=rig(),s=seed();try{for(const e of s.enemies)e.hp=1;draw(k,s);const effects=[];for(let i=0;i<3;i++){s.players[0].atb=1;s.targets[0]=i;assert(core.action(s,0,'attack'));effects.push(...s.effects.splice(0));}s.effects=effects;const b=draw(k,s);assert.equal(s.mode,'victory');assert.equal(b.resources.active,3);assert.equal(b.resources.rawTextureBytes,9216);assert(b.remnants.every(g=>g.originalEnabled===false&&g.textureUploads===1));s.ticks+=24;draw(k,s);assert.equal(k.w.inspect().rescueEnemyBody.resources.active,0);assert.equal(k.w.inspect().rescueEnemyBody.resources.released,3);}finally{k.close();}});
test('T real recoil interrupts an outgoing motion without resuming the old attack',()=>{const k=rig(),s=seed();try{s.rescue.guest.hp=0;draw(k,s);actualAttack(s);draw(k,s);advance(s,6);draw(k,s);s.players[0].atb=1;s.targets[0]=0;assert(core.action(s,0,'attack'));draw(k,s);advance(s,5);draw(k,s);const h=k.w.inspect().rescueEnemyBody.history.filter(h=>h.cause.index===0);assert.equal(h.at(-1).cause.kind,'recoil');assert(h.at(-1).offset.z>0);advance(s,19);draw(k,s);assert.equal(pos(k,s)[2],s.enemies[0].z);}finally{k.close();}});
test('T replacing a slot removes its old-source observation instead of reattributing it',()=>{const k=rig(),s=seed();try{s.rescue.guest.hp=0;draw(k,s);actualAttack(s);draw(k,s);assert(k.w.inspect().rescueEnemyBody.history.some(h=>h.cause.index===0));s.enemies[0]=structuredClone(s.enemies[0]);draw(k,s);assert(!k.w.inspect().rescueEnemyBody.history.some(h=>h.cause.index===0));}finally{k.close();}});

for(const name of Object.keys(rescueBodyTSpec.files))test('T exact inverse and missing/duplicate/unrelated rejection '+name,()=>{const raw=trialUIfDeclared(name,readFileSync(name,'utf8')),old=rescueBodyTBaseline(name,raw),e=rescueBodyTSpec.files[name][0];assert.equal(sha(old),rescueBodyTSpec.originalSha256[name]);assert.equal(rescueBodyTIfDeclared(name,old),old);for(const bad of [raw+e.after,raw.replace(e.after,''),raw+'\n// unrelated drift\n'])assert.throws(()=>rescueBodyTBaseline(name,bad));});
test('T original core/rules/saves/art/controllers/input/workflow bytes remain exact S',()=>{for(const [p,h] of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03t-unchanged-inputs.json'))))assert.equal(sha(nativeBuildYIfDeclared(p,readFileSync(p,'utf8'))),h,p);});
