/** Explicit unit/offline fixtures. Only provider browser reports are native evidence. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as core from '../.test/core.mjs';
import * as priorCore from '../.test/rescue-s-prior-core.mjs';
import {World} from '../.test/cpu-entry.mjs';
import {World as PriorWorld} from '../.test/rescue-s-prior-world.mjs';
import {RescueEnemyMotion,rescueEnemyFrame} from '../.test/rescue-enemy-motion.mjs';
import {drawRescueEnemyFrame} from '../.test/rescue-enemy-art.mjs';
import {drawNaga,drawYakra} from '../.test/rescue-art.mjs';
import {surface,png} from '../scripts/asset-export.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';
import {rescueSBaseline,rescueSIfDeclared,rescueSSpec} from './helpers/rescue-s-baseline.mjs';
const kinds=['naga','hench','yakra'],maps=['cathedral','passage','sanctum'];
const sha=x=>createHash('sha256').update(x).digest('hex');
const fnv=data=>{let h=2166136261;for(const v of data)h=Math.imul(h^v,16777619);return h>>>0;};
const golden=JSON.parse(readFileSync('tests/fixtures/rescue-enemy-cells.json'));
function cell(kind,frame){const p=surface(kind==='yakra'?48:24,kind==='yakra'?48:32);drawRescueEnemyFrame(p.ink,kind,frame);return p;}
function seed(chapter='cathedral',C=core){const s=C.createState(chapter);s.era='middle';s.joined=true;s.kingdom={phase:'rescue',heardYear:true,forestWon:true,elapsed:0};s.opening={phase:'vista',canyonWon:true,elapsed:0};s.fair.luccaMet=true;s.fair.telepodTested=true;s.rescue.stage=chapter==='cathedral'?'entered':'allied';s.rescue.organOpen=chapter!=='cathedral';s.rescue.guardsWon=chapter==='sanctum';assert(C.beginBattle(s));return s;}
function rig(width=192,height=128,W=World){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;const c=cpuTestCanvas(width,height);c.canvas.ownerDocument=doc;const w=new W(c.canvas);return{w,c,media,close(){w.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};}
function draw(k,s,dt=0,animate=false){const effects=s.effects.splice(0),before=structuredClone(s),eb=structuredClone(effects);k.w.draw(s,dt,animate,effects);assert.deepEqual(s,before);assert.deepEqual(effects,eb);return k.w.inspect().rescueEnemyMotion;}
const advance=(s,n)=>{for(let i=0;i<n;i++)core.step(s,core.IDLE,1/60);};
const sprite=(k,kind,index=0)=>kind==='yakra'?k.w.yakra:k.w.rescueFoes[index];
const rgba=(sp)=>{const z=sp.texture.getSize();return Buffer.from(sp.texture.getContext().getImageData(0,0,z.width,z.height).data);};
const counts=k=>[k.w.scene.meshes.length,k.w.scene.materials.length,k.w.scene.textures.length];
function delivered(chapter){const s=seed(chapter);s.rescue.guest.hp=0;for(let i=0;i<500;i++){s.effects.length=0;core.step(s,core.IDLE,1/60);if(s.effects.some(e=>e.enemyAction))return s;}throw Error('No real attack');}
function port(kind='naga'){let enabled=true,disposed=false,uploads=0;const c=cpuTestCanvas(kind==='yakra'?48:24,kind==='yakra'?48:32);const sp={mesh:{isDisposed:()=>disposed,isEnabled:()=>enabled,isVisible:true,visibility:1},texture:{getContext:()=>c.context,getSize:()=>({width:c.canvas.width,height:c.canvas.height}),update:()=>uploads++}};return{sp,c,uploads:()=>uploads,hide:()=>enabled=false,show:()=>enabled=true,dispose:()=>disposed=true};}
for(const kind of kinds){
 test(`S ${kind} frame0 is byte-identical to the retained original painter`,()=>{const p=cell(kind,0),old=surface(p.width,p.height);if(kind==='yakra')drawYakra(old.ink,0);else drawNaga(old.ink,kind==='hench');assert.deepEqual(p.rgba,old.rgba);if(kind==='yakra'){drawYakra(old.ink,1);assert.deepEqual(cell(kind,1).rgba,old.rgba);}});
 for(let frame=0;frame<5;frame++)test(`S ${kind}/${frame} is deterministic and independently frozen in the exact cell fixture`,()=>{const p=cell(kind,frame),q=cpuTestCanvas(p.width,p.height);drawRescueEnemyFrame(q.context,kind,frame);assert.deepEqual(Buffer.from(q.pixels()),p.rgba);assert.deepEqual({width:p.width,height:p.height,fnv1a32:fnv(p.rgba),sha256:sha(p.rgba)},golden.cells[`${kind}/${frame}`]);assert.deepEqual(cell(kind,frame).rgba,p.rgba);});
 test(`S ${kind} five distinct authored cells preserve face, foot rows and palette`,()=>{const base=cell(kind,0),palette=new Set();for(let n=0;n<base.rgba.length;n+=4)palette.add(base.rgba.subarray(n,n+4).toString('hex'));assert.equal(new Set([0,1,2,3,4].map(f=>sha(cell(kind,f).rgba))).size,5);for(let f=0;f<5;f++){const p=cell(kind,f),reference=surface(p.width,p.height);if(kind==='yakra')drawYakra(reference.ink,f===1?1:0);else drawNaga(reference.ink,kind==='hench');for(let y=0;y<p.height;y++)for(let x=0;x<p.width;x++){const n=(y*p.width+x)*4;assert(palette.has(p.rgba.subarray(n,n+4).toString('hex')));const retained=kind==='yakra'?(y<20||y>=41||(x>=10&&x<39)):(y<11||y>=27||(x>=6&&x<18&&y<18));if(retained)assert.deepEqual(p.rgba.subarray(n,n+4),reference.rgba.subarray(n,n+4),`${kind}/${f} pixel${x}/${y}`);}}});
}
for(const bad of [-1,5,.5,NaN,Infinity])test('S invalid cell '+String(bad)+' fails before drawing',()=>{const p=cell('naga',0),h=sha(p.rgba);assert.throws(()=>drawRescueEnemyFrame(p.ink,'naga',bad),RangeError);assert.equal(sha(p.rgba),h);});
test('S invalid kind fails before drawing',()=>{const p=cell('naga',0),h=sha(p.rgba);assert.throws(()=>drawRescueEnemyFrame(p.ink,'other',0));assert.equal(sha(p.rgba),h);});
for(const kind of kinds)for(const age of [0,7,8,15,16,23,24])test(`S ${kind} real action phases ${age}`,()=>{const expected=age<8?2:age<16?3:age<24?1:0;assert.equal(rescueEnemyFrame(100+age,0,kind,0,false,100,null),expected);assert.equal(rescueEnemyFrame(100+age,0,kind,0,true,100,100+age),0);assert.equal(rescueEnemyFrame(100+age,0,kind,0,false,100,100+age),4);});
test('S future/stale hit and action ticks do not invent a pose',()=>{for(const bad of [null,-1,101,NaN,Infinity,.5])assert.equal(rescueEnemyFrame(100,0,'naga',0,false,bad,bad),0);assert.equal(rescueEnemyFrame(118,0,'naga',0,false,null,100),0);for(const t of [-1,NaN,1.5])assert.throws(()=>rescueEnemyFrame(t,0,'naga',0,false,null,null));});
test('S original Yakra ready cells now depend only on simulation tick',()=>{for(let t=0;t<30;t++)assert.equal(rescueEnemyFrame(t,0,'yakra',.9,false,null,null),Math.floor(t/5)%2);});
for(const chapter of maps)test('S exact R rule parity every tick: '+chapter,()=>{const a=seed(chapter),b=seed(chapter,priorCore);for(let t=0;t<1100;t++){core.step(a,core.IDLE,1/60);priorCore.step(b,priorCore.IDLE,1/60);const x=structuredClone(a);for(const e of x.effects)delete e.enemyAction;assert.deepEqual(x,b,'only added metadata at tick'+t);if(t===180||t===700){assert.equal(core.action(a,0,'attack'),priorCore.action(b,0,'attack'));}}const events=a.effects.filter(e=>e.enemyAction);assert(events.length>0);for(const e of events){const f=a.enemies[e.enemyAction.index];assert.deepEqual(e.enemyAction.origin,{x:f.x,z:f.z});assert.deepEqual(e.enemyAction.target,{x:e.x,z:e.z});} });
for(const chapter of maps)test('S real core attacks drive actual production textures and recovery: '+chapter,()=>{const k=rig(),s=delivered(chapter),kind=s.enemies[0].kind;try{let m=draw(k,s);assert(m.history.some(h=>h.cause?.kind==='attack'&&h.frame===2));const sp=sprite(k,kind);assert.deepEqual(rgba(sp),cell(kind,2).rgba);advance(s,8);m=draw(k,s);assert.deepEqual(rgba(sp),cell(kind,3).rgba);advance(s,8);draw(k,s);assert.deepEqual(rgba(sp),cell(kind,1).rgba);advance(s,8);draw(k,s);assert.deepEqual(rgba(sp),cell(kind,0).rgba);const o={state:structuredClone(s),motion:k.w.inspect().rescueEnemyMotion,renderer:k.w.inspect().renderer};mkdirSync('test-results/rescue-enemy-offline',{recursive:true});writeFileSync(`test-results/rescue-enemy-offline/${kind}-observation.json`,JSON.stringify(o,null,2));}finally{k.close();}});
for(const chapter of maps)test('S living player recoil and logical death are unchanged: '+chapter,()=>{const k=rig(),s=seed(chapter),kind=s.enemies[0].kind;try{s.rescue.guest.hp=0;draw(k,s);advance(s,143);s.targets[0]=0;assert(core.action(s,0,'attack'));let m=draw(k,s);assert(m.history.some(h=>h.index===0&&h.frame===4&&h.hp>0));assert.deepEqual(rgba(sprite(k,kind)),cell(kind,4).rgba);mkdirSync('test-results/rescue-enemy-offline',{recursive:true});writeFileSync(`test-results/rescue-enemy-offline/${kind}-hurt-observation.json`,JSON.stringify({state:structuredClone(s),motion:m},null,2));advance(s,18);draw(k,s);assert.notDeepEqual(rgba(sprite(k,kind)),cell(kind,4).rgba);/* Explicit offline lethal fixture; same real action handles damage and finish. */s.enemies[0].hp=30;s.players[0].atb=1;s.targets[0]=0;assert(core.action(s,0,'attack'));const n=m.history.length;draw(k,s);assert.equal(sprite(k,kind).mesh.isEnabled(),false);assert.equal(s.enemies[0].hp,0);assert(!k.w.inspect().rescueEnemyMotion.history.slice(n).some(h=>h.index===0&&h.frame===4));}finally{k.close();}});
test('S Yakra true three-victim pulse triggers one source action',()=>{const s=seed('sanctum');let effects;for(let t=0;t<1000;t++){s.effects.length=0;core.step(s,core.IDLE,1/60);const e=s.effects.filter(e=>e.enemyAction);if(e.length===3){effects=structuredClone(e);break;}}assert(effects);const c=new RescueEnemyMotion(),p=port('yakra');c.begin(s,false);for(const e of effects)c.receive(s,e);c.update(p.sp,0);const h=c.inspect().history;assert.equal(h.length,1);assert.equal(h[0].frame,2);assert.deepEqual(h[0].cause.effect,effects[0]);assert.equal(new Set(effects.map(e=>JSON.stringify(e.enemyAction.target))).size,3);});
for(const defect of ['wrong-index','future','stale','actor','guest','wrong-origin','wrong-target','nan','dead','wrong-kind','wrong-effect','outside-rescue'])test('S negative delivered action '+defect,()=>{const s=delivered('cathedral'),e=structuredClone(s.effects.find(e=>e.enemyAction)),c=new RescueEnemyMotion(),p=port();if(defect==='wrong-index')e.enemyAction.index=3;if(defect==='future')e.enemyAction.tick++;if(defect==='stale')e.enemyAction.tick-=24;if(defect==='actor')e.actor=0;if(defect==='guest')e.guest=true;if(defect==='wrong-origin')e.enemyAction.origin.x+=1;if(defect==='wrong-target')e.enemyAction.target.z+=1;if(defect==='nan')e.x=NaN;if(defect==='dead')s.enemies[0].hp=0;if(defect==='wrong-kind')s.enemies[0].kind='imp';if(defect==='wrong-effect')e.kind='heal';if(defect==='outside-rescue')s.chapter='forest';c.begin(s,false);c.receive(s,e);c.update(p.sp,0);assert(!c.inspect().history.some(h=>h.cause?.kind==='attack'));});
test('S target-only foe damage cannot be misidentified as an attacker',()=>{const s=seed(),c=new RescueEnemyMotion(),p=port();c.begin(s,false);c.receive(s,{x:s.players[0].x,z:s.players[0].z,kind:'hit',text:'offline target-only'});c.update(p.sp,0);assert(c.inspect().history.every(h=>h.cause===null));});
test('S overlapping enemy targets never select an arbitrary living recoil',()=>{const s=seed(),c=new RescueEnemyMotion(),p=port();Object.assign(s.enemies[1],{x:s.enemies[0].x,z:s.enemies[0].z});c.begin(s,false);c.receive(s,{actor:0,kind:'hit',text:'offline ambiguous',x:s.enemies[0].x,z:s.enemies[0].z});c.update(p.sp,0);assert.equal(c.inspect().history[0].cause,null);});
test('S real guest hit is accepted without assigning it to a human slot',()=>{const s=seed('passage'),c=new RescueEnemyMotion(),p=port('hench');let e;for(let t=0;t<250;t++){s.effects.length=0;core.step(s,core.IDLE,1/60);e=s.effects.find(x=>x.guest&&x.kind==='hit');if(e)break;}assert(e);c.begin(s,false);c.receive(s,e);const i=s.enemies.findIndex(f=>f.x===e.x&&f.z===e.z);c.update(p.sp,i);assert.equal(c.inspect().history.at(-1).frame,4);});
test('S fixed tick repeated draw is stable and reduced preference restores exact pixels',()=>{const k=rig(),s=delivered('sanctum');try{draw(k,s);advance(s,8);draw(k,s);const before=Buffer.from(rgba(k.w.yakra)),c=counts(k),m=k.w.inspect().rescueEnemyMotion;for(let i=0;i<10;i++)draw(k,s,30,true);assert.deepEqual(k.w.inspect().rescueEnemyMotion,m);k.media.matches=true;draw(k,s);assert.deepEqual(rgba(k.w.yakra),cell('yakra',0).rgba);k.media.matches=false;draw(k,s);assert.deepEqual(rgba(k.w.yakra),before);assert.deepEqual(counts(k),c);}finally{k.close();}});
for(const hiding of ['disabled','invisible','zero-alpha','disposed'])test('S '+hiding+' sprite does not upload or read cells',()=>{const s=delivered('cathedral'),c=new RescueEnemyMotion(),p=port();c.begin(s,false);c.receive(s,s.effects.find(e=>e.enemyAction));if(hiding==='disabled')p.hide();if(hiding==='invisible')p.sp.mesh.isVisible=false;if(hiding==='zero-alpha')p.sp.mesh.visibility=0;if(hiding==='disposed')p.dispose();c.update(p.sp,0);assert.equal(p.uploads(),0);assert.equal(c.inspect().history.length,0);});
for(const reset of ['rewind','state','chapter','identity','explicit'])test('S '+reset+' clears action state but preserves physical cache without hidden redraw',()=>{let s=delivered('cathedral');const c=new RescueEnemyMotion(),p=port();c.begin(s,false);c.receive(s,s.effects.find(e=>e.enemyAction));c.update(p.sp,0);assert.equal(p.uploads(),1);p.hide();if(reset==='rewind')s.ticks--;if(reset==='state')s=structuredClone(s);if(reset==='chapter')s.chapter='passage';if(reset==='identity')s.enemies[0]=structuredClone(s.enemies[0]);if(reset==='explicit')c.reset();c.begin(s,false);c.update(p.sp,0);assert.equal(p.uploads(),1);p.show();c.update(p.sp,0);assert.equal(p.uploads(),2);assert.equal(c.inspect().cache[0].frame,0);assert.equal(c.inspect().history.at(-1).cause,null);});
test('S history is bounded and returned copies cannot mutate recorded sources',()=>{const s=seed(),c=new RescueEnemyMotion(),p=port();for(let t=0;t<60;t++){s.ticks=t;c.begin(s,t%2===0);c.receive(s,{kind:'hit',actor:0,x:s.enemies[0].x,z:s.enemies[0].z,text:'explicit offline bounded-history fixture'});c.update(p.sp,0);}const m=c.inspect();assert.equal(m.history.length,24);assert.equal(m.historyDropped,36);m.history[0].cause.effect.text='changed';assert.notEqual(c.inspect().history[0].cause.effect.text,'changed');c.dispose();assert.equal(c.inspect().history.length,0);assert.deepEqual(c.inspect().cache,[null,null,null]);c.begin(s,false);c.update(p.sp,0);assert(c.inspect().disposed);});
test('S read failure is explicit, never substituted with fabricated cell fingerprints',()=>{const s=seed(),c=new RescueEnemyMotion(),p=port();p.c.context.getImageData=()=>{throw Error('offline read failure');};c.begin(s,false);c.update(p.sp,0);assert.equal(c.inspect().textureReadFailures,1);assert.equal(c.inspect().history[0].cell,null);});
for(const [w,h]of[[192,128],[256,160],[240,180]])test(`S actual CPU rescue textures differ only during added action and return exact R ${w}x${h}`,()=>{const a=rig(w,h),b=rig(w,h,PriorWorld);try{const s=delivered('sanctum'),p=structuredClone(s);draw(a,s);draw(b,p);assert.deepEqual(s,p);assert.notDeepEqual(a.c.pixels(),b.c.pixels());advance(s,80);advance(p,80);draw(a,s);draw(b,p);assert.deepEqual(a.c.pixels(),b.c.pixels());assert.deepEqual(s,p);assert.deepEqual(counts(a),counts(b));mkdirSync('test-results/rescue-enemy-offline',{recursive:true});writeFileSync(`test-results/rescue-enemy-offline/cpu-${w}x${h}.json`,JSON.stringify({scope:'offline actual CPU rendering,not native',positiveActionPixels:true,restExactR:true,resourcesEqual:true}));}finally{b.close();a.close();}});
for(const name of Object.keys(rescueSSpec.files))test('S exact inverse and missing/duplicate/unrelated rejection '+name,()=>{const raw=readFileSync(name,'utf8'),old=rescueSBaseline(name,raw),e=rescueSSpec.files[name][0];assert.equal(sha(old),rescueSSpec.originalSha256[name]);assert.equal(rescueSIfDeclared(name,old),old);for(const bad of[raw+e.after,raw.replace(e.after,''),raw+'\n// unrelated\n'])assert.throws(()=>rescueSBaseline(name,bad));});
test('S held prologue, input, original art, timing and earlier motion controllers remain exact R',()=>{for(const [p,h] of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03s-unchanged-inputs.json'))))assert.equal(sha(readFileSync(p)),h,p);});
