import {landmarkIfDeclared} from './helpers/landmark-baseline.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {NullEngine,Scene,FreeCamera,Vector3,Camera,MeshBuilder,TransformNode,StandardMaterial} from '@babylonjs/core/index.js';
import {TownBuildingOcclusion,TOWN_BUILDING_OCCLUSION} from '../.test/town-building-occlusion.mjs';
import {World,createState,renderCompatibleScene} from '../.test/field-enemy-baseline-cpu-entry.mjs';import {World as OldWorld,renderCompatibleScene as renderOld} from '../.test/building-baseline-cpu-entry.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';import {buildingBaseline} from './helpers/building-baseline.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');const spec=JSON.parse(readFileSync('tests/baselines/vq03a-declared-building-edits.json'));const original=JSON.parse(readFileSync('tests/fixtures/ci68-town-building-regression.json'));
for(const [p,edits]of Object.entries(spec.files))test('A strict source inverse '+p,()=>{const s=landmarkIfDeclared(p,readFileSync(p,'utf8'));assert.equal(hash(buildingBaseline(p,s)),spec.originalSha256[p]);for(const e of edits){assert.throws(()=>buildingBaseline(p,s+e.after));assert.throws(()=>buildingBaseline(p,s.replace(e.after,'')));}assert.notEqual(hash(buildingBaseline(p,s+'\n// unrelated change\n')),spec.originalSha256[p]);});
function rig(){const engine=new NullEngine(),scene=new Scene(engine),camera=new FreeCamera('camera',new Vector3(0,0,-20),scene);camera.setTarget(Vector3.Zero());camera.mode=Camera.ORTHOGRAPHIC_CAMERA;scene.activeCamera=camera;
 const owner=new TransformNode('kingdom-truce',scene),a=MeshBuilder.CreateBox('truce-plaster',{width:4,height:4,depth:.4},scene);a.parent=owner;a.position.z=-2;const m=new StandardMaterial('unchanged-shared',scene);a.material=m;
 const sibling=MeshBuilder.CreateBox('unrelated',{size:1},scene);sibling.material=m;const actor=MeshBuilder.CreatePlane('hero',{width:1.36,height:1.85},scene);actor.position.z=0;const controller=new TownBuildingOcclusion(scene);
 return {engine,scene,camera,a,m,sibling,actor,controller,draw(t,id='p0',reduced=false){controller.update(t,'truce',[{id,mesh:actor}],reduced);return controller.inspect();},close(){scene.dispose();engine.dispose();}};}
for(const id of ['p0','p1','guest'])test('A triangle occlusion protects '+id+' without shared material mutation',()=>{const k=rig();try{const before={alpha:k.m.alpha,mode:k.m.transparencyMode,position:k.a.position.asArray(),scale:k.a.scaling.asArray()};const o=k.draw(1,id);assert.deepEqual(o.groups[0].blockedBy,[id]);assert.equal(k.a.visibility,.16);assert.equal(k.sibling.visibility,1);assert.equal(o.groups[0].members[0].blend,true);assert.deepEqual({alpha:k.m.alpha,mode:k.m.transparencyMode,position:k.a.position.asArray(),scale:k.a.scaling.asArray()},before);}finally{k.close();}});
for(const [name,setup]of [['behind actor',k=>k.actor.position.z=-4],['beside',k=>k.actor.position.x=9],['disabled',k=>k.actor.setEnabled(false)],['hidden',k=>k.actor.isVisible=false],['invisible',k=>k.actor.visibility=0]])test('A ignores '+name,()=>{const k=rig();try{setup(k);assert.equal(k.draw(0).groups[0].visibility,1);}finally{k.close();}});
test('A fixed ticks hold and restore, freeze repeated draws, reset reverse ticks',()=>{const k=rig();try{k.actor.position.x=9;k.draw(0);k.actor.position.x=0;const a=k.draw(1);assert(a.groups[0].visibility<1&&a.groups[0].visibility>.16);for(let i=0;i<10;i++)assert.deepEqual(k.draw(1),a);assert.equal(k.draw(200).groups[0].visibility,.16);k.actor.position.x=9;assert.equal(k.draw(211).groups[0].visibility,.16);assert(k.draw(213).groups[0].visibility>.16);assert.equal(k.draw(400).groups[0].visibility,1);k.actor.position.x=0;assert.equal(k.draw(0).groups[0].visibility,.16);k.controller.reset();assert.equal(k.a.visibility,1);assert.equal(k.controller.inspect().active,false);}finally{k.close();}});
test('A reduced motion, unknown owner, invalid tick and map exit stay local',()=>{const k=rig();try{k.actor.position.x=9;k.draw(0);k.actor.position.x=0;assert.equal(k.draw(1,'p0',true).groups[0].visibility,.16);for(const t of [NaN,Infinity,-1,1.5]){k.controller.update(t,'truce',[]);assert.equal(k.a.visibility,1);assert.equal(k.controller.inspect().active,false);}assert.deepEqual(k.draw(0,'unknown').subjects,[]);k.draw(1);k.controller.update(2,'forest',[]);assert.equal(k.a.visibility,1);}finally{k.close();}});
function pair(w=249,h=540){const oldDoc=globalThis.document,oldWindow=globalThis.window;const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};const a=cpuTestCanvas(w,h),b=cpuTestCanvas(w,h);a.canvas.ownerDocument=b.canvas.ownerDocument=doc;const current=new World(a.canvas),old=new OldWorld(b.canvas);return{a,b,current,old,close(){current.engine.dispose();old.engine.dispose();globalThis.document=oldDoc;globalThis.window=oldWindow;}};}
const geom=m=>({name:m.name,pos:m.position.asArray(),rot:m.rotation.asArray(),scale:m.scaling.asArray(),vertices:m.getTotalVertices(),indices:m.getTotalIndices(),material:m.material?.name,enabled:m.isEnabled()});
for(const stop of original.stops)test('A exact original CI68 '+stop.name+' state fixture, visibility only',()=>{const k=pair();try{const s=structuredClone(stop.state),before=structuredClone(s);k.current.draw(s,0,false);k.old.draw(structuredClone(s),0,false);assert.deepEqual(s,before);assert.deepEqual(k.current.scene.meshes.map(geom),k.old.scene.meshes.map(geom));assert.equal(k.current.scene.textures.length,k.old.scene.textures.length);assert.equal(k.current.scene.materials.length,k.old.scene.materials.length);assert.deepEqual(k.current.inspect().townSignOcclusion,k.old.inspect().townSignOcclusion);const o=k.current.inspect().townBuildingOcclusion;assert.equal(o.groups.length,4);assert(o.groups.every(g=>g.members.length===26));if(stop.name==='resident'){assert(o.groups.some(g=>g.blockedBy.includes('p0')));assert.notDeepEqual(k.a.pixels(),k.b.pixels());}else if(stop.name==='entry')assert.deepEqual(k.a.pixels(),k.b.pixels());const pixels=k.a.pixels().slice();for(let i=0;i<3;i++){k.current.draw(s,0,false);assert.deepEqual(k.a.pixels(),pixels);assert.deepEqual(s,before);}assert.equal(k.current.inspectRenderer().cpu.textureMemory.budget,33554432);}finally{k.close();}});
for(const portrait of [false,true])test('A non-Truce exact pixels and six warm-cache returns '+portrait,()=>{const k=pair(portrait?120:180,portrait?240:120);try{const chapters=['forest','castle','chamber','fair','bedroom','downstairs','overworld','cathedral','future'];for(const chapter of chapters){const s=createState(chapter);k.current.draw(s,0,false);k.old.draw(structuredClone(s),0,false);assert.deepEqual(k.a.pixels(),k.b.pixels(),chapter);assert.deepEqual(k.current.scene.meshes.map(geom),k.old.scene.meshes.map(geom));}for(const c of ['truce','forest','castle'])k.current.draw(createState(c),0,false);const n=[k.current.scene.meshes.length,k.current.scene.textures.length,k.current.scene.materials.length];for(let i=0;i<6;i++)for(const c of ['truce','forest','castle']){k.current.draw(createState(c),0,false);assert.deepEqual([k.current.scene.meshes.length,k.current.scene.textures.length,k.current.scene.materials.length],n);}}finally{k.close();}});
test('A holds forbidden game, renderer and prologue boundaries',()=>{for(const p of ['src/core.ts','src/main.ts','src/prologue-render.ts','src/cpu-raster.ts','src/cpu-scene.ts','.github/workflows/ci.yml'])assert.throws(()=>buildingBaseline(p,'modified'));const b=readFileSync('src/prologue-render.ts');assert.equal(createHash('sha1').update(Buffer.concat([Buffer.from(`blob ${b.length}\0`),b])).digest('hex'),'2711a74185aacf3c6bddf9db85ba99a2afbc507a');assert.equal(TOWN_BUILDING_OCCLUSION.approved,false);});

test('A resident actor contributes actual offline CPU pixels through the houses, unlike preserved CI68',()=>{const k=pair(390,844);try{
 const stop=original.stops.find(s=>s.name==='resident'),s=structuredClone(stop.state),frozen=structuredClone(s);const counts=[];
 for(const [world,port,render]of [[k.current,k.a,renderCompatibleScene],[k.old,k.b,renderOld]]){
  world.draw(structuredClone(s),0,false);const shown=port.pixels().slice(),player=world.scene.getMeshByName('player-0');
  // Offline-only ablation of presentation; this is not a browser hook or gameplay mutation.
  player.setEnabled(false);render(world.engine,world.scene);const absent=port.pixels();let changed=0;
  for(let i=0;i<shown.length;i+=4)if(shown[i]!==absent[i]||shown[i+1]!==absent[i+1]||shown[i+2]!==absent[i+2])changed++;
  counts.push(changed);player.setEnabled(true);render(world.engine,world.scene);assert.deepEqual(port.pixels(),shown);
 }
 assert.equal(counts[1],0,'preserved CI68 fixture reproduces fully hidden player');assert(counts[0]>100,'new presentation must render more than an incidental actor pixel');assert.deepEqual(s,frozen);
 }finally{k.close();}});

test('A build metadata names the actual new runtime batch',()=>{assert.match(landmarkIfDeclared('scripts/build.mjs',readFileSync('scripts/build.mjs','utf8')),/version:'0\.9\.48',batch:'VQ03A'/);});
