import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {assertTownBuildingRoute} from '../scripts/town-building-evidence.mjs';
const states=JSON.parse(readFileSync('tests/fixtures/ci68-town-building-regression.json')).stops;
// Synthetic shape fixtures remain separate from original native reports.
const anchors=[[-7,4],[7,4],[-6.5,-1.5],[6.5,-.6]];
const parts={'truce-chimney':1,'truce-crossbeam':1,'truce-door':1,'truce-glass':2,'truce-lintel':1,'truce-mullion':2,'truce-pitched-roof':2,'truce-plaster':1,'truce-ridge':1,'truce-roof-course':8,'truce-stone-plinth':1,'truce-timber':3,'truce-window':2};
function fixture(){return{stops:states.map(s=>({name:s.name,state:structuredClone(s.state),buildingOcclusion:{profile:'vq03a-town-building-visibility',active:true,approved:false,tick:s.state.ticks,method:'parallel-orthographic-triangle-rays',subjects:['p0'],fadeTicks:9,holdTicks:12,meshRayTests:60,groups:anchors.map(([x,z],i)=>{const hit=s.name==='resident'&&i===2,v=hit?.16:1;return{id:`truce-house:${x},${z}`,owner:'kingdom-truce',visibility:v,blockedBy:hit?['p0']:[],members:Object.entries(parts).flatMap(([name,n])=>Array.from({length:n},()=>({name,position:[x,1.5,z],visibility:v,originalVisibility:1,blend:hit})))}})}}))};}
test('A fixture only verifies observer shape, not new native evidence',()=>assert.equal(assertTownBuildingRoute(fixture()),true));
for(const [name,mutate]of [['missing observation',r=>delete r.stops[0].buildingOcclusion],['wrong tick',r=>r.stops[0].buildingOcclusion.tick++],['ghost P2',r=>r.stops[0].buildingOcclusion.subjects.push('p1')],['missing part',r=>r.stops[1].buildingOcclusion.groups[2].members.pop()],['no actual reveal',r=>r.stops[1].buildingOcclusion.groups[2].blockedBy=[]],['wrong blend',r=>r.stops[1].buildingOcclusion.groups[2].members[0].blend=false],['modified alpha',r=>r.stops[1].buildingOcclusion.groups[2].members[0].originalVisibility=.5],['unknown owner',r=>r.stops[1].buildingOcclusion.groups[2].blockedBy=['ghost']],['duplicate house',r=>r.stops[0].buildingOcclusion.groups[1].id=r.stops[0].buildingOcclusion.groups[0].id],['lost stop',r=>r.stops.pop()],['ray budget',r=>r.stops[0].buildingOcclusion.meshRayTests=2809]])test('A rejects '+name+' and retains first observation',()=>{const r=fixture();mutate(r);assert.throws(()=>assertTownBuildingRoute(r),e=>{assert.match(e.message,/Town building visibility/);assert('observation'in e);return true;});});

for(const [name,mutate]of [['wrong house anchor',g=>g.id='truce-house:100,100'],['wrong member identity',g=>g.members[0].name='inn-sign'],['duplicate instead of chimney',g=>g.members[0].name='truce-plaster'],['drifted plaster position',g=>g.members.find(m=>m.name==='truce-plaster').position[0]+=1]])test('A rejects '+name,()=>{const r=fixture();mutate(r.stops[1].buildingOcclusion.groups[2]);assert.throws(()=>assertTownBuildingRoute(r),/Town building visibility/);});
