import {canyonKIfDeclared} from './helpers/canyon-k-baseline.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {buildTrial} from '../.test/trial-render.mjs';
import {buildTrial as oldTrial} from '../.test/detail-j-prior-trial.mjs';
import {World,createState} from '../.test/cpu-entry.mjs';
import {World as OldWorld} from '../.test/detail-j-prior-world.mjs';
import {drawCourtDais,drawTrialOak,TRIAL_DETAIL_ART} from '../.test/trial-detail-art.mjs';
import {courtDaisUV} from '../.test/trial-detail.mjs';
import {drawWoodlandOak} from '../.test/woodland-art.mjs';
import {surface} from '../scripts/asset-export.mjs';
import {festivalTestScene} from './festival-test-scene.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';
import {detailJBaseline,detailJIfDeclared} from './helpers/detail-j-baseline.mjs';
const fixture=JSON.parse(readFileSync('tests/fixtures/ci80-detail-states.json'));
const sha=b=>createHash('sha256').update(b).digest('hex');
const pixels=t=>Buffer.from(t.getContext().getImageData(0,0,t.getSize().width,t.getSize().height).data);
const trees=scene=>scene.meshes.filter(m=>/^guardia1000(tree|canopy)$/.test(m.name));
const dais=scene=>scene.meshes.filter(m=>m.name==='court-curved-dais');
function geometry(scene){return scene.meshes.map(m=>({name:m.name,parent:m.parent?.name,position:m.position.asArray(),scaling:m.scaling.asArray(),rotation:m.rotation.asArray(),enabled:m.isEnabled(),visible:m.isVisible,billboard:m.billboardMode,vertices:sha(Buffer.from(new Float32Array(m.getVerticesData('position')??[]).buffer)),indices:sha(Buffer.from(new Uint32Array(m.getIndices()??[]).buffer))}));}
for(let variant=0;variant<4;variant++)test('J authored oak '+variant+' is deterministic, binary alpha and has the exact accepted contact roots',()=>{
 const a=surface(64,80),b=surface(64,80),old=surface(64,80);drawTrialOak(a.ink,variant);drawTrialOak(b.ink,variant);drawWoodlandOak(old.ink);assert.equal(Buffer.compare(a.rgba,b.rgba),0);assert.equal(Buffer.compare(a.rgba.subarray(64*54*4),old.rgba.subarray(64*54*4)),0);
 let opaque=0;for(let i=3;i<a.rgba.length;i+=4){assert([0,255].includes(a.rgba[i]));opaque+=a.rgba[i]===255;}assert(opaque>1500&&opaque<3500);assert.equal(a.rgba.subarray(64*77*4).some(x=>x!==0),false);
 if(variant===0)assert.equal(Buffer.compare(a.rgba,old.rgba),0);else assert.notEqual(Buffer.compare(a.rgba,old.rgba),0);
});
test('J four silhouettes genuinely differ, not only four metadata labels',()=>{const hashes=[];for(let i=0;i<4;i++){const a=surface(64,80);drawTrialOak(a.ink,i);hashes.push(sha(Buffer.from(Array.from(a.rgba).filter((_,i)=>i%4===3))));}assert.equal(new Set(hashes).size,4);});
test('J invalid variant refuses without modifying the destination',()=>{for(const v of [-1,4,NaN,Infinity,.5,'1',null]){const a=surface(64,80);a.rgba.fill(29);const before=Buffer.from(a.rgba);assert.throws(()=>drawTrialOak(a.ink,v),RangeError);assert.equal(Buffer.compare(before,a.rgba),0);}});
test('J dais atlas is opaque deterministic and separates cap from side',()=>{const a=surface(128,160),b=surface(128,160);drawCourtDais(a.ink);drawCourtDais(b.ink);assert.equal(Buffer.compare(a.rgba,b.rgba),0);for(let i=3;i<a.rgba.length;i+=4)assert.equal(a.rgba[i],255);assert(new Set(Array.from({length:128*128},(_,i)=>a.rgba.subarray(i*4,i*4+3).toString('hex'))).size>=5);assert.notEqual(sha(a.rgba.subarray(0,128*32*4)),sha(a.rgba.subarray(128*128*4)));});
test('J cap and edge UVs have padding, fresh vectors and only normalized coordinates',()=>{const a=courtDaisUV(),b=courtDaisUV();assert.deepEqual(a.map(v=>v.asArray()),[[0,.2,1,1],[0,.0125,1,.175],[0,.2,1,1]]);a[0].y=8;assert.equal(b[0].y,.2);});
test('J original three dais cylinders share one nearest opaque cap/edge atlas; geometry and court feet unchanged',()=>{
 const r=festivalTestScene(),p=festivalTestScene();try{const current=buildTrial(r.scene,r.shadow),old=oldTrial(p.scene,p.shadow),s=structuredClone(fixture.states.courtroom);current.draw(s);old.draw(structuredClone(s));assert.deepEqual(geometry(r.scene),geometry(p.scene));const ms=dais(r.scene);assert.equal(ms.length,3);assert(ms.every(m=>m.material===ms[0].material));const t=ms[0].material.diffuseTexture;assert(t);assert.deepEqual({...t.getSize()},{width:128,height:160});assert.equal(t.samplingMode,1);assert.equal(t.hasAlpha,false);assert.equal(t.wrapU,0);assert.equal(t.wrapV,0);assert.equal(r.scene.textures.length,p.scene.textures.length+1);const a=surface(128,160);drawCourtDais(a.ink);assert.equal(sha(pixels(t)),sha(a.rgba));for(const a of current.inspect().courtStaging.actors)assert(a.footError<1e-5);
 const oldUV=dais(p.scene)[0].getVerticesData('uv');assert.notDeepEqual(ms[0].getVerticesData('uv'),oldUV);assert.deepEqual(s,fixture.states.courtroom);
 }finally{r.dispose();p.dispose();}
});
test('J all fifteen existing trees use stable authored sequence without moving or adding cards',()=>{
 const r=festivalTestScene(),p=festivalTestScene();try{const current=buildTrial(r.scene,r.shadow),old=oldTrial(p.scene,p.shadow),s=structuredClone(fixture.states['forest-gate']);current.draw(s);old.draw(structuredClone(s));assert.deepEqual(geometry(r.scene),geometry(p.scene));assert.equal(r.scene.textures.length,p.scene.textures.length);const ts=trees(r.scene);assert.equal(ts.length,15);const hashes=[];ts.forEach((m,i)=>{const t=m.material.diffuseTexture;assert.deepEqual({...t.getSize()},{width:64,height:80});assert.equal(t.samplingMode,1);assert.equal(t.hasAlpha,true);const a=surface(64,80);drawTrialOak(a.ink,i%4);assert.equal(sha(pixels(t)),sha(a.rgba));hashes.push(sha(pixels(t)));});assert.equal(new Set(hashes).size,4);for(let i=1;i<hashes.length;i++)assert.notEqual(hashes[i],hashes[i-1]);assert.deepEqual(current.inspect().forestGate.position,[5.5,1.35,4]);assert.deepEqual(s,fixture.states['forest-gate']);
 }finally{r.dispose();p.dispose();}
});
test('J static textures never upload on draws or reduced-motion changes; roots cache and dispose',()=>{
 const r=festivalTestScene();try{const trial=buildTrial(r.scene,r.shadow);for(const s of Object.values(fixture.states))trial.draw(structuredClone(s));const counts=[r.scene.meshes.length,r.scene.textures.length],selected=[dais(r.scene)[0].material.diffuseTexture,...trees(r.scene).map(m=>m.material.diffuseTexture)];const hashes=selected.map(t=>sha(pixels(t)));let uploads=0;for(const t of selected){const original=t.update.bind(t);t.update=(...args)=>{uploads++;return original(...args);};}
 for(let i=0;i<60;i++)for(const s of Object.values(fixture.states))trial.draw(structuredClone(s),!!(i%2));assert.equal(uploads,0);assert.deepEqual(counts,[r.scene.meshes.length,r.scene.textures.length]);assert.deepEqual(hashes,selected.map(t=>sha(pixels(t))));trial.draw(createState('hall1000'));assert(!r.scene.getTransformNodeByName('trial-courtroom').isEnabled());assert(!r.scene.getTransformNodeByName('trial-guardia1000').isEnabled());r.scene.dispose();assert.equal(r.scene.textures.length,0);assert.equal(r.scene.meshes.length,0);
 }finally{r.dispose();}
});
function rig(w,h){const saved={window:globalThis.window,document:globalThis.document,matchMedia:globalThis.matchMedia},media={matches:false,addEventListener(){},removeEventListener(){}};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.matchMedia=()=>media;globalThis.document=doc;globalThis.window={devicePixelRatio:1,matchMedia:()=>media,addEventListener(){},removeEventListener(){},navigator:{}};const ca=cpuTestCanvas(w,h),cb=cpuTestCanvas(w,h);ca.canvas.ownerDocument=cb.canvas.ownerDocument=doc;let a,b;try{a=new World(ca.canvas);b=new OldWorld(cb.canvas);}catch(e){a?.engine.dispose();Object.assign(globalThis,saved);throw e;}return {a,b,ca,cb,media,close(){a.engine.dispose();b.engine.dispose();Object.assign(globalThis,saved);}};}
for(const [w,h] of [[192,128],[96,160],[160,96]])test(`J current offline ${w}x${h}: actual new pixels, unchanged support/geometry/state, exact restoration`,()=>{const r=rig(w,h);try{for(const s0 of Object.values(fixture.states)){const s=structuredClone(s0);r.media.matches=false;r.a.draw(s,0,false);r.b.draw(structuredClone(s),0,false);const initial=Buffer.from(r.ca.pixels());assert.notEqual(Buffer.compare(initial,Buffer.from(r.cb.pixels())),0,s.chapter);assert.deepEqual(geometry(r.a.scene),geometry(r.b.scene));const counts=[r.a.scene.meshes.length,r.a.scene.textures.length];r.media.matches=true;r.a.draw(s,0,false);const reduced=Buffer.from(r.ca.pixels());r.a.draw(s,0,false);assert.equal(Buffer.compare(reduced,Buffer.from(r.ca.pixels())),0);r.media.matches=false;r.a.draw(s,0,false);assert.equal(Buffer.compare(initial,Buffer.from(r.ca.pixels())),0);assert.deepEqual(s,s0);assert.deepEqual(counts,[r.a.scene.meshes.length,r.a.scene.textures.length]);if(s.chapter==='courtroom')assert.deepEqual(r.a.inspect().trialMaps.courtStaging,r.b.inspect().trialMaps.courtStaging);}}finally{r.close();}});
test('J other eight maps retain exact CI80 pixels and geometry',()=>{const r=rig(192,128);try{for(const chapter of ['fair','hall1000','cellblock','execution','prisonstairs','warden','prisonbridge','futuregate']){const s=createState(chapter==='fair'?'bedroom':chapter);s.chapter=chapter;s.mode='explore';s.ticks=140;if(chapter==='fair')s.prologue.stage='fair';const before=structuredClone(s);r.a.draw(s,0,false);r.b.draw(structuredClone(s),0,false);assert.equal(Buffer.compare(Buffer.from(r.ca.pixels()),Buffer.from(r.cb.pixels())),0,chapter);assert.deepEqual(geometry(r.a.scene),geometry(r.b.scene));assert.deepEqual(s,before);}}finally{r.close();}});
const spec=JSON.parse(readFileSync('tests/baselines/vq03j-declared-detail-edits.json'));
for(const [n,edits] of Object.entries(spec.files))test('J exact CI80 source inverse with missing/duplicate/unrelated guards: '+n,()=>{const raw=canyonKIfDeclared(n,readFileSync(n,'utf8')),old=detailJBaseline(n,raw);assert.equal(sha(old),spec.originalSha256[n]);assert.equal(detailJIfDeclared(n,old),old);for(const e of edits){assert.throws(()=>detailJBaseline(n,raw.replace(e.after,'')));assert.throws(()=>detailJBaseline(n,raw+e.after));}assert.notEqual(sha(detailJBaseline(n,raw+'\n// unrelated')),spec.originalSha256[n]);});
test('J static-only helpers have no clock, randomness, state writes or networking and held art is unchanged',()=>{for(const p of ['src/trial-detail-art.ts','src/trial-detail.ts'])assert.doesNotMatch(readFileSync(p,'utf8'),/Math\.random|Date\.|performance\.|setTimeout|setInterval|fetch\(|\.ticks|\.players|TRIAL_SOLIDS/);const held=readFileSync('src/prologue-render.ts');assert.equal(createHash('sha1').update(`blob ${held.length}\0`).update(held).digest('hex'),'2711a74185aacf3c6bddf9db85ba99a2afbc507a');assert.equal(TRIAL_DETAIL_ART.approved,false);assert.equal(fixture.run,'36117413556');});
