/** Offline fixtures and real production CPU rendering. No native game/time/state injection. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {trialHistoryEviction,TRIAL_MOTION_HISTORY} from '../.test/trial-motion-history.mjs';
import {trialHistoryWBaseline,trialHistoryWIfDeclared,trialHistoryWSpec} from './helpers/trial-history-w-baseline.mjs';
import {World} from '../.test/cpu-entry.mjs';
import {World as PriorWorld} from '../.test/trial-history-w-prior-world.mjs';
import * as core from '../.test/core.mjs';
import {beginTrialBattle} from '../.test/trial-rules.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
const row=(index,tick,kind='attack',frame=2)=>({index,chapter:'prisonbridge',kind:index===0?'tankHead':index===1?'tankBody':'tankWheel',frame,reducedMotion:false,cause:kind===null?null:{kind,tick}});
function append(a,r){a.push(r);if(a.length>24){const x=trialHistoryEviction(a);a.splice(x.index,1);return x.reason;}return null;}
for(const n of [0,1,24,26])test('W rejects non-overflow selection '+n,()=>assert.throws(()=>trialHistoryEviction(Array.from({length:n},()=>row(0,1))),RangeError));
test('W evicts passive history before a real repair without mutating any row',()=>{const rows=[row(0,1,'repair'),...Array.from({length:23},(_,i)=>row(1,i+2)),row(2,30,null)],copy=structuredClone(rows);assert.deepEqual(trialHistoryEviction(rows),{index:24,reason:'idle'});assert.deepEqual(rows,copy);});
test('W peer action flood retains the latest source repair within 24 samples',()=>{const a=[row(0,1,'repair',2),row(0,1,'repair',3),row(0,1,'repair',1)];const original=[...a];for(let tick=2;tick<1000;tick++){append(a,row(1,tick));append(a,row(2,tick));assert(a.length<=24);assert(original.every(r=>a.includes(r)));}assert.equal(a.length,24);});
test('W newer same-source repair supersedes the old repair, not peer latest phases',()=>{const a=[row(0,1,'repair'),...Array.from({length:23},(_,i)=>row(1,2,'attack',i)),row(0,3,'repair')];assert.deepEqual(trialHistoryEviction(a),{index:0,reason:'superseded'});});
test('W operation and actor ownership are distinct retention families',()=>{const a=[row(0,1,'repair'),row(1,1,'hurt'),...Array.from({length:22},()=>row(2,2)),row(2,3)];assert.deepEqual(trialHistoryEviction(a),{index:2,reason:'superseded'});});
test('W repeated same-event frame can leave without inventing missing phases',()=>{const a=Array.from({length:25},()=>row(0,1,'repair',2));assert.deepEqual(trialHistoryEviction(a),{index:0,reason:'duplicate'});a.splice(0,1);assert(!a.some(r=>r.frame===3));});
test('W different reduced preference is not the same observed phase',()=>{const a=Array.from({length:25},(_,i)=>({...row(i,1),kind:'offline-'+i}));a[1]={...a[0],reducedMotion:true};assert.equal(trialHistoryEviction(a).reason,'capacity');});
test('W bounded fallback remains explicit when every sample is distinct',()=>{const a=Array.from({length:25},(_,i)=>({...row(i,1),kind:'offline-'+i}));assert.deepEqual(trialHistoryEviction(a),{index:0,reason:'capacity'});});
test('W missing real repair never becomes a repair through retention',()=>{const a=[];for(let t=0;t<300;t++)append(a,row(1,t));assert(!a.some(r=>r.cause?.kind==='repair'));});
function seed(){const s=core.createState('prisonbridge');s.kingdom.phase='rescue';s.joined=true;Object.assign(s.trial,{stage:'tank',knocks:3,luccaJoined:true,guardsWon:true,fade:0});assert(beginTrialBattle(s,'tank'));return s;}
function rig(W=World,width=192,height=128){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;const c=cpuTestCanvas(width,height);c.canvas.ownerDocument=doc;const w=new W(c.canvas);return {w,c,media,close(){w.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};}
function draw(k,s,es=s.effects.splice(0)){const before=structuredClone(s),effects=structuredClone(es);k.w.draw(s,0,false,es);assert.deepEqual(s,before);assert.deepEqual(es,effects);const m=k.w.inspect().trialMaps.enemyMotion;assert(m.history.length<=24);return m;}
function advance(s,n){for(let i=0;i<n;i++)core.step(s,core.IDLE,1/60);}
function repair(k,s){draw(k,s);s.enemies[1].hp-=30;s.enemies[0].atb=.999;advance(s,1);const m=draw(k,s);assert.equal(s.trial.headRepairs,1);assert(m.history.some(h=>h.cause?.kind==='repair'));return m;}
const counts=k=>[k.w.scene.meshes.length,k.w.scene.materials.length,k.w.scene.textures.length];
for(const [width,height,cadence] of [[192,128,7],[256,160,11],[240,180,19]])test(`W actual ${width}x${height} delayed repair capture retains drawn cells; exact V loses them (cadence${cadence})`,()=>{const a=rig(World,width,height),b=rig(PriorWorld,width,height),s=seed(),v=structuredClone(s);try{repair(a,s);repair(b,v);const compare=()=>{assert.deepEqual(s,v);assert.deepEqual(Buffer.from(a.c.pixels()),Buffer.from(b.c.pixels()));assert.deepEqual(counts(a),counts(b));};compare();for(const n of [8,8]){advance(s,n);advance(v,n);draw(a,s);draw(b,v);compare();}const originallyDrawn=draw(a,s).history.filter(h=>h.cause?.kind==='repair');assert.deepEqual(new Set(originallyDrawn.map(h=>h.frame)),new Set([1,2,3]));
 for(let i=0;i<300;i++){advance(s,1);advance(v,1);if(i%cadence===cadence-1){draw(a,s);draw(b,v);compare();}}const m=draw(a,s),prior=draw(b,v);compare();assert.equal(prior.history.filter(h=>h.cause?.kind==='repair').length,0);assert(originallyDrawn.every(r=>m.history.some(h=>JSON.stringify(h)===JSON.stringify(r))));assert.equal(m.historyPolicy,TRIAL_MOTION_HISTORY.id);assert.equal(Object.values(m.historyEvictions).reduce((a,b)=>a+b,0),m.historyDropped);assert(m.historyEvictions.idle>0);mkdirSync('test-results/trial-history-offline',{recursive:true});writeFileSync(`test-results/trial-history-offline/delayed-${cadence}.json`,JSON.stringify({scope:'offline exact-V/production-W comparison,not native',state:s,motion:m,priorHistory:prior.history,pixelsIdentical:true,resourcesIdentical:true},null,2));}finally{b.close();a.close();}});
test('W same tick repeat/cache does not add samples or texture uploads',()=>{const k=rig(),s=seed();try{repair(k,s);advance(s,8);const before=draw(k,s);for(let n=0;n<25;n++)assert.deepEqual(draw(k,s),before);}finally{k.close();}});
test('W reduced preference round trips cannot grow history beyond the original bound',()=>{const k=rig(),s=seed();try{repair(k,s);const resources=counts(k);for(let n=0;n<100;n++){k.media.matches=!!(n%2);draw(k,s);}assert.deepEqual(counts(k),resources);assert(k.w.inspect().trialMaps.enemyMotion.history.length<=24);}finally{k.close();}});
test('W new encounter in the same State after victory cannot inherit old repair evidence',()=>{const k=rig(),s=seed();try{repair(k,s);s.enemies.forEach(e=>e.hp=0);s.mode='victory';draw(k,s);assert(k.w.inspect().trialMaps.enemyMotion.history.some(h=>h.cause?.kind==='repair'));s.enemies=seed().enemies;s.mode='battle';s.ticks++;const m=draw(k,s,[]);assert(!m.history.some(h=>h.cause));}finally{k.close();}});
for(const operation of ['reload','rewind','chapter'])test('W '+operation+' invalidates observations instead of relabelling their owner',()=>{const k=rig(),s=seed();try{repair(k,s);let next=s;if(operation==='reload')next=structuredClone(s);if(operation==='rewind')s.ticks=0;if(operation==='chapter'){s.chapter='warden';s.mode='explore';}const m=draw(k,next,[]);assert(!m.history.some(h=>h.cause));assert.equal(m.historyDropped,0);assert.equal(Object.values(m.historyEvictions).reduce((a,b)=>a+b,0),0);}finally{k.close();}});
test('W disposing a borrowed mesh removes only its own stored observations',()=>{const k=rig(),s=seed();try{repair(k,s);const before=draw(k,s);assert(before.history.some(h=>h.index===1));k.w.scene.getMeshByName('prisonbridgetank-head').dispose();const m=k.w.inspect().trialMaps.enemyMotion;assert(!m.history.some(h=>h.index===0));assert(m.history.some(h=>h.index===1));}finally{k.close();}});
test('W inspect snapshots cannot mutate actual sample storage or counters',()=>{const k=rig(),s=seed();try{repair(k,s);const m=draw(k,s);m.history[0].frame=999;m.historyEvictions.idle=999;const actual=k.w.inspect().trialMaps.enemyMotion;assert(actual.history.every(h=>h.frame<5));assert.notEqual(actual.historyEvictions.idle,999);}finally{k.close();}});
test('W hidden target does not create a repair sample; missing observation remains missing',()=>{const k=rig(),s=seed();try{draw(k,s);k.w.scene.getMeshByName('prisonbridgetank-head').isVisible=false;s.enemies[1].hp-=30;s.enemies[0].atb=.999;advance(s,1);const m=draw(k,s);assert.equal(s.trial.headRepairs,1);assert(!m.history.some(h=>h.cause?.kind==='repair'));}finally{k.close();}});
for(const name of Object.keys(trialHistoryWSpec.files))test('W strict exact-V source inverse '+name,()=>{const raw=readFileSync(name,'utf8'),old=trialHistoryWBaseline(name,raw),e=trialHistoryWSpec.files[name][0];assert.equal(hash(old),trialHistoryWSpec.originalSha256[name]);assert.equal(trialHistoryWIfDeclared(name,old),old);for(const bad of [raw.replace(e.after,''),raw+e.after,raw+'\n// unrelated drift'])assert.throws(()=>trialHistoryWBaseline(name,bad));});
test('W unchanged gameplay, art, V bodies, native gates and held prologue are byte-identical',()=>{for(const [name,h] of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03w-unchanged-inputs.json'))))assert.equal(hash(readFileSync(name)),h,name);});
