import {trialBodyVIfDeclared} from './helpers/trial-body-v-baseline.mjs';
import {trialUBaseline,trialUIfDeclared,trialUSpec} from './helpers/trial-u-baseline.mjs';
/** Offline rule/texture fixtures only. Provider CI owns native evidence. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as core from '../.test/core.mjs';
import * as prior from '../.test/trial-u-prior-core.mjs';
import {beginTrialBattle} from '../.test/trial-rules.mjs';
import {World} from '../.test/cpu-entry.mjs';
import {World as PriorWorld} from '../.test/trial-u-prior-world.mjs';
import {TrialEnemyMotion,trialEnemyFrame} from '../.test/trial-enemy-motion.mjs';
import {drawTrialEnemy} from '../.test/trial-enemy-art.mjs';
import {drawWitness} from '../.test/witness-art.mjs';
import {drawTankPart} from '../.test/trial-art.mjs';
import {surface} from '../scripts/asset-export.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';
const kinds=['prisonGuard','tankHead','tankBody','tankWheel'];
const sha=x=>createHash('sha256').update(x).digest('hex');
const fnv=d=>{let h=2166136261;for(const v of d)h=Math.imul(h^v,16777619);return h>>>0;};
const cells=JSON.parse(readFileSync('tests/fixtures/trial-enemy-cells.json')).cells;
function seed(chapter='prisonbridge',C=core){const s=C.createState(chapter);s.kingdom.phase='rescue';s.joined=true;Object.assign(s.trial,{stage:chapter==='prisonbridge'?'tank':'escape',knocks:3,luccaJoined:chapter==='prisonbridge',guardsWon:chapter==='prisonbridge',fade:0});assert(beginTrialBattle(s,chapter==='prisonbridge'?'tank':chapter==='cellblock'?'cellguards':'stairguards'));return s;}
function rig(W=World,width=192,height=128){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;const c=cpuTestCanvas(width,height);c.canvas.ownerDocument=doc;const w=new W(c.canvas);return {w,c,media,close(){w.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};}
function draw(k,s,effects=s.effects.splice(0)){const before=structuredClone(s),ef=structuredClone(effects);k.w.draw(s,0,false,effects);assert.deepEqual(s,before);assert.deepEqual(effects,ef);return k.w.inspect().trialMaps.enemyMotion;}
function advance(s,n){for(let i=0;i<n;i++)core.step(s,core.IDLE,1/60);}
function cell(kind,frame){const p=surface(kind==='prisonGuard'?48:64,64);drawTrialEnemy(p.ink,kind,frame);return p;}
function mesh(k,index,s){return s.chapter==='prisonbridge'?k.w.scene.getMeshByName('prisonbridge'+['tank-head','tank-body','tank-wheel'][index]):k.w.scene.meshes.filter(m=>m.name===s.chapter+'guard').slice(-2)[index];}
const rgba=m=>{const t=m.material.diffuseTexture,z=t.getSize();return Buffer.from(t.getContext().getImageData(0,0,z.width,z.height).data);};
const counts=k=>[k.w.scene.meshes.length,k.w.scene.materials.length,k.w.scene.textures.length];
function emit(s,index=1){s.effects.length=0;s.enemies[index].atb=.999;advance(s,1);assert(s.effects.some(e=>e.enemyAction?.index===index));return s.effects.splice(0);}
for(const kind of kinds){
 for(let frame=0;frame<5;frame++)test(`U ${kind}/${frame} deterministic actual cell matches frozen independent fixture`,()=>{const p=cell(kind,frame),c=cpuTestCanvas(p.width,p.height);drawTrialEnemy(c.context,kind,frame);assert.deepEqual(Buffer.from(c.pixels()),p.rgba);assert.deepEqual({width:p.width,height:p.height,fnv1a32:fnv(p.rgba),sha256:sha(p.rgba)},cells[`${kind}/${frame}`]);});
 test(`U ${kind} retains original cells0/1, original palette and contact rows`,()=>{for(const f of [0,1]){const p=cell(kind,f),o=surface(p.width,p.height);if(kind==='prisonGuard')drawWitness(o.ink,'guard',f);else drawTankPart(o.ink,kind.slice(4).toLowerCase(),f);assert.deepEqual(p.rgba,o.rgba);}const p=cell(kind,0),colors=new Set();for(const f of [0,1]){const q=cell(kind,f);for(let i=0;i<q.rgba.length;i+=4)colors.add(q.rgba.subarray(i,i+4).toString('hex'));}for(const f of [2,3,4]){const q=cell(kind,f);assert.notEqual(sha(q.rgba),sha(p.rgba));for(let i=0;i<q.rgba.length;i+=4)assert(colors.has(q.rgba.subarray(i,i+4).toString('hex')));for(let y=kind==='prisonGuard'?55:59;y<64;y++)assert.deepEqual(q.rgba.subarray(y*p.width*4,(y+1)*p.width*4),p.rgba.subarray(y*p.width*4,(y+1)*p.width*4));}});
 for(const age of [0,7,8,15,16,23,24])test(`U ${kind} delivered action ages ${age} obey fixed phases`,()=>{const kindCause=kind==='tankHead'?'repair':'attack',f=trialEnemyFrame(100+age,kind,false,{kind:kindCause,tick:100});assert.equal(f,age<8?2:age<16?3:age<24?1:kind==='prisonGuard'?0:trialEnemyFrame(100+age,kind,false,null));assert.equal(trialEnemyFrame(100+age,kind,true,{kind:kindCause,tick:100}),0);});
}
for(const f of [-1,5,.1,NaN,Infinity])test('U invalid pose '+String(f)+' leaves pixels unchanged',()=>{const p=cell('prisonGuard',0),h=sha(p.rgba);assert.throws(()=>drawTrialEnemy(p.ink,'prisonGuard',f));assert.equal(sha(p.rgba),h);});
test('U invalid kind and tick reject without invented phases',()=>{assert.throws(()=>drawTrialEnemy(surface(64,64).ink,'other',0));for(const t of [-1,NaN,.2])assert.throws(()=>trialEnemyFrame(t,'tankHead',false,null));assert.equal(trialEnemyFrame(100,'prisonGuard',false,{kind:'attack',tick:101}),0);assert.equal(trialEnemyFrame(100,'prisonGuard',false,{kind:'hurt',tick:-1}),0);});
for(const chapter of ['cellblock','prisonstairs','prisonbridge'])test('U exact T full rule parity with only declared presentation metadata: '+chapter,()=>{const a=seed(chapter),b=seed(chapter,prior);if(chapter==='prisonbridge')a.enemies[1].hp=b.enemies[1].hp=160;for(let t=0;t<600;t++){core.step(a,core.IDLE,1/60);prior.step(b,prior.IDLE,1/60);const x=structuredClone(a);for(const e of x.effects)delete e.enemyAction;assert.deepEqual(x,b,'tick'+t);}const es=a.effects.filter(e=>e.enemyAction);assert(es.length);for(const e of es){const f=a.enemies[e.enemyAction.index];assert.deepEqual(e.enemyAction.origin,{x:f.x,z:f.z});assert.deepEqual(e.enemyAction.target,{x:e.x,z:e.z});}assert.throws(()=>core.serialize(a));assert.throws(()=>prior.serialize(b));for(let n=0;n<10000&&a.mode==='battle';n++){core.step(a,core.IDLE,1/60);prior.step(b,prior.IDLE,1/60);}assert.equal(a.mode,'defeat');assert.equal(b.mode,'defeat');core.leaveBattle(a);prior.leaveBattle(b);for(let n=0;n<100;n++){core.step(a,core.IDLE,1/60);prior.step(b,prior.IDLE,1/60);}assert.equal(core.serialize(a),prior.serialize(b));});
for(const [kind,index,chapter] of [['prisonGuard',0,'cellblock'],['tankBody',1,'prisonbridge'],['tankWheel',2,'prisonbridge'],['tankHead',0,'prisonbridge']])test('U actual delivered '+kind+' action drives real production texture and recovery',()=>{const k=rig(),s=seed(chapter);try{draw(k,s);if(kind==='tankHead')s.enemies[1].hp-=40;const es=emit(s,index);let m=draw(k,s,es);assert(m.history.some(h=>h.index===index&&h.frame===2&&h.cause?.kind===(kind==='tankHead'?'repair':'attack')));assert.deepEqual(rgba(mesh(k,index,s)),cell(kind,2).rgba);advance(s,8);draw(k,s);assert.deepEqual(rgba(mesh(k,index,s)),cell(kind,3).rgba);advance(s,8);draw(k,s);assert.deepEqual(rgba(mesh(k,index,s)),cell(kind,1).rgba);advance(s,8);m=draw(k,s);assert.deepEqual(rgba(mesh(k,index,s)),cell(kind,trialEnemyFrame(s.ticks,kind,false,null)).rgba);mkdirSync('test-results/trial-enemy-offline',{recursive:true});writeFileSync(`test-results/trial-enemy-offline/${kind}.json`,JSON.stringify({state:structuredClone(s),motion:m},null,2));}finally{k.close();}});
test('U wheel multiple victims and head multiple repairs remain one source action each',()=>{const k=rig(),s=seed();try{draw(k,s);s.enemies[1].hp-=40;s.enemies[2].hp-=40;const es=emit(s,0);assert.equal(es.length,2);draw(k,s,es);assert.equal(k.w.inspect().trialMaps.enemyMotion.history.filter(h=>h.cause?.kind==='repair').length,1);const wheel=emit(s,2);assert.equal(wheel.length,2);draw(k,s,wheel);assert.equal(k.w.inspect().trialMaps.enemyMotion.history.filter(h=>h.index===2&&h.cause?.kind==='attack').length,1);}finally{k.close();}});
test('U physical hurt uses actual HP delta; head shield never invents hurt',()=>{const k=rig(),s=seed();try{draw(k,s);s.players[1].atb=1;s.targets[1]=0;assert(core.action(s,1,'skill'));draw(k,s);assert(!k.w.inspect().trialMaps.enemyMotion.history.some(h=>h.cause?.kind==='hurt'));s.players[0].atb=1;s.targets[0]=0;assert(core.action(s,0,'attack'));draw(k,s);assert.deepEqual(rgba(mesh(k,0,s)),cell('tankHead',4).rgba);mkdirSync('test-results/trial-enemy-offline',{recursive:true});writeFileSync('test-results/trial-enemy-offline/hurt-head.json',JSON.stringify({state:structuredClone(s),motion:k.w.inspect().trialMaps.enemyMotion},null,2));advance(s,18);draw(k,s);assert.notDeepEqual(rgba(mesh(k,0,s)),cell('tankHead',4).rgba);}finally{k.close();}});
test('U same tick/cache/reduced toggle avoids repeated uploads and retains action phase',()=>{const k=rig(),s=seed();try{draw(k,s);draw(k,s,emit(s,1));advance(s,9);let m=draw(k,s),bindings=structuredClone(m.bindings),pixels=Buffer.from(k.c.pixels());for(let i=0;i<30;i++){draw(k,s);assert.deepEqual(k.w.inspect().trialMaps.enemyMotion.bindings,bindings);assert.deepEqual(Buffer.from(k.c.pixels()),pixels);}k.media.matches=true;draw(k,s);assert.deepEqual(rgba(mesh(k,1,s)),cell('tankBody',0).rgba);m=k.w.inspect().trialMaps.enemyMotion;draw(k,s);assert.deepEqual(k.w.inspect().trialMaps.enemyMotion,m);k.media.matches=false;draw(k,s);assert.deepEqual(rgba(mesh(k,1,s)),cell('tankBody',3).rgba);}finally{k.close();}});
test('U hidden and dead textures stop; state identity and rewind clear old causes',()=>{const k=rig(),s=seed();try{draw(k,s);draw(k,s,emit(s,1));const b=mesh(k,1,s);b.isVisible=false;let n=k.w.inspect().trialMaps.enemyMotion.bindings[1].uploads;advance(s,20);draw(k,s);assert.equal(k.w.inspect().trialMaps.enemyMotion.bindings[1].uploads,n);b.isVisible=true;draw(k,s);assert(!k.w.inspect().trialMaps.enemyMotion.history.at(-1).cause);s.enemies[1].hp=0;draw(k,s);n=k.w.inspect().trialMaps.enemyMotion.bindings[1].uploads;advance(s,30);draw(k,s);assert.equal(k.w.inspect().trialMaps.enemyMotion.bindings[1].uploads,n);assert.equal(b.isEnabled(),false);const reload=seed();draw(k,reload);assert(k.w.inspect().trialMaps.enemyMotion.history.every(h=>h.cause===null));draw(k,reload,emit(reload,1));reload.ticks=0;reload.effects=[];draw(k,reload);assert(k.w.inspect().trialMaps.enemyMotion.history.every(h=>h.cause===null));}finally{k.close();}});
for(const defect of ['index','future','origin','target','nan','actor','wrong-kind','missing-source'])test('U malformed outgoing '+defect+' never starts a pose',()=>{const k=rig(),s=seed();try{draw(k,s);const e=emit(s,1)[0];if(defect==='index')e.enemyAction.index=0;if(defect==='future')e.enemyAction.tick=s.ticks+1;if(defect==='origin')e.enemyAction.origin.x+=1;if(defect==='target')e.enemyAction.target.z+=1;if(defect==='nan')e.enemyAction.origin.x=NaN;if(defect==='actor')e.actor=0;if(defect==='wrong-kind')e.kind='heal';if(defect==='missing-source')delete e.enemyAction;draw(k,s,[e]);assert(!k.w.inspect().trialMaps.enemyMotion.history.some(h=>h.cause));}finally{k.close();}});
test('U combat handoff preserves later ambient NPC seeds without double ownership',()=>{const k=rig(),s=seed('cellblock');let seeds;try{draw(k,s);assert.equal(k.w.inspect().trialMaps.motion.actors.length,1);const on=k.w.scene.meshes.filter(m=>m.name==='cellblockguard');assert.equal(on.length,3);s.chapter='hall1000';s.mode='explore';draw(k,s);seeds=k.w.inspect().trialMaps.motion.actors.map(a=>[a.name,a.seed]);}finally{k.close();}const old=rig(PriorWorld),o=seed('cellblock');try{old.w.draw(o,0,false,[]);o.chapter='hall1000';o.mode='explore';old.w.draw(o,0,false,[]);assert.deepEqual(seeds,old.w.inspect().trialMaps.motion.actors.map(a=>[a.name,a.seed]));}finally{old.close();}});
test('U history bounded and independent snapshots; resource count unaffected by ongoing actions',()=>{const k=rig(),s=seed();try{draw(k,s);const c=counts(k);for(let i=0;i<80;i++){s.players.forEach(p=>p.hp=120);const es=emit(s,i%2+1);const before=structuredClone(es);draw(k,s,es);assert.deepEqual(es,before);}const m=k.w.inspect().trialMaps.enemyMotion;assert.equal(m.history.length,24);assert(m.historyDropped>0);m.history[0].cause.tick=-5;assert(k.w.inspect().trialMaps.enemyMotion.history[0].cause.tick>=0);advance(s,76);draw(k,s);assert.deepEqual(counts(k),c);k.w.engine.dispose();assert.equal(k.w.trialWorld.inspect().enemyMotion.disposed,true);assert.equal(k.w.trialWorld.inspect().enemyMotion.bindings.length,0);}finally{k.close();}});

for(const [width,height]of [[192,128],[256,160],[240,180]])test(`U actual CPU cells change only during source action and restore T tank ${width}x${height}`,()=>{for(const [kind,index,chapter]of [['prisonGuard',0,'cellblock'],['tankHead',0,'prisonbridge'],['tankBody',1,'prisonbridge'],['tankWheel',2,'prisonbridge']]){const a=rig(World,width,height),b=rig(PriorWorld,width,height);try{const s=seed(chapter),p=structuredClone(s);draw(a,s);draw(b,p);assert.deepEqual(a.c.pixels(),b.c.pixels());if(kind==='tankHead')s.enemies[1].hp=p.enemies[1].hp=160;s.enemies[index].atb=p.enemies[index].atb=.999;core.step(s,core.IDLE,1/60);prior.step(p,prior.IDLE,1/60);draw(a,s);draw(b,p);assert.deepEqual(s,p);assert.notDeepEqual(a.c.pixels(),b.c.pixels());advance(s,24);for(let n=0;n<24;n++)prior.step(p,prior.IDLE,1/60);draw(a,s);draw(b,p);if(kind==='prisonGuard'){a.media.matches=b.media.matches=true;draw(a,s);draw(b,p);}assert.deepEqual(a.c.pixels(),b.c.pixels());assert.deepEqual(counts(a),counts(b));mkdirSync('test-results/trial-enemy-offline',{recursive:true});writeFileSync(`test-results/trial-enemy-offline/pixels-${kind}-${width}x${height}.json`,JSON.stringify({scope:'offline real CPU rasterization,not native',positivePixels:true,restoredT:true,guardRestoreUsesOriginalReducedMode:kind==='prisonGuard',counts:counts(a),stateUnchanged:true}));}finally{b.close();a.close();}}});
test('U a new slot owner cannot inherit a previous attack and dead defeat texture does not update',()=>{const k=rig(),s=seed();try{draw(k,s);draw(k,s,emit(s,1));assert(k.w.inspect().trialMaps.enemyMotion.history.some(h=>h.index===1&&h.cause));s.enemies[1]=structuredClone(s.enemies[1]);draw(k,s);assert(!k.w.inspect().trialMaps.enemyMotion.history.some(h=>h.index===1&&h.cause));s.enemies[1].hp=0;s.mode='defeat';const n=k.w.inspect().trialMaps.enemyMotion.bindings[1].uploads;draw(k,s);s.ticks+=20;draw(k,s);assert.equal(k.w.inspect().trialMaps.enemyMotion.bindings[1].uploads,n);}finally{k.close();}});
test('U borrowed binding rejects foreign/doubled/invalid texture owners and disposes references',()=>{const k=rig(),s=seed();try{draw(k,s);const m=mesh(k,0,s),c=new TrialEnemyMotion(k.w.scene),n=counts(k);assert.throws(()=>c.bind(m,'other',0,s.chapter));assert.throws(()=>c.bind(m,'prisonGuard',0,s.chapter));assert.throws(()=>c.bind(m,'tankHead',-1,s.chapter));c.bind(m,'tankHead',0,s.chapter);assert.throws(()=>c.bind(m,'tankHead',0,s.chapter));assert.deepEqual(counts(k),n);c.dispose();c.draw(s);assert(c.inspect().disposed);assert.equal(c.inspect().bindings.length,0);assert.deepEqual(counts(k),n);}finally{k.close();}});

for(const name of Object.keys(trialUSpec.files))test('U source-only inverse preserves T and rejects missing/duplicate/unrelated drift '+name,()=>{const raw=trialBodyVIfDeclared(name,readFileSync(name,'utf8')),old=trialUBaseline(name,raw),e=trialUSpec.files[name][0];assert.equal(sha(old),trialUSpec.originalSha256[name]);assert.equal(trialUIfDeclared(name,old),old);for(const bad of [raw.replace(e.after,''),raw+e.after,raw+'\n// unrelated drift'])assert.throws(()=>trialUBaseline(name,bad));});
test('U original gameplay core, painters, prior controllers, CPU, input and workflow bytes retained',()=>{for(const [name,h]of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03u-unchanged-inputs.json'))))assert.equal(sha(trialBodyVIfDeclared(name,readFileSync(name,'utf8'))),h,name);});
test('U original tankFrame diagnostic reports the actual cached body cell, including action poses',()=>{const k=rig(),s=seed();try{draw(k,s);for(const age of [0,8,16,24]){if(age===0)draw(k,s,emit(s,1));else{advance(s,8);draw(k,s);}const v=k.w.inspect().trialMaps,b=v.enemyMotion.bindings.find(b=>b.kind==='tankBody');assert.equal(v.tankFrame,b.frame);assert.deepEqual(rgba(mesh(k,1,s)),cell('tankBody',v.tankFrame).rgba);}}finally{k.close();}});
