"""Synthetic offline reports generated by production core/CPU fixtures; never native evidence."""
import copy,json,gzip,unittest,tempfile,inspect,hashlib
from pathlib import Path
from trial_enemy_body import assert_trial_body_observation,assert_trial_body_report,capture_trial_body,write_trial_body_report,OBSERVE_SCRIPT,BOUNDARIES
from trial_body_v_preservation import SPEC,restore_trial_body_v_source,restore_trial_body_v_if_declared
ROOT=Path(__file__).resolve().parents[1]
FIX=json.loads(gzip.decompress((ROOT/'tests/fixtures/trial-body-offline.json.gz').read_bytes()))
SHA='a'*40

def sample(name='action-tankBody'):return copy.deepcopy(FIX[name])
def report():
    guard=sample('action-prisonGuard');guard['state']['mode']='victory'
    stair=copy.deepcopy(guard);stair['state']['chapter']=stair['body']['chapter']='prisonstairs'
    for h in stair['body']['history']:h['cause']['chapter']='prisonstairs'
    tank=sample();victory=sample('death-tankHead');victory['state']['mode']='victory'
    return {'status':'passed','sourceSha':SHA,'build':{'sourceSha':SHA,'version':'0.9.69','batch':'VQ03V'},'errors':[],'nativeInputsOnly':True,'physicalDevice':False,'artApproved':False,'fullAnimationComplete':False,'framebufferSynchronized':False,'observations':dict(zip(BOUNDARIES,[guard,stair,tank,copy.deepcopy(tank),victory,copy.deepcopy(stair)]))}

class TrialBody(unittest.TestCase):
    def test_all_actual_offline_sources_and_deaths(self):
        for name,o in FIX.items():
            v=assert_trial_body_observation(o)
            if name.startswith('action-'):self.assertEqual(v['restoredBodyActions'],1)
            if name.startswith('recoil-'):self.assertEqual(v['positiveRecoils'],1)
            if name.startswith('death-'):self.assertEqual(v['completeRemnants'],1)
    def test_report_all_boundaries_and_sha(self):
        r=report();before=copy.deepcopy(r);v=assert_trial_body_report(r,SHA);self.assertEqual(r,before);self.assertEqual(len(v),6)
    def test_no_actual_action_remains_missing_not_fabricated(self):
        r=report()
        for o in r['observations'].values():o['body']['history']=[]
        with self.assertRaises(AssertionError):assert_trial_body_report(r,SHA)
        self.assertTrue(all(x['positiveBodyActions']==0 for x in assert_trial_body_report(r,SHA,require_actions=False).values()))
    def test_wrong_source_and_build_not_accepted(self):
        for field,value in [('sourceSha','b'*40),('status','failed'),('errors',['actual']),('nativeInputsOnly',False),('physicalDevice',True),('artApproved',True),('fullAnimationComplete',True),('framebufferSynchronized',True)]:
            r=report();r[field]=value
            with self.assertRaises(AssertionError):assert_trial_body_report(r,SHA)
        r=report();r['build']['batch']='VQ03U'
        with self.assertRaises(AssertionError):assert_trial_body_report(r,SHA)
    def test_boundary_missing_and_order_rejected(self):
        r=report();r['observations'].pop('tank-repair')
        with self.assertRaises(AssertionError):assert_trial_body_report(r,SHA)
    def test_no_state_mutation_or_framebuffer_promotion(self):
        for key,val in [('tick',-1),('stateMutation',True),('approved',True),('disposed',True),('historyLimit',25),('historyDropped',-1)]:
            o=sample();o['body'][key]=val
            with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_resources_bounded_and_failures_are_not_hidden(self):
        for key,val in [('active',4),('rawTextureBytes',49153),('created',-1),('released',-1),('creationFailures',1),('maxTextureBytes',100000)]:
            o=sample();o['body']['resources'][key]=val
            with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_original_source_index_tick_origin_target_required(self):
        for key,val in [('index',0),('tick',-1),('origin',{'x':999,'z':0}),('target',{'x':0,'z':999})]:
            o=sample();o['body']['history'][0]['cause']['effect']['enemyAction'][key]=val
            with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_head_repair_cannot_be_an_attack(self):
        o=sample();c=o['body']['history'][0]['cause'];c['foeKind']='tankHead';c['index']=0
        with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_phase_and_positions_must_match_actual_curve(self):
        for key,val in [('position',[999,0,0]),('offset',{'x':99,'z':0}),('phase','expired'),('tick',-1),('scope','framebuffer')]:
            o=sample();o['body']['history'][1][key]=val
            with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_living_hp_delta_essential_no_zero_damage_inference(self):
        for key,val in [('hpBefore',0),('hpAfter',0),('hpAfter',999)]:
            o=sample('recoil-tankHead');o['body']['history'][0]['cause'][key]=val
            with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_recoil_origin_required(self):
        o=sample('recoil-tankBody');del o['body']['history'][0]['cause']['effect']['origin']
        with self.assertRaises((AssertionError,KeyError)):assert_trial_body_observation(o)
    def test_death_copy_requires_original_disabled(self):
        o=sample('death-tankHead');o['body']['history'][0]['originalEnabled']=True
        with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_static_cell_does_not_change_or_invent_pixels(self):
        o=sample('death-tankHead');o['body']['history'][1]['cell']['fnv1a32']^=1
        with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_death_fade_and_foot_geometry_checked(self):
        for key,val in [('alpha',1),('scale',[1,1,1]),('position',[99,99,99])]:
            o=sample('death-tankHead');o['body']['history'][2][key]=val
            with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_missing_death_phase_is_gap_not_complete(self):
        o=sample('death-tankHead');o['body']['history']=[h for h in o['body']['history'] if h['phase']!='late'];v=assert_trial_body_observation(o);self.assertEqual(v['deathRemnants'],1);self.assertEqual(v['completeRemnants'],0)
    def test_history_order_and_tick_validated(self):
        o=sample();o['body']['history'].reverse()
        with self.assertRaises(AssertionError):assert_trial_body_observation(o)
    def test_capture_is_one_read_and_failure_is_persisted(self):
        o=sample();calls=[]
        class Page:
            def evaluate(self,script):calls.append(script);return copy.deepcopy(o)
        with tempfile.TemporaryDirectory() as t:
            out=Path(t);obs={};capture_trial_body(Page(),out,'tank-animation',obs);self.assertEqual(calls,[OBSERVE_SCRIPT]);self.assertEqual(json.loads((out/'trial-body-tank-animation-observation.json').read_text()),o)
            r=report();write_trial_body_report(out,r['observations'],r['build'],SHA,[])
            with self.assertRaises(AssertionError):write_trial_body_report(out,r['observations'],r['build'],SHA,['actual failure'])
            self.assertEqual(json.loads((out/'trial-enemy-body-report.json').read_text())['status'],'failed')
        for bad in ('.keyboard','.click','.wait','localStorage','setState'):self.assertNotIn(bad,inspect.getsource(capture_trial_body))
    def test_native_routes_exact_U_after_source_only_inverse(self):
        for name in ('tests/trial_browser.py','tests/rescue_browser.py','tests/field_enemy_action_browser.py'):
            old=restore_trial_body_v_source(name,(ROOT/name).read_text());self.assertEqual(hashlib.sha256(old.encode()).hexdigest(),SPEC['originalSha256'][name])
    def test_source_inverse_negative_missing_duplicate_drift(self):
        for name,edits in SPEC['files'].items():
            raw=(ROOT/name).read_text();old=restore_trial_body_v_source(name,raw);self.assertEqual(restore_trial_body_v_if_declared(name,old),old);e=edits[0]
            for bad in (raw.replace(e['after'],'',1),raw+e['after'],raw+'\n// drift'):
                with self.assertRaises(AssertionError):restore_trial_body_v_source(name,bad)
if __name__=='__main__':unittest.main()
