import {trialHistoryWIfDeclared} from './helpers/trial-history-w-baseline.mjs';
/** Offline fixtures with actual core delivery and production CPU rendering; not native evidence. */
import test from 'node:test';
import {DynamicTexture,MeshBuilder} from '@babylonjs/core';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {png} from '../scripts/asset-export.mjs';
import {gzipSync} from 'node:zlib';
import * as core from '../.test/core.mjs';
import {beginTrialBattle} from '../.test/trial-rules.mjs';
import {World} from '../.test/cpu-entry.mjs';
import {World as PriorWorld} from '../.test/trial-body-v-prior-world.mjs';
import {TrialEnemyBody,trialBodyOffset,TRIAL_BODY} from '../.test/trial-enemy-body.mjs';
import {cpuTestCanvas} from './cpu-test-canvas.mjs';
import {trialBodyVBaseline,trialBodyVIfDeclared,trialBodyVSpec} from './helpers/trial-body-v-baseline.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
const near=(a,b)=>assert(Math.abs(a-b)<1e-10,`${a} != ${b}`);
const vnear=(a,b)=>a.forEach((x,i)=>near(x,b[i]));
const kinds=[['prisonGuard',0,'cellblock'],['tankHead',0,'prisonbridge'],['tankBody',1,'prisonbridge'],['tankWheel',2,'prisonbridge']];
function seed(chapter='prisonbridge'){
 const s=core.createState(chapter);s.kingdom.phase='rescue';s.joined=true;
 Object.assign(s.trial,{stage:chapter==='prisonbridge'?'tank':'escape',knocks:3,luccaJoined:chapter==='prisonbridge',guardsWon:chapter==='prisonbridge',fade:0});
 beginTrialBattle(s,chapter==='prisonbridge'?'tank':chapter==='cellblock'?'cellguards':'stairguards');return s;
}
function rig(W=World,width=192,height=128){const saved=[globalThis.document,globalThis.window,globalThis.matchMedia],media={matches:false};const doc={createElement:t=>t==='canvas'?cpuTestCanvas(1,1).canvas:{style:{}},getElementById:()=>null,addEventListener(){},removeEventListener(){}};globalThis.document=doc;globalThis.window={devicePixelRatio:1,addEventListener(){},removeEventListener(){},navigator:{}};globalThis.matchMedia=()=>media;const c=cpuTestCanvas(width,height);c.canvas.ownerDocument=doc;const w=new W(c.canvas);return {w,c,media,close(){w.engine.dispose();[globalThis.document,globalThis.window,globalThis.matchMedia]=saved;}};}
function draw(k,s,es=s.effects.splice(0)){
 const before=structuredClone(s),effects=structuredClone(es);k.w.draw(s,0,false,es);assert.deepEqual(s,before);assert.deepEqual(es,effects);return k.w.inspect().trialMaps.enemyBody;
}
function advance(s,n){for(let i=0;i<n;i++)core.step(s,core.IDLE,1/60);}
function emit(s,i){s.effects.length=0;s.enemies[i].atb=.999;advance(s,1);const es=s.effects.splice(0);assert(es.some(e=>e.enemyAction?.index===i));return es;}
function mesh(k,i,s){return s.chapter==='prisonbridge'?k.w.scene.getMeshByName('prisonbridge'+['tank-head','tank-body','tank-wheel'][i]):k.w.scene.meshes.filter(m=>m.name===s.chapter+'guard').slice(-2)[i];}
function rgba(m){const t=m.material.diffuseTexture,z=t.getSize();return Buffer.from(t.getContext().getImageData(0,0,z.width,z.height).data);}
const counts=k=>[k.w.scene.meshes.length,k.w.scene.materials.length,k.w.scene.textures.length];
function damage(s,i,lethal=false){
 if(lethal)s.enemies[i].hp=1;
 s.players[0].atb=1;s.targets[0]=i;s.effects.length=0;assert(core.action(s,0,'attack'));return s.effects.splice(0);
}
const fixtures={};function save(name,k,s){fixtures[name]={state:structuredClone(s),body:k.w.inspect().trialMaps.enemyBody};mkdirSync('test-results/trial-body-offline',{recursive:true});writeFileSync('test-results/trial-body-offline/observations.json',JSON.stringify(fixtures,null,2));writeFileSync('test-results/trial-body-offline/observations.json.gz',gzipSync(JSON.stringify(fixtures),{mtime:0}));}

test('V presentation profile is bounded and unapproved',()=>{assert.equal(TRIAL_BODY.deathTicks,24);assert.equal(TRIAL_BODY.remnantLimit,3);assert.equal(TRIAL_BODY.maxTextureBytes,49152);assert.equal(TRIAL_BODY.approved,false);});
for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1]])test(`V authored curve source direction ${dx},${dz}`,()=>{
 const e={kind:'hit',x:dx,z:dz,origin:{x:0,z:0},enemyAction:{index:0,tick:10,origin:{x:0,z:0},target:{x:dx,z:dz}}};
 for(const [kind,distance]of [['prisonGuard',.20],['tankBody',-.08],['tankWheel',.10],['tankHead',0]]){
  const c={kind:'attack',tick:10,foeKind:kind,effect:e},d=trialBodyOffset(c,22,false),n=Math.hypot(dx,dz);near(d.x,dx/n*distance);near(d.z,dz/n*distance);
  for(const age of [0,24,99])assert.deepEqual(trialBodyOffset(c,10+age,false),{x:0,z:0});assert.deepEqual(trialBodyOffset(c,22,true),{x:0,z:0});
 }
 const c={kind:'recoil',tick:10,foeKind:'tankBody',effect:e},d=trialBodyOffset(c,19,false);near(Math.hypot(d.x,d.z),.10);assert.deepEqual(trialBodyOffset(c,28,false),{x:0,z:0});
});
test('V invalid clocks and reduced arguments rejected',()=>{for(const tick of [-1,NaN,Infinity,.5])assert.throws(()=>trialBodyOffset({tick:0},tick,false));assert.throws(()=>trialBodyOffset({tick:0},1,'true'));});
for(const [kind,index,chapter]of kinds.filter(x=>x[0]!=='tankHead'))test('V real '+kind+' delivery moves original anchor then restores it',()=>{const k=rig(),s=seed(chapter);try{
 draw(k,s);const b=mesh(k,index,s),anchor=b.position.asArray(),es=emit(s,index);draw(k,s,es);vnear(b.position.asArray(),anchor);
 for(const age of [3,12,21]){advance(s,age-(s.ticks-es[0].enemyAction.tick));draw(k,s);const m=k.w.inspect().trialMaps.enemyBody,c=m.history.find(h=>h.cause.kind==='attack'&&h.cause.index===index).cause,d=trialBodyOffset(c,s.ticks,false);vnear(b.position.asArray(),[anchor[0]+d.x,anchor[1],anchor[2]+d.z]);}
 advance(s,3);draw(k,s);vnear(b.position.asArray(),anchor);assert(k.w.inspect().trialMaps.enemyBody.history.some(h=>h.phase==='expired'));save('action-'+kind,k,s);
 }finally{k.close();}});
test('V head multiple repairs are not a physical strike; wheel victims do not duplicate its source',()=>{const k=rig(),s=seed();try{draw(k,s);s.enemies[1].hp-=30;s.enemies[2].hp-=30;const p=mesh(k,0,s).position.asArray();draw(k,s,emit(s,0));advance(s,8);draw(k,s);vnear(mesh(k,0,s).position.asArray(),p);assert(!k.w.inspect().trialMaps.enemyBody.history.some(h=>h.cause.index===0));const es=emit(s,2);assert.equal(es.length,2);draw(k,s,es);const m=k.w.inspect().trialMaps.enemyBody;assert.equal(m.history.filter(h=>h.cause.index===2&&h.phase==='start').length,1);draw(k,s,es);assert.equal(k.w.inspect().trialMaps.enemyBody.history.length,m.history.length);}finally{k.close();}});
for(const [kind,index,chapter]of kinds)test('V living '+kind+' actual HP loss causes source-directed recoil',()=>{const k=rig(),s=seed(chapter);try{draw(k,s);const b=mesh(k,index,s),p=b.position.asArray();const es=damage(s,index);draw(k,s,es);advance(s,9);draw(k,s);assert.notDeepEqual(b.position.asArray(),p);advance(s,9);draw(k,s);vnear(b.position.asArray(),p);save('recoil-'+kind,k,s);}finally{k.close();}});
test('V shielded zero-damage flame creates no head/body recoil',()=>{const k=rig(),s=seed();try{draw(k,s);const hp=s.enemies.map(e=>e.hp);s.players[1].atb=1;s.targets[1]=0;assert(core.action(s,1,'skill'));draw(k,s);assert.deepEqual(s.enemies.map(e=>e.hp),hp);assert(!k.w.inspect().trialMaps.enemyBody.history.some(h=>h.cause.kind==='recoil'));}finally{k.close();}});
for(const [kind,index,chapter]of kinds)test('V '+kind+' lethal actual hit uses independent static copy and expires',()=>{const k=rig(),s=seed(chapter);try{
 s.enemies[index].hp=1;draw(k,s);const b=mesh(k,index,s),pixels=rgba(b),c=counts(k),p=b.position.asArray();draw(k,s,damage(s,index));let m=k.w.inspect().trialMaps.enemyBody;
 assert.equal(b.isEnabled(),false);assert.equal(m.resources.active,1);assert.deepEqual(counts(k),c.map(n=>n+3));const g=k.w.scene.getMeshByName('trial-remnant-'+index);assert(g);assert.deepEqual(rgba(g),pixels);assert.notEqual(g.material.diffuseTexture,b.material.diffuseTexture);vnear(g.position.asArray(),p);
 const copy=g.material.diffuseTexture;for(const age of [1,8,16,23]){s.ticks=m.remnants[0].deathTick+age;draw(k,s,[]);assert.equal(k.w.inspect().trialMaps.enemyBody.remnants[0].textureUploads,1);assert.equal(g.material.diffuseTexture,copy);assert.deepEqual(rgba(g),pixels);const h=k.w.inspect().trialMaps.enemyBody.history.at(-1);if(h.cause.kind==='death'&&h.phase!=='start'){const q=(h.tick-h.cause.tick)/24;near(h.alpha,.82*(1-q));const geo=h.geometry;geo.base.forEach((v,i)=>near(h.position[i]+geo.up[i]*geo.height*geo.scale[1]*.3*q,v));}}
 s.ticks=m.remnants[0].deathTick+24;draw(k,s,[]);m=k.w.inspect().trialMaps.enemyBody;assert.equal(m.resources.active,0);assert.equal(m.resources.created,m.resources.released);assert.deepEqual(counts(k),c.map(n=>n+2));assert.equal(g.isDisposed(),true);save('death-'+kind,k,s);s.ticks+=52;draw(k,s,[]);assert.deepEqual(counts(k),c);
 }finally{k.close();}});
test('V same tick, pause-style redraw, reduced toggle never accumulates body motion or texture work',()=>{const k=rig(),s=seed();try{draw(k,s);draw(k,s,emit(s,1));advance(s,7);draw(k,s);const p=mesh(k,1,s).position.asArray(),pixels=Buffer.from(k.c.pixels()),m=structuredClone(k.w.inspect().trialMaps.enemyBody);for(let n=0;n<15;n++){draw(k,s);vnear(mesh(k,1,s).position.asArray(),p);assert.deepEqual(Buffer.from(k.c.pixels()),pixels);assert.deepEqual(k.w.inspect().trialMaps.enemyBody,m);}k.media.matches=true;draw(k,s);const h=k.w.inspect().trialMaps.enemyBody.history.at(-1);assert.deepEqual(h.offset,{x:0,z:0});k.media.matches=false;draw(k,s);vnear(mesh(k,1,s).position.asArray(),p);}finally{k.close();}});
for(const why of ['reduced','rewind','identity','chapter','defeat','resurrect','dispose'])test('V death copy cleanup on '+why,()=>{const k=rig(),s=seed();try{s.enemies[0].hp=1;draw(k,s);draw(k,s,damage(s,0));assert.equal(k.w.inspect().trialMaps.enemyBody.resources.active,1);if(why==='reduced')k.media.matches=true;if(why==='rewind')s.ticks=-0;if(why==='identity')s.enemies[0]=structuredClone(s.enemies[0]);if(why==='chapter')s.chapter='warden';if(why==='defeat')s.mode='defeat';if(why==='resurrect')s.enemies[0].hp=10;if(why==='dispose'){k.w.trialWorld.dispose?.();k.w.scene.dispose();assert.equal(k.w.trialWorld.inspect().enemyBody.disposed,true);return;}if(why==='rewind'){s.ticks=10;draw(k,s,[]);s.ticks=0;}draw(k,s,[]);assert.equal(k.w.inspect().trialMaps.enemyBody.resources.active,0);}finally{k.close();}});
test('V first-dead or unobserved lethal state does not invent a death event',()=>{const k=rig(),s=seed();try{s.enemies[0].hp=0;draw(k,s);assert.equal(k.w.inspect().trialMaps.enemyBody.resources.active,0);s.enemies[1].hp=0;draw(k,s);assert.equal(k.w.inspect().trialMaps.enemyBody.resources.active,0);}finally{k.close();}});
test('V hidden foe cannot create a copy or carry stale displacement',()=>{const k=rig(),s=seed();try{draw(k,s);draw(k,s,emit(s,1));advance(s,5);draw(k,s);mesh(k,1,s).isVisible=false;draw(k,s);const h=k.w.inspect().trialMaps.enemyBody.history.length;advance(s,10);draw(k,s);assert.equal(k.w.inspect().trialMaps.enemyBody.history.length,h);mesh(k,1,s).isVisible=true;draw(k,s);assert.equal(k.w.inspect().trialMaps.enemyBody.resources.active,0);}finally{k.close();}});
for(const defect of ['future','index','origin','target','missing','heal','actor','nan'])test('V rejected outgoing metadata '+defect,()=>{const k=rig(),s=seed();try{draw(k,s);const e=emit(s,1)[0];if(defect==='future')e.enemyAction.tick=s.ticks+1;if(defect==='index')e.enemyAction.index=0;if(defect==='origin')e.enemyAction.origin.x++;if(defect==='target')e.enemyAction.target.z++;if(defect==='missing')delete e.enemyAction;if(defect==='heal')e.kind='heal';if(defect==='actor')e.actor=0;if(defect==='nan')e.x=NaN;draw(k,s,[e]);assert.equal(k.w.inspect().trialMaps.enemyBody.history.length,0);}finally{k.close();}});
test('V body interruption from actual recoil restores old source without logical mutation',()=>{const k=rig(),s=seed();try{draw(k,s);draw(k,s,emit(s,1));advance(s,5);draw(k,s);draw(k,s,damage(s,1));assert.equal(k.w.inspect().trialMaps.enemyBody.history.at(-1).cause.kind,'recoil');advance(s,18);draw(k,s);assert.equal(k.w.inspect().trialMaps.enemyBody.history.at(-1).phase,'expired');}finally{k.close();}});
test('V ambiguous exact targets and origin-less combo do not infer recoil',()=>{const k=rig(),s=seed();try{draw(k,s);const es=damage(s,1);delete es[0].origin;draw(k,s,es);assert.equal(k.w.inspect().trialMaps.enemyBody.history.length,0);s.enemies[2].x=s.enemies[1].x;s.enemies[2].z=s.enemies[1].z;draw(k,s);draw(k,s,damage(s,1));assert.equal(k.w.inspect().trialMaps.enemyBody.history.length,0);}finally{k.close();}});
for(const [w,h]of [[192,128],[256,160],[240,180]])test(`V CPU body/death pixels and U restoration ${w}x${h}`,()=>{for(const [kind,index,chapter]of kinds){const a=rig(World,w,h),b=rig(PriorWorld,w,h);try{const s=seed(chapter),u=structuredClone(s);draw(a,s);draw(b,u);assert.equal(Buffer.from(a.c.pixels()).equals(Buffer.from(b.c.pixels())),true,'exact baseline pixels');s.enemies[index].hp=u.enemies[index].hp=1;draw(a,s);draw(b,u);const es=damage(s,index),us=damage(u,index);draw(a,s,es);draw(b,u,us);assert.deepEqual(s,u);assert.equal(Buffer.from(a.c.pixels()).equals(Buffer.from(b.c.pixels())),false,kind+' death pixels');mkdirSync('test-results/trial-body-offline',{recursive:true});writeFileSync(`test-results/trial-body-offline/${kind}-${w}x${h}-death.png`,png({width:a.c.canvas.width,height:a.c.canvas.height,rgba:Buffer.from(a.c.pixels())}));s.ticks+=24;u.ticks+=24;draw(a,s,[]);draw(b,u,[]);assert.equal(Buffer.from(a.c.pixels()).equals(Buffer.from(b.c.pixels())),true,kind+' U expiry restoration');assert.deepEqual(counts(a),counts(b));}finally{b.close();a.close();}}});
test('V bounded history snapshots and resources do not grow after expiry',()=>{const k=rig(),s=seed();try{draw(k,s);const c=counts(k);for(let n=0;n<40;n++){s.players.forEach(p=>p.hp=120);draw(k,s,emit(s,1));advance(s,3);draw(k,s);}const m=k.w.inspect().trialMaps.enemyBody;assert.equal(m.history.length,24);assert(m.historyDropped>0);m.history[0].cause.tick=-1;assert(k.w.inspect().trialMaps.enemyBody.history[0].cause.tick>=0);advance(s,90);draw(k,s);assert.deepEqual(counts(k),c);}finally{k.close();}});
test('V copy failure cleans all partially owned resources',()=>{const k=rig(),s=seed();try{s.enemies[0].hp=1;draw(k,s);const t=mesh(k,0,s).material.diffuseTexture,ctx=t.getContext(),original=ctx.getImageData,c=counts(k);ctx.getImageData=()=>{throw Error('offline copy failure');};draw(k,s,damage(s,0));ctx.getImageData=original;const m=k.w.inspect().trialMaps.enemyBody;assert.equal(m.resources.active,0);assert.equal(m.resources.creationFailures,1);assert.deepEqual(counts(k),c.map(n=>n+2));s.ticks+=76;draw(k,s,[]);assert.deepEqual(counts(k),c);}finally{k.close();}});
test('V binding validation and borrowed-mesh disposal never owns original art',()=>{const k=rig(),s=seed();try{draw(k,s);const m=mesh(k,0,s),c=new TrialEnemyBody(k.w.scene),n=counts(k);assert.throws(()=>c.bind(m,'bad',0,s.chapter));assert.throws(()=>c.bind(m,'prisonGuard',0,s.chapter));c.bind(m,'tankHead',0,s.chapter);assert.throws(()=>c.bind(m,'tankHead',0,s.chapter));c.dispose();assert(c.inspect().disposed);assert.deepEqual(counts(k),n);assert.equal(m.isDisposed(),false);}finally{k.close();}});
for(const name of Object.keys(trialBodyVSpec.files))test('V strict source inverse '+name,()=>{const raw=trialHistoryWIfDeclared(name,readFileSync(name,'utf8')),old=trialBodyVBaseline(name,raw),e=trialBodyVSpec.files[name][0];assert.equal(sha(old),trialBodyVSpec.originalSha256[name]);assert.equal(trialBodyVIfDeclared(name,old),old);for(const bad of [raw.replace(e.after,''),raw+e.after,raw+'\n// drift'])assert.throws(()=>trialBodyVBaseline(name,bad));});
test('V unchanged core/U animation/art/inputs/workflow retained exactly',()=>{for(const [name,h]of Object.entries(JSON.parse(readFileSync('tests/baselines/vq03v-unchanged-inputs.json'))))assert.equal(sha(trialHistoryWIfDeclared(name,readFileSync(name,'utf8'))),h,name);});

test('V directionless real hit interrupts a lunge without guessing recoil direction',()=>{const k=rig(),s=seed();try{draw(k,s);const base=mesh(k,1,s).position.asArray();draw(k,s,emit(s,1));advance(s,5);draw(k,s);assert.notDeepEqual(mesh(k,1,s).position.asArray(),base);const es=damage(s,1);delete es[0].origin;draw(k,s,es);vnear(mesh(k,1,s).position.asArray(),base);assert(!k.w.inspect().trialMaps.enemyBody.history.some(h=>h.cause.kind==='recoil'));}finally{k.close();}});
test('V simultaneous real tank deaths use three once-uploaded copies within the declared cap',()=>{const k=rig(),s=seed();try{s.enemies.forEach(e=>e.hp=1);draw(k,s);const es=[];for(let i=0;i<3;i++)es.push(...damage(s,i));draw(k,s,es);const m=k.w.inspect().trialMaps.enemyBody;assert.equal(m.resources.active,3);assert.equal(m.resources.rawTextureBytes,49152);assert(m.remnants.every(g=>g.textureUploads===1&&!g.originalEnabled));for(let n=0;n<20;n++){draw(k,s,[]);assert.equal(k.w.inspect().trialMaps.enemyBody.resources.created,3);}k.media.matches=true;draw(k,s,[]);assert.equal(k.w.inspect().trialMaps.enemyBody.resources.active,0);k.media.matches=false;draw(k,s,[]);assert.equal(k.w.inspect().trialMaps.enemyBody.resources.active,0);}finally{k.close();}});
test('V state reload cancels transient sources without recreating dead copies',()=>{const k=rig(),s=seed();try{s.enemies[0].hp=1;draw(k,s);draw(k,s,damage(s,0));const loaded=structuredClone(s);draw(k,loaded,[]);const m=k.w.inspect().trialMaps.enemyBody;assert.equal(m.resources.active,0);assert.equal(m.history.length,0);}finally{k.close();}});
test('V actual CPU source action offsets visibly differ from exact U then restore',()=>{for(const [kind,index,chapter]of kinds.filter(k=>k[0]!=='tankHead')){const a=rig(),b=rig(PriorWorld);try{const s=seed(chapter),u=structuredClone(s);draw(a,s);draw(b,u);draw(a,s,emit(s,index));draw(b,u,emit(u,index));advance(s,12);advance(u,12);draw(a,s);draw(b,u);assert.deepEqual(s,u);assert.equal(Buffer.from(a.c.pixels()).equals(Buffer.from(b.c.pixels())),false,kind+' positive body pixels');advance(s,12);advance(u,12);draw(a,s);draw(b,u);assert.equal(Buffer.from(a.c.pixels()).equals(Buffer.from(b.c.pixels())),true,kind+' exact U returned');}finally{b.close();a.close();}}});

for(const stage of ['upload','mesh'])test('V allocation failure after '+stage+' releases all partial resources',()=>{const k=rig(),s=seed();const oldUpdate=DynamicTexture.prototype.update,oldPlane=MeshBuilder.CreatePlane;try{s.enemies[0].hp=1;draw(k,s);const c=counts(k);if(stage==='upload')DynamicTexture.prototype.update=function(...args){if(this.name.startsWith('trial-remnant-'))throw Error('offline upload failure');return oldUpdate.apply(this,args);};else MeshBuilder.CreatePlane=function(name,...args){if(name.startsWith('trial-remnant-'))throw Error('offline mesh failure');return oldPlane.call(this,name,...args);};draw(k,s,damage(s,0));const m=k.w.inspect().trialMaps.enemyBody;assert.equal(m.resources.active,0);assert.equal(m.resources.creationFailures,1);assert.deepEqual(counts(k),c.map(x=>x+2));s.ticks+=76;draw(k,s,[]);assert.deepEqual(counts(k),c);}finally{DynamicTexture.prototype.update=oldUpdate;MeshBuilder.CreatePlane=oldPlane;k.close();}});
