import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {runInNewContext} from 'node:vm';
import {visibilityRig} from './helpers/visibility-rig.mjs';import {png} from '../scripts/asset-export.mjs';import {assertVisibilityStop} from '../scripts/visibility-evidence.mjs';
const stops=JSON.parse(readFileSync('tests/fixtures/ci71-town-visibility-regression.json')).stops;
const script=readFileSync('tests/town_route_capture.py','utf8').split("VISIBILITY = r'''")[1].split("'''",1)[0];
function observe(name){const k=visibilityRig();try{const state=structuredClone(stops.find(s=>s.name===name).state),before=structuredClone(state);k.current.draw(state,0,false);const view=k.current.inspect(),renderer=k.current.inspectRenderer();
 const observation=runInNewContext('('+script+')()',{window:{__CHRONO_TEST__:{view:()=>k.current.inspect()}},document:{getElementById:id=>id==='world'?k.currentPort.canvas:null}});
 const bytes=png({width:renderer.width,height:renderer.height,rgba:Buffer.from(k.currentPort.pixels())}),v={name,state,renderer,camera:view.earlyComfort,visibility:JSON.parse(JSON.stringify(observation)),canvasImage:{path:`town-route-${name}-canvas.png`,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}};
 assert.deepEqual(state,before);return {v,bytes};}finally{k.close();}}
for(const name of ['entry','resident','inn','exit'])test('D actual read-only observer and independent PNG gate: offline '+name,()=>{const {v,bytes}=observe(name);assert(assertVisibilityStop(v,bytes));});
const mutations={missing:v=>delete v.visibility,approval:v=>v.visibility.artApproved=true,physical:v=>v.visibility.physicalDevice=true,staleTick:v=>v.visibility.woodland.tick++,owner:v=>v.visibility.woodland.groups[3].owner='held-home',extraActor:v=>v.visibility.woodland.subjects.push('npc'),missingTree:v=>v.visibility.woodland.groups.pop(),changedAnchor:v=>v.visibility.woodland.groups[0].position[0]++,scale:v=>v.visibility.woodland.groups[0].scale[0]=.8,filtered:v=>v.visibility.woodland.groups[0].sampling=2,unboundedMasks:v=>v.visibility.woodland.alphaMaskBytes++,rayBudget:v=>v.visibility.woodland.meshRayTests=49,wrongMode:v=>v.visibility.woodland.groups[3].materialMode=1,noExitFade:v=>v.visibility.woodland.groups[3].visibility=1,transparentHit:v=>v.visibility.woodland.groups[3].hits[0].alpha=0,wrongUV:v=>v.visibility.woodland.groups[3].hits[0].pixel[1]++,noFoot:v=>v.visibility.woodland.groups[3].hits[0].sample=3,behind:v=>v.visibility.woodland.groups[3].hits[0].distance=64,noCpuFix:v=>v.visibility.blend.profile='old',negativeCount:v=>v.visibility.blend.faceCulled=-1,noProbe:v=>v.visibility.lowerBody.samples=[],wrongDimension:v=>v.visibility.lowerBody.width++,movedProbe:v=>v.visibility.lowerBody.samples[0].points[0].x++,changedPixel:v=>v.visibility.lowerBody.samples[0].points[0].rgba[0]^=1,wrongHash:v=>v.canvasImage.sha256='0'.repeat(64)};
const example=observe('exit');
for(const [name,mutate]of Object.entries(mutations))test('D native visibility gate rejects '+name,()=>{const v=structuredClone(example.v);mutate(v);assert.throws(()=>assertVisibilityStop(v,example.bytes));});
test('D pixel gate rejects corrupted raw PNG even with a rewritten receipt',()=>{const bytes=Buffer.from(example.bytes);bytes[bytes.length-6]^=1;const v=structuredClone(example.v);v.canvasImage.sha256=createHash('sha256').update(bytes).digest('hex');assert.throws(()=>assertVisibilityStop(v,bytes));});
test('D resident must exercise actual closed-mesh culling',()=>{const {v,bytes}=observe('resident');v.visibility.blend.faceCulled=0;assert.throws(()=>assertVisibilityStop(v,bytes));});
test('D new native gates are unconditional and original six legs/four files remain',()=>{const s=readFileSync('scripts/cpu-era-evidence.mjs','utf8');assert.match(s,/assertVisibilityStop\(v,b\)/);assert.match(s,/assertTownRoute\(r\.townReadability/);assert.match(s,/assertTownBuildingRoute\(r\.townReadability\)/);assert.match(s,/assertTownLandmarkRoute\(r\.townReadability\)/);const p=readFileSync('tests/town_route_capture.py','utf8');assert.match(p,/visibility=p\.evaluate\(VISIBILITY\)/);assert.doesNotMatch(script,/keyboard|press\(|setTimeout|Date\.now|snapshot\(|dispatch|\.click\(|save|collision/);});
